### PR TITLE
fixed substatus on ftb_import

### LINKED ISSUE #1342: Very big percentage values when downloading specific modpacks
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

QT 6.5.1

### Description of bug

I have observed that downloading any FTB Legacy modpack will show the progress next to the name be like, 100000 times bigger than should. That text also seems a bit redundant as it is included right below in progress bar.
image

### Steps to reproduce

* Download any FTB Legacy modpack

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #1342

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

File: launcher/modplatform/legacy_ftb/PackInstallTask.cpp [hunk 1]
```diff
@@ -65,6 +65,7 @@ void PackInstallTask::executeTask()
 void PackInstallTask::downloadPack()
 {
     setStatus(tr("Downloading zip for %1").arg(m_pack.name));
+    setProgress(1, 4);
```
Comment (Ryex) [inline launcher/modplatform/legacy_ftb/PackInstallTask.cpp:68]: The only line that fixes anything? :P

Comment (Trial97) [reply launcher/modplatform/legacy_ftb/PackInstallTask.cpp:68]: Nope, the progress signal was weird so I also yanked it out. 
Regarding the format, I presumed that it would be ok to have it as this is a small PR.
If needed I can remove the format

Comment (Scrumplex) [reply launcher/modplatform/legacy_ftb/PackInstallTask.cpp:68]: > If needed I can remove the format

maybe you can just split it up into two commits to make it easier to separate formatting and actual changes

Comment (Trial97) [reply launcher/modplatform/legacy_ftb/PackInstallTask.cpp:68]: > maybe you can just split it up into two commits to make it easier to separate formatting and actual changes

Thanks for the suggestion

Comment (TayouVR) [reply launcher/modplatform/legacy_ftb/PackInstallTask.cpp:68]: so uhhh, this just sets it to 25%? 1/4th

Comment (Trial97) [reply launcher/modplatform/legacy_ftb/PackInstallTask.cpp:68]: yeah but now has a sub-task that progresses normally.
Up the progress of the final task, down the progress of the subtask.

Comment (TayouVR) [reply launcher/modplatform/legacy_ftb/PackInstallTask.cpp:68]: thats fine I suppose ^^

**Review by TayouVR — APPROVED** [review]
