### PR TITLE
Skip parsing open QSaveFile temprary files as resources

### LINKED ISSUE #2822: Large mod operations can be really unstable
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 5.15.13

### Description of bug

When doing large operations involving mods (updating, creating metadata, checking dependencies, downloading large amounts of mods, etc...), the launcher will often randomly crash with no explanation

### Steps to reproduce

* Do a heavy operation as mentioned previously
* The launcher might crash (may take a few attempts)

### Suspected cause

Likely an operation failing propagating to the rest of the launcher instead of being handled

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #2945: Crash when trying to download shaders.
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.0

### Version of Qt

Qt 6.7.3

### Description of bug

I tried to download Complementary shaders, but the launcher suddenly closed by itself, which should not happen. The shaders downloaded, but I can no longer reproduce this crash. Maybe logs can help you
[PrismLauncher-1.log](https://github.com/user-attachments/files/17460591/PrismLauncher-1.log)

### Steps to reproduce

Press Shader packs tab;
Press Download shaders button;
Select (any?) Complementary shaders;
Donwload them.

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
this PR aims to fix:  #2822 and #2945
That is the aim but I'm unsure if this fixes it.
I'm not able to reproduce the crashes.
Here is what I think happens:
- user downloads resources 
- we use QSaveFile to save the file
- in the process that generates a temporary file(usually in the same folder); the temporary file name adds the `.XXXXXX` suffix to the original file name, where the `XXXXXX` part is dynamically generated to ensure uniqueness.
- because this adds a file to the resource folder Prism triggers a signal in ResourceFolderModel that the directory changed and needs updating
- when updating we open the files to identify some basic information(authors, version, mod loader)
- at this point can happen two things:
  - the file is detected but is removed before we try to open it(possibly throws an error and crashes due to this)
  - the QSaveFile tries to delete it while we try to parse it and on Windows, you can not remove an open file

The reason why I suspect the QSaveFile being the issue is because I saw similar logs on windows crashes:
`Failed to count hard links for "D:/PrismLauncher/instances/1.20.1/.minecraft/shaderpacks/ComplementaryUnbound_r5.3.zip.cYjxxa" : "�� ������� ����� ��������� ����."`

### CODE REVIEW

File: launcher/minecraft/mod/tasks/BasicFolderLoadTask.h [hunk 1]
```diff
@@ -52,6 +53,11 @@ class BasicFolderLoadTask : public Task {
         m_dir.refresh();
         for (auto entry : m_dir.entryInfoList()) {
             auto filePath = entry.absoluteFilePath();
+#if defined Q_OS_WIN32
+            if (APPLICATION->checkQSavePath(filePath)) {
+                continue;
+            }
+#endif
```
Comment (Ryex) [inline launcher/minecraft/mod/tasks/BasicFolderLoadTask.h]: Why only do this check on windows? it seems reasonable to me to not try to parse a file that is in the process of being saved on any os.

File: launcher/Application.cpp [hunk 2]
```diff
@@ -1883,3 +1883,28 @@ const QString Application::javaPath()
...
+{
+    QMutexLocker locker(&m_qsaveResourcesMutex);
+    m_qsaveResources.remove(path);
+}
+
+bool Application::checkQSavePath(QString path)
+{
+    QMutexLocker locker(&m_qsaveResourcesMutex);
+    for (auto r : m_qsaveResources) {
+        if (path.contains(r)) {
```
Comment (Ryex) [inline launcher/Application.cpp]: wouldn't this be safer as `startsWith` ?

File: launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp [hunk 3]
```diff
@@ -65,6 +66,11 @@ void ModFolderLoadTask::executeTask()
     m_mods_dir.refresh();
     for (auto entry : m_mods_dir.entryInfoList()) {
         auto filePath = entry.absoluteFilePath();
+#if defined Q_OS_WIN32
```
Comment (Ryex) [inline launcher/minecraft/mod/tasks/ModFolderLoadTask.cpp]: dito

File: launcher/minecraft/mod/tasks/BasicFolderLoadTask.h (hunk 1 above)
Comment (Trial97) [reply launcher/minecraft/mod/tasks/BasicFolderLoadTask.h]: You are right.
I focused on windows because the crash happens only there.

File: launcher/modplatform/packwiz/Packwiz.cpp [hunk 4]
```diff
@@ -72,7 +72,6 @@ auto stringEntry(toml::table table, QString entry_name) -> QString
 {
     auto node = table[StringUtils::toStdString(entry_name)];
     if (!node) {
-        qCritical() << "Failed to read str property '" + entry_name + "' in mod metadata.";
```
Comment (Ryex) [inline launcher/modplatform/packwiz/Packwiz.cpp:75]: qCritical()
> exits if the environment variable QT_FATAL_CRITICALS is not empty.

while I'm ok with changing it to a non fatal version I thing we should keep the log

File: launcher/modplatform/packwiz/Packwiz.cpp [hunk 5]
```diff
@@ -83,7 +82,6 @@ auto intEntry(toml::table table, QString entry_name) -> int
 {
     auto node = table[StringUtils::toStdString(entry_name)];
     if (!node) {
-        qCritical() << "Failed to read int property '" + entry_name + "' in mod metadata.";
```
Comment (Ryex) [inline launcher/modplatform/packwiz/Packwiz.cpp:86]: ditto

**Review by Ryex — CHANGES_REQUESTED** [review]

File: launcher/Application.cpp (hunk 2 above)
Comment (TheKodeToad) [reply launcher/Application.cpp]: Using contains seems better (will be optimised by set), why can't you match the full thing?

Comment (Trial97) [reply launcher/Application.cpp]: the path here is the absolute path, while the `r`(part from `m_qsaveResources`) is not guaranteed to be absolute and may be relative.

Comment (TheKodeToad) [reply launcher/Application.cpp]: You could resolve the path in the constructor and grab the last component of the path. I see now there isn't a way to retrieve the suffix on qsavefile though

Comment (Trial97) [reply launcher/Application.cpp]: The path can't be retrieved from QSaveFile sadly

Comment (Ryex) [reply launcher/Application.cpp]: ah.

**Review by Ryex — APPROVED** [review]
https://discord.com/channels/1031648380885147709/1284224536358944829/1298056285211856967

File: launcher/Application.cpp [hunk 6]
```diff
@@ -1883,3 +1883,26 @@ const QString Application::javaPath()
...
+            return true;
+        }
+    }
+    return false;
```
Comment (TheKodeToad) [inline launcher/Application.cpp:1907]:
```suggestion
    path = FS::AbsolutePath(path);

    QMutexLocker locker(&m_qsaveResourcesMutex);
    for (auto r : m_qsaveResources) {
        if (path.startsWith(r)) {
            return true;
        }
    }
    return false;
```

File: launcher/PSaveFile.h [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+ *
+ * Note: Please do not use the `setFileName` function directly, as it
+ * is not virtual and cannot be overridden.
+ */
+class PSaveFile : public QSaveFile {
+   public:
+    PSaveFile(const QString& name) : QSaveFile(name)
+    {
+        if (auto app = APPLICATION_DYN) {
+            app->addQSavePath(name + ".");
```
Comment (TheKodeToad) [inline launcher/PSaveFile.h:52]:
```suggestion
            app->addQSavePath(FS::absolutePath(name) + ".");
```

File: launcher/PSaveFile.h [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+        }
+    }
+    PSaveFile(const QString& name, QObject* parent) : QSaveFile(name, parent)
+    {
+        if (auto app = APPLICATION_DYN) {
+            app->addQSavePath(name + ".");
```
Comment (TheKodeToad) [inline launcher/PSaveFile.h:58]:
```suggestion
            app->addQSavePath(FS::absolutePath(name) + ".");
```

File: launcher/PSaveFile.h [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+        }
+    }
+    virtual ~PSaveFile()
+    {
+        if (auto app = APPLICATION_DYN) {
+            app->removeQSavePath(fileName() + ".");
```
Comment (TheKodeToad) [inline launcher/PSaveFile.h:64]:
```suggestion
            app->removeQSavePath(FS::absolutePath(fileName()) + ".");
```

**Review by TheKodeToad — COMMENTED** [review]
~~I feel like this would work~~ Made a mistake: FS::AbsolutePath returns the path of the parent

**Comment by TheKodeToad** [comment]
New suggestion: QFileInfo info(path); path.canonicalPath() + '/' + path.fileName() should give a consistent representation allowing you to match the file with startsWith

**Comment by TheKodeToad** [comment]
The problem with this implementation is if there are two files being downloaded with the same name but different parents they will be considered the same...
Also, if a filename is added to the list twice, it will be removed on the first destruct meaning the folder load tasks will see both files as available

It's just not very robust...

**Comment by Trial97** [comment]
> The problem with this implementation is if there are two files being downloaded with the same name but different parents they will be considered the same...

The only way that can happen is if two mods/shaders have different names but share the same file(we do not add multiple resources with the same name in the same ResourceDownloadDialog.
But I can switch the QSet<QString> with a QHash<QString,int> and increment the value at add and decrement on remove

**Comment by TheKodeToad** [comment]
> The only way that can happen is if two mods/shaders have different names but share the same file(we do not add multiple resources with the same name in the same ResourceDownloadDialog. But I can switch the QSet with a QHash<QString,int> and increment the value at add and decrement on remove

It won't be much of an issue for now, but more issues could arise if we allow resources to be downloaded in multiple instances (I assume https://github.com/PrismLauncher/PrismLauncher/pull/2598 will do this). A reference counter is at least an improvement, but I wonder if we could just suppress this error instead of it bringing down the whole application

**Comment by TheKodeToad** [comment]
Or maybe just have a file extension whitelist for parsing

**Comment by Trial97** [comment]
> It won't be much of an issue for now, but more issues could arise if we allow resources to be downloaded in multiple instances (I assume #2598 will do this). A reference counter is at least an improvement, but I wonder if we could just suppress this error instead of it bringing down the whole application

Not really the issue happens when you have the resource view open. Hopefully, we code the task manager in such way that we not allow users to open instance edit windows if the instance is not ready. And if you do update mods in  multiple instances at the same time this will not be affected as we use the full path now (including the instance path)




> Or maybe just have a file extension whitelist for parsing

Well I don't know any standards for that.

**Comment by TheKodeToad** [comment]
sorry, realised after I posted. Anything wrong with using canonicalPath() to prevent collisions?

> Well I don't know any standards for that.

The standard file extensions for files we support:
Mods = .zip (idk why but we show in add dialog), .jar, .litemod, .nilmod
Resource packs = .zip, folder with no extension
Shader packs = .zip, folder with no extension

We could also check for XXXXXX but it would match mrpack

**Comment by TheKodeToad** [comment]
Oh I see you did make a change. Still, question still applies. canonicalPath removes .. and . so it seems like a good idea to use it, also maybe instead of in the constructor in addQSavePath, removeQSavePath and checkQSavePath to ensure it is always resolved

**Comment by Trial97** [comment]
> Anything wrong with using canonicalPath() to prevent collisions?

We are not dealing with symlinks here so an absolute path should suffice (this is for the pesky temporary files that are generated when downloading/modifying resources)

> We could also check for XXXXXX but it would match mrpack

this only applies to resources that we try to read concurrently based on dir change (mrpack is not included in those)
I think we can check for that prefix with a regex: but because the lack of doc on how that part is generated, I'm not comfortable doing it(feel free to open another PR). 



> also maybe instead of in the constructor in addQSavePath, removeQSavePath and checkQSavePath to ensure it is always resolved

the PSaveFile should not be separated from the mentioned functions: do not call add/remove QSavePath outside the PSaveFile. check function on other had I already have the absolute path where is called so no need for that.

**Review by TheKodeToad — APPROVED** [review]

**Comment by TheKodeToad** [comment]
We should probably have tested again with my suggested changes

**Comment by Trial97** [comment]
Merge now, then prepare a testing phase only for windows users where they can test it out :)
