### PR TITLE
Fixes for task abort logic

### LINKED ISSUE #5397: Launcher freeze when try "abort" on mod download part of instance...
### Operating System

Nobara Linux

### Version of Prism Launcher

Prism launcher 11.02 qt portable NOT aarch64 and tested on appimage and flathub version SAME trouble.

### Version of Qt

qt 6

### Description of bug

The log ends abruptly after Will try to download QUrl. No abortion signals or cleanup logs follow, confirming a total freeze of the main thread during the network task

https://github.com/user-attachments/assets/d7222213-1e02-4067-bd27-2cbd62965323

### Steps to reproduce

just start download modpack and at part "Will try download Qurll" abort mod downloading

### Suspected cause

POSSIBLE Deadlock in GUI thread during network abort
The line "39.355 Debug: [launcher.task.net.metacache.http] Saving metacache with 15 entries (unknown:0)" appears only after a long delay (approx. 15-20 seconds if NOT longer) after clicking Abort. During this time, the entire UI is completely frozen. It looks like the main thread is waiting for a network timeout instead of terminating the task immediately
Even after waiting for 5+- minutes after the Saving metacache entry, the launcher remains completely unresponsive and no further log entries are generated. It's a permanent hang, not a temporary delay
### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by 0x189D7997**
Fixes #5397.

There are two underlying issues fixed here:

1. The freeze itself is caused by `abort()` method in `InstanceCreationTask` not calling its super. The task is never aborted and hangs indefinitely. https://github.com/PrismLauncher/PrismLauncher/blob/f40cbf816e1c594584587a981d29971692e615ab/launcher/InstanceCreationTask.cpp#L21
2. While searching for the cause I discovered another related bug: when tasks containing other subtasks are aborted, they do not check if the subtasks are still running and often they are not, causing a crash via assertion on `Debug` build and undesired/undefined behavior on `Release` builds. Example: https://github.com/PrismLauncher/PrismLauncher/blob/f40cbf816e1c594584587a981d29971692e615ab/launcher/modplatform/flame/FlameInstanceCreationTask.cpp#L85

I decided to fix this in by making the `Task` itself call `emitAborted()` only if it is still running. There should be no reason to invoke on-aborted callbacks if the task has already succeeded or failed.
Similar fix to `NetJob` because it overrides logic from `Task`. Similar to how it was already done in `ConcurrentTask`. 
The alternative of fixing this individually in all the `abort()` overrides does not seem practical to me, I have found too much occurrences (30 - 50?).

I need advice on what to do with `Task::State::Inactive`. Not sure how it is actually used and what is the correct behavior should be when `abort()` is called on a task in this state (can it happen anywhere in the existing code?).

### CODE REVIEW

File: launcher/tasks/Task.h [hunk 1]
```diff
@@ -165,7 +165,7 @@ class Task : public QObject, public QRunnable {
     //! used by external code to ask the task to abort
     virtual bool abort()
     {
-        if (canAbort())
+        if (canAbort() && isRunning())
```
Comment (Octol1ttle) [inline launcher/tasks/Task.h:168]: move `isRunning()` to `canAbort()`?

Comment (0x189D7997) [reply launcher/tasks/Task.h:168]: Would mess with the return value.
Currently `true` is returned if the task already finished running but could have been aborted otherwise.
Or am I wrong about this being the correct behavior?

Comment (0x189D7997) [reply launcher/tasks/Task.h:168]: Cannot do this anyway because too many classes override `canAbort()`, mostly with `true`.

**Review by Trial97 — APPROVED** [review]

**Review by Ryex — APPROVED** [review]
