### PR TITLE
fix: crash when the instance window is closed before download dialog is open

### LINKED ISSUE #3604: Clicking download mods then closing the instance screen before the mod download window shows up causes the Launcher to crash
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.3

### Version of Qt

Qt 6.8.1

### Description of bug

When you close the instance screen after clicking "Download Mod" button but before the download mod screen shows up, the Launcher itself freezes then crashes.
 
* Expected behaviour: Nothing happens. The Download Mod screen simply doesn't show up because the instance screen has been closed.
* Actual behaviour: The launcher freezes and crashes.

The Event Log says the exception code to be `0xc0000374` with offset `0x00000000000ff3c9`. The module was `ntdll.dll`. All three tests was logged in the Event Log to be the same error.

### Steps to reproduce

* Open the instance screen of any given instance.
* Switch to the mods tab.
* Click "Download Mod", then immediately close the instance screen before the mod download window shows up.
* -> × Launcher crashes.

### Suspected cause

_No response_

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #3604

so based on the issue description:
- try to download mods
- before the mods download dialog is open close the instance window
- it will crash because of double deletion

No I was unable to reproduce it(the dialog is always instant) but by changing the code(adding ` QTimer::singleShot(5000, nullptr, [this]() { static_cast<InstanceWindow*>(parent()->parent())->close(); });` before creating the resource download dialog did the trick).
Double deletion happens because, first, the dialog is on stack(not a pointer), and we pass the parent dialog.
It is deleted by parent closing and then because the function code arrives at the end.

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

File: launcher/ui/widgets/ModFilterWidget.cpp [hunk 1]
```diff
@@ -321,7 +320,8 @@ void ModFilterWidget::setCategories(const QList<ModPlatform::Category>& categori
 {
     m_categories = categories;
 
-    delete ui->categoryGroup->layout();
+    if (ui->categoryGroup->layout())
+        delete ui->categoryGroup->layout();
```
Comment (TheKodeToad) [inline launcher/ui/widgets/ModFilterWidget.cpp]: Redundant change? Deleting a nullptr should just do... nothing

Comment (Trial97) [reply launcher/ui/widgets/ModFilterWidget.cpp]: Removed it. still strange that that delete line was mentioned in the crash log provided in the issue.
I hope the crash was only because of the double deletion of the dialog.

**Review by TheKodeToad — APPROVED** [review]
