### PR TITLE
Preserve file extension of instance icon when importing

### LINKED ISSUE #535: Imported pack icons do not have file extensions
### Operating System

Windows

### Version of Prism Launcher

5.2

### Version of Qt

6.4.0

### Description of bug

Icons downloaded when selecting a pack from a different site/launcher in the import menu have no file extension, and while they work fine in the launcher, they appear as blank "File" type files in Windows Explorer.

image

This can be remedied manually by adding an extension such as .png at the end via a rename, at which point they will function correctly in Windows Explorer and other programs too.

### Steps to reproduce

1. Go to the pack import menu
2. Go to Curseforge, ATLauncher, FTB, FTB Legacy, Modrinth, or Technic sections, and select a pack
3. Either click the pack icon selector do download the icon, or install the pack to download the icon
4. The icon will show up without a file type in the Icons folder

### Suspected cause

Presumably PrismLauncher just downloads the icon and saves it without giving it an actual extension, not sure why.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #535

### CODE REVIEW

File: launcher/icons/IconList.cpp [hunk 1]
```diff
@@ -258,8 +259,7 @@ Qt::ItemFlags IconList::flags(const QModelIndex& index) const
     Qt::ItemFlags defaultFlags = QAbstractListModel::flags(index);
     if (index.isValid())
         return Qt::ItemIsDropEnabled | defaultFlags;
```
Comment (TheKodeToad) [inline launcher/icons/IconList.cpp]: Doesn't even seem necessary

File: launcher/ui/dialogs/NewInstanceDialog.cpp [hunk 2]
```diff
@@ -284,28 +284,27 @@ QString NewInstanceDialog::iconKey() const
...
     updateDialogState();
 }
 
 void NewInstanceDialog::importIconNow()
 {
-    if(importIcon) {
+    if (importIcon) {
         APPLICATION->icons()->installIcon(importIconPath, importIconName);
-        InstIconKey = importIconName;
+        InstIconKey = importIconName.section('.', 0, 0);
```
Comment (TheKodeToad) [inline launcher/ui/dialogs/NewInstanceDialog.cpp]:
```suggestion
        InstIconKey = importIconName.mid(0, importIconName.lastIndexOf('.');
```

This differs in behaviour from `QFileInfo::completeBaseName` - therefore will break on `my.icon.png`. seems this is only used for modpacks though so maybe not an issue

**Review by TheKodeToad — APPROVED** [review]

File: launcher/ui/dialogs/NewInstanceDialog.cpp (hunk 2 above)
Comment (Trial97) [reply launcher/ui/dialogs/NewInstanceDialog.cpp]: `importIconName.section('.', 0, 0);`  was used previously on all the modpack icons so I don't tink It will break anything regardless

File: launcher/icons/IconList.cpp (hunk 1 above)
Comment (Trial97) [reply launcher/icons/IconList.cpp]: Most of that code is formatted only (the single change, in this case, was removing the else word).
I do not know what this is and what may impact so I prefer to leave it as it is now

Comment (TheKodeToad) [reply launcher/icons/IconList.cpp]: the `if` and `else` is the same which I thought would be something else nice to clean up

Comment (Trial97) [reply launcher/icons/IconList.cpp]: fair

**Review by Scrumplex — APPROVED** [review]
