### PR TITLE
Delete associated shortcuts when deleting instance

### LINKED ISSUE #3148: Automatic deletion of shortcuts when deleting instances
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.7.3

### Description of bug

After deleting the instance from the launcher, its created shortcuts remain in the Launchpad. Since it does not have an x (cross) button attached, it cannot be directly deleted from the Launchpad.
To delete these shortcuts, users will need to know to manually delete them in `~/Applications`, which is not a common folder for regular users to search.

Personally, I think the correct way is probably to delete the shortcut when you delete the instance. Alternatively, adding the x (cross) button to the Launchpad icon would be a welcome additional feature to enable convenient deletion, but I don't know if this is even possible for non-App Store-installed icons.

System: macOS aarch64 15.1.1

### Steps to reproduce

1. Create a Minecraft instance in the launcher
2. Click "Create Shortcut" on the instance
3. Delete the instance within the launcher
4. The shortcut still exists in the Launchpad

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Mick235711**
Implement the other half of #3767: delete the instance's shortcuts when deleting the instance itself.
The deletion dialogue mentioned in https://github.com/PrismLauncher/PrismLauncher/pull/2966#issuecomment-2509813997 is not implemented for now, as I don't think there is a huge demand for looking at all shortcuts for an instance and select some for deletion. If there is demand for that, I can implement this too.

Strategies:
- Try trashing the shortcuts first; if trashing is not successful, directly try to delete them
- Register shortcut for an instance on creation; modified `FS::createShortcut` to return the shortcut location (which may have `.app`/`.lnk` appended) instead of bool.
- Store shortcut list for an instance in the settings object, and restore them on loading appropriately (remove the link if the shortcut path does not exist)

Known issues:
- If the shortcut itself is deleted, and another unrelated folder is renamed to be the same name as the shortcut, it will be associated as a shortcut on reload/launch instead, which may cause unrelated folder to be trashed/deleted. However, we cannot do anything about that.
  - Technically one can imagine validating the shortcut by looking into the bash script and extract the parameter; however that is too hard for Windows I think.

Fixes #3148.

### CODE REVIEW

File: launcher/BaseInstance.cpp [hunk 1]
```diff
@@ -69,6 +69,7 @@ BaseInstance::BaseInstance(SettingsObjectPtr globalSettings, SettingsObjectPtr s
     m_settings->registerSetting("lastTimePlayed", 0);
 
     m_settings->registerSetting("linkedInstances", "[]");
+    m_settings->registerSetting("shortcuts", QVariant::fromValue(QList<ShortcutData>{}));
```
Comment (Trial97) [inline launcher/BaseInstance.cpp]: Iwould suggest to json encode any settings that is more complex than basic types

File: launcher/FileSystem.cpp [hunk 2]
```diff
@@ -976,7 +976,7 @@ bool createShortcut(QString destination, QString target, QStringList args, QStri
                   "</dict>\n"
                   "</plist>";
 
-    return true;
+    return application.path();
```
Comment (Trial97) [inline launcher/FileSystem.cpp:979]: this doesn't loook like the path to the destination shortcut

Comment (Mick235711) [reply launcher/FileSystem.cpp:979]: It is the path to `.app` folder, which IMO is what we want to trash

File: launcher/InstanceList.cpp [hunk 3]
```diff
@@ -348,26 +349,43 @@ bool InstanceList::trashInstance(const InstanceId& id)
...
+            if (!FS::deletePath(filePath)) {
+                qWarning() << "Deletion of shortcut" << name << "at path" << filePath << "for instance" << id
+                           << "has not been successful, given up...";
+            } else {
+                qDebug() << "Shortcut" << name << "at path" << filePath << "for instance" << id << "has been deleted by the launcher.";
+            }
+            continue;
+        }
+        qDebug() << "Shortcut" << name << "at path" << filePath << "for instance" << id << "has been trashed by the launcher.";
+        m_trashHistory.top().shortcuts.append({ { name, filePath, target }, trashedLoc });
```
Comment (Trial97) [inline launcher/InstanceList.cpp:373]: do we remove somewhere the shortcuts from the settings?

Comment (Mick235711) [reply launcher/InstanceList.cpp:373]: No, but to reach this point the instance should have been trashed successfully, so it doesn't really matter. If the instance is later put back, the reload logic will prune any shortcut path that no longer exist

File: launcher/minecraft/MinecraftInstance.cpp [hunk 4]
```diff
@@ -1040,6 +1040,10 @@ QString MinecraftInstance::getStatusbarDescription()
                     .arg(Time::prettifyDuration(totalTimePlayed(), APPLICATION->settings()->get("ShowGameTimeWithoutDays").toBool())));
         }
     }
+    auto currentShortcuts = shortcuts();
+    if (!currentShortcuts.isEmpty()) {
+        description.append(tr(", %n shortcut(s) registered", "", currentShortcuts.size()));
```
Comment (Trial97) [inline launcher/minecraft/MinecraftInstance.cpp]: This may seem usefull but the overload of info on this line is exceeding

**Review by Trial97 — COMMENTED** [review]
What do you think about the moved shortcuts? This would be impossible to track each shortcut moved by the user. Should we announce the user when creating the shortcut?

File: launcher/BaseInstance.cpp (hunk 1 above)
Comment (Mick235711) [reply launcher/BaseInstance.cpp]: Sure

File: launcher/minecraft/MinecraftInstance.cpp (hunk 4 above)
Comment (Mick235711) [reply launcher/minecraft/MinecraftInstance.cpp]: Yeah, after thinking about this more I think it is more appropriate to add this to the deletion confirmation screen instead

**Comment by Mick235711** [comment]
> What do you think about the moved shortcuts? This would be impossible to track each shortcut moved by the user. Should we announce the user when creating the shortcut?

Sure, I added a note in the creation screen to announce this
CleanShot 2025-06-01 at 16 33 12@2x

File: launcher/FileSystem.cpp [hunk 5]
```diff
@@ -1002,32 +1002,32 @@ bool createShortcut(QString destination, QString target, QStringList args, QStri
...
 
-    return true;
+    return destination;
 #elif defined(Q_OS_WIN)
     QFileInfo targetInfo(target);
 
     if (!targetInfo.exists()) {
         qWarning() << "Target file does not exist!";
-        return false;
+        return "";
```
Comment (TheKodeToad) [inline launcher/FileSystem.cpp]: It would be better to represent an error with QString() - which creates a null string where isNull is true
isEmpty is also true on a null string, so you can just keep that the same - however I still feel a null string makes the intent clearer

Comment (Mick235711) [reply launcher/FileSystem.cpp]: Ah, that's a neat piece of info I didn't know. Thanks for the suggestion!

File: launcher/InstanceList.cpp [hunk 6]
```diff
@@ -377,21 +395,41 @@ void InstanceList::undoTrashInstance()
         top.path += "1";
     }
 
+    if (!QFile(top.trashPath).rename(top.path)) {
+        qWarning() << "Moving" << top.trashPath << "back to" << top.path << "failed!";
+        return false;
+    }
```
Comment (TheKodeToad) [inline launcher/InstanceList.cpp:401]: Shouldn't this be below the log message?

Comment (Mick235711) [reply launcher/InstanceList.cpp:401]: Well, in most cases I tend to first do the action and then log, and also when wrote this way, it can just return early without needing an else.

**Review by TheKodeToad — APPROVED** [review]

File: launcher/BaseInstance.cpp [hunk 7]
```diff
@@ -69,6 +69,7 @@ BaseInstance::BaseInstance(SettingsObjectPtr globalSettings, SettingsObjectPtr s
     m_settings->registerSetting("lastTimePlayed", 0);
 
     m_settings->registerSetting("linkedInstances", "[]");
+    m_settings->registerSetting("shortcuts", QVariant::fromValue(QByteArray{}));
```
Comment (Trial97) [inline launcher/BaseInstance.cpp]: this should be a string

File: launcher/BaseInstance.cpp [hunk 8]
```diff
@@ -398,6 +399,39 @@ bool BaseInstance::syncInstanceDirName(const QString& newRoot) const
...
+{
+    // FIXME: if no change, do not set. setting involves saving a file.
+    QJsonArray array;
+    for (const auto& elem : shortcuts) {
+        array.append(QJsonObject{ { "name", elem.name }, { "filePath", elem.filePath }, { "target", static_cast<int>(elem.target) } });
+    }
+
+    QJsonDocument document;
+    document.setArray(array);
+    m_settings->set("shortcuts", QVariant::fromValue(document.toJson(QJsonDocument::Compact)));
```
Comment (Trial97) [inline launcher/BaseInstance.cpp]: Wrap in QString::fromUtf8(

File: launcher/BaseInstance.cpp [hunk 9]
```diff
@@ -398,6 +399,39 @@ bool BaseInstance::syncInstanceDirName(const QString& newRoot) const
...
+}
+
+QList<ShortcutData> BaseInstance::shortcuts() const
+{
+    auto data = m_settings->get("shortcuts").value<QByteArray>();
```
Comment (Trial97) [inline launcher/BaseInstance.cpp]: is get().toString().toUtf8()

**Review by Trial97 — COMMENTED** [review]
One last thing I want to avoid storing QBytearray in the config: I'm trying to migrate from the current QBytearray to QString in order to have a more correct ini file and making the decoding/encoding based on weird qt prefixes

**Comment by Mick235711** [comment]
> One last thing I want to avoid storing QBytearray in the config: I'm trying to migrate from the current QBytearray to QString in order to have a more correct ini file and making the decoding/encoding based on weird qt prefixes

Sure, now fixed as suggested.

**Review by Trial97 — APPROVED** [review]
Not sure if this correctly handles the incorrect JSON setting value (aka if fore some reason the setting is an invalid json value in the ini file)

**Review by Ryex — APPROVED** [review]

**Comment by Mick235711** [comment]
> Not sure if this correctly handles the incorrect JSON setting value (aka if fore some reason the setting is an invalid json value in the ini file)

I added some checks for that; if the format is invalid, then just returns no shortcut, and if the path does not exist just excludes this entry from the resulting list. Hope this suffices...

File: launcher/BaseInstance.cpp [hunk 10]
```diff
@@ -398,6 +399,51 @@ bool BaseInstance::syncInstanceDirName(const QString& newRoot) const
...
+
+    QJsonDocument document;
+    document.setArray(array);
+    m_settings->set("shortcuts", QString::fromUtf8(document.toJson(QJsonDocument::Compact)));
+}
+
+QList<ShortcutData> BaseInstance::shortcuts() const
+{
+    auto data = m_settings->get("shortcuts").toString().toUtf8();
+    auto document = QJsonDocument::fromJson(data);
```
Comment (Trial97) [inline launcher/BaseInstance.cpp]: This can trow exeption if not valid json

File: launcher/BaseInstance.cpp [hunk 11]
```diff
@@ -398,6 +399,51 @@ bool BaseInstance::syncInstanceDirName(const QString& newRoot) const
...
+    QList<ShortcutData> results;
+    for (const auto& elem : document.array()) {
```
Comment (Trial97) [inline launcher/BaseInstance.cpp:432]: What happens when doccument is not an array?

File: launcher/BaseInstance.cpp [hunk 12]
```diff
@@ -398,6 +399,51 @@ bool BaseInstance::syncInstanceDirName(const QString& newRoot) const
...
+        auto dict = elem.toObject();
```
Comment (Trial97) [inline launcher/BaseInstance.cpp:435]: Same here What happens when the elem is not object

File: launcher/BaseInstance.cpp [hunk 13]
```diff
@@ -398,6 +399,51 @@ bool BaseInstance::syncInstanceDirName(const QString& newRoot) const
...
+        if (!dict.contains("name") || !dict.contains("filePath") || !dict.contains("target"))
+            return {};
```
Comment (Trial97) [inline launcher/BaseInstance.cpp]: I would not return here; but just continue parsing the json

File: launcher/BaseInstance.cpp [hunk 14]
```diff
@@ -398,6 +399,51 @@ bool BaseInstance::syncInstanceDirName(const QString& newRoot) const
...
+        int value = dict["target"].toInt(-1);
+        if (!dict["name"].isString() || !dict["filePath"].isString() || value < 0 || value >= 3)
```
Comment (Trial97) [inline launcher/BaseInstance.cpp:439]: same here

File: launcher/BaseInstance.cpp (hunk 10 above)
Comment (Trial97) [reply launcher/BaseInstance.cpp]:
```    QJsonParseError parseError;
    QJsonDocument doc = QJsonDocument::fromJson(jsonString.toUtf8(), &parseError);

    if (parseError.error != QJsonParseError::NoError || !doc.isObject())
        return {};```

**Review by Trial97 — COMMENTED** [review]
We have a Json.h header that implements some basic json functions, like ensurejsonstring/ensurejsonobject/ensurejsonarray

File: launcher/BaseInstance.cpp (hunk 11 above)
Comment (Mick235711) [reply launcher/BaseInstance.cpp:432]: `array()` will return an empty array in that case, which cause the function to return an empty list

File: launcher/BaseInstance.cpp (hunk 12 above)
Comment (Mick235711) [reply launcher/BaseInstance.cpp:435]: `QJsonValue::toObject` will return an default-constructed `QJsonObject` if the elem is not object, which cause the contain check to fail and an empty list to be returned.

File: launcher/BaseInstance.cpp (hunk 13 above)
Comment (Mick235711) [reply launcher/BaseInstance.cpp]: Sure, if that's what you want, I will implement that.

**Comment by Mick235711** [comment]
> We have a Json.h header that implements some basic json functions, like ensurejsonstring/ensurejsonobject/ensurejsonarray

I looked into that, however, it reports errors by throwing exceptions... do we really want to use exceptions as control flow here?

**Review by Trial97 — APPROVED** [review]
The ensure function should not throw but return the default value in case of any error.
But it is not needed, this looks ok.(just fix the build error)

**Comment by Mick235711** [comment]
Forgot to run format before push... build should be ok now.
