### PR TITLE
Use static image when opengl context is not available

### LINKED ISSUE #4498: Crash on manage skins when OpenGL is not present
### Operating System

Linux

### Version of Prism Launcher

10.0.0-pre1

### Version of Qt

6.9.3

### Description of bug

```
     7.804 D: Started watching  "/home/fabien/.local/share/PrismLauncher/skins" (unknown:0)
     7.815 W: [qt.glx] qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile) (unknown:0)
     7.828 W: [qt.glx] qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile) (unknown:0)
     7.829 W: [qt.glx] qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile) (unknown:0)
     7.843 F: Could not initialize GLX (unknown:0)
fish: Job 1, ''/home/fabien/Applications/Pris…' terminated by signal SIGABRT (Abort)
```

### Steps to reproduce

Settings -> MS Account -> Manage Skins...

### Suspected cause

Library issue?

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes crash on appimage where the opengl context is not available 
fixes #4498

### CODE REVIEW

**Comment by Ryex** [comment]
is the `qnamespace.h` intentional?

**Comment by Trial97** [comment]
Nope

File: launcher/ui/dialogs/skins/SkinManageDialog.cpp [hunk 1]
```diff
@@ -21,6 +21,7 @@
 #include "ui_SkinManageDialog.h"
 
 #include <FileSystem.h>
+#include <qnamespace.h>
```
Comment (Trial97) [inline launcher/ui/dialogs/skins/SkinManageDialog.cpp]:
```suggestion
```

**Review by Ryex — APPROVED** [review]

**Review by DioEgizio — APPROVED** [review]
