### PR TITLE
Fix a crash that could happen installing an ATLauncher modpack

### LINKED ISSUE #3866: launcher crash when importing atlauncher modpack
### Operating System

Windows

### Version of Prism Launcher

develop 573aa8c208d915fb44eb99019945d481fce3f90c (also happens on 9.3, 9.4)

### Version of Qt

6.9.0

### Description of bug

importing a Moonquest modpack from atlauncher causes prism to crash
originally reported on discord https://discord.com/channels/1031648380885147709/1382109274032832723

### Steps to reproduce

- go to add instance > atlauncher
- try to import Moonquest 
- click through it
- get crash

### Suspected cause

[gdbcrash.log](https://github.com/user-attachments/files/20680560/gdbcrash.log)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #3866 

right now this only checks for prefix mc version
so [this](https://mvnrepository.com/artifact/net.minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9) would still fail not sure how and why this happens with forge versions
related to https://github.com/PrismLauncher/PrismLauncher/issues/3799

### CODE REVIEW

File: launcher/minecraft/PackProfile.cpp [hunk 1]
```diff
@@ -958,16 +958,39 @@ std::shared_ptr<LaunchProfile> PackProfile::getProfile() const
...
 bool PackProfile::setComponentVersion(const QString& uid, const QString& version, bool important)
 {
     auto iter = d->componentIndex.find(uid);
+    auto _version = version;
+    if (uid == "net.minecraftforge" && isWeirdForgeFormat(version)) {
+        int dashIndex = version.indexOf('-');
+        if (dashIndex != -1 && dashIndex + 1 < version.length()) {
+            _version = version.mid(dashIndex + 1);
+        }
+    }
```
Comment (TheKodeToad) [inline launcher/minecraft/PackProfile.cpp]: I don't think we should include loader specific workarounds in PackProfile - it seems a little too hacky

Comment (Trial97) [reply launcher/minecraft/PackProfile.cpp]: Then where should I add this hack? Or should I just fallback to latest version in cases where the version is not found in our meta

Comment (TheKodeToad) [reply launcher/minecraft/PackProfile.cpp]: It'd be better to put it inside the modpack install tasks - and mimic the behaviour of Modrinth App for mrpack; CurseForge app for CurseForge pack; ATLauncher for ATLauncher pack etc.

I think if a modpack states its version like this it's usually the modpacks fault as Modrinth app will not export with version prefixed/suffixed versions

I've not investigated ATLauncher or CurseForge, but if either of them export versions like this implement this workaround for them - there are ways you could still deduplicate this code

If we want to follow a more "liberal with what you accept, conservative with what you send" approach I'd still consider this bad practice

**Review by Ryex — APPROVED** [review]

File: launcher/minecraft/PackProfile.cpp (hunk 1 above)
Comment (Ryex) [reply launcher/minecraft/PackProfile.cpp]: personally I'm not opposed to this kind of monkey patching. sometimes it is necessary and effective. we should ideally be liberal in what we accept in cases where old / oddly formated packs work in other launchers they should work in ours.

however I'm not such a fan just injecting the patch here. don't we do similar component based checks in this stage? any way we could pull them out into a ComponentPatch class and register thouse patches to run for component names?

**Review by Ryex — CHANGES_REQUESTED** [review]
not a fan of the patch being injected in the add component method

File: launcher/minecraft/PackProfile.cpp (hunk 1 above)
Comment (TheKodeToad) [reply launcher/minecraft/PackProfile.cpp]: > however I'm not such a fan just injecting the patch here. don't we do similar component based checks in this stage? any way we could pull them out into a ComponentPatch class and register thouse patches to run for component names?

I don't think this makes a lot of sense - I think this is a modpack format thing - I imagine some modpack formats support this version notation and others don't.

Our modpack installation tasks already generally has the responsibility of parsing the version anyway. So I think we should stick to that.

Comment (Trial97) [reply launcher/minecraft/PackProfile.cpp]: Wouldn't it be better if instead of patching the version, have in packprofile(or on imports) a way to say Hey we couldn't find the version you are looking so we are gonna use the latest/recommended version from the meta.
I would go in to add that in packprofile so the user would see: yeah, the version errored(but it still launches) instead of why does my instance import uses this version instead of the one mentioned in the import.

**Comment by TheKodeToad** [comment]
FWIW Modrinth app does not support `1.8.9-11.15.1.2318-1.8.9` (example given on Discord)
image

Neither does CurseForge
image

I personally don't think there's any reason to apply this globally

**Comment by TheKodeToad** [comment]
The reason the pack works in ATLauncher is because the pack itself embeds the Forge JAR.
If we applied this workaround we would be doing something no other launcher does - just about every other launcher only allows the Forge version number in the standard format
(Modrinth, CurseForge, MultiMC, ATLauncher, FTB)

**Comment by TheKodeToad** [comment]
Wait, never mind. ATLauncher does support this format, even if it's not like this modpack where it seemingly works because Forge is actually a jarmod instead of a loader. Even in CurseForge packs.

But my conclusion would be the same: if we do any workaround it should be ATLauncher specific

**Comment by Trial97** [comment]
I know that both CF and Modrinth do not support this kind of format and I will move the patching in atlauncher, but should we add a protection for CF and Modrinth in case this happens, like in the issue #3799 where the exported zip contains an invalid loader version(and in that case use the latest version and announce the user about it)?

**Comment by TheKodeToad** [comment]
Sure, but that's another issue

**Review by Ryex — APPROVED** [review]

File: launcher/meta/Index.cpp [hunk 2]
```diff
@@ -159,4 +159,79 @@ Version::Ptr Index::getLoadedVersion(const QString& uid, const QString& version)
...
+        return false;  // No dash or nothing after dash - considered valid
+
+    QChar nextChar = input[dashIndex + 1];
+    if (nextChar.isLetter()) {
+        return false;  // Immediate letter after dash
+    }
+
+    QString afterDash = input.mid(dashIndex + 1);
+    return afterDash.contains('.');  // Dot found after dash so most probably it is
+}
```
Comment (TheKodeToad) [inline launcher/meta/Index.cpp]: This handling should be ATLauncher-specific as no other format is likely to have it 
Since you're just using this to obtain the Minecraft version can't you just use mcVersion?

Comment (Trial97) [reply launcher/meta/Index.cpp]: The artifact is present in the forge Maven repo: https://mvnrepository.com/artifact/net.minecraftforge/forge/1.12.2-14.23.5.2847 (one example)
So I will presume that the other formats can still have it

Comment (TheKodeToad) [reply launcher/meta/Index.cpp]: I edited message
> Since you're just using this to obtain the Minecraft version can't you just use mcVersion?

Comment (Trial97) [reply launcher/meta/Index.cpp]: I'm using it to find the forge version

Comment (TheKodeToad) [reply launcher/meta/Index.cpp]: Still not really sure about it as ideally our meta handling code should not be intertwined with loader specific stuff...

Comment (Trial97) [reply launcher/meta/Index.cpp]: I can remove this version patch from here, and it should use the recommended version instead of the intended version. Are you okay with that?

Comment (TheKodeToad) [reply launcher/meta/Index.cpp]: >  So I will presume that the other formats can still have it

Evidence suggests otherwise.

I think it would at least be a little better if we split it off but we also have handling specific to neo/forge there :(

Comment (Trial97) [reply launcher/meta/Index.cpp]: Done removed that weird handling: now instead of searching a specific version that may not be there, it will always use the recommended version if the format return a loader that is not in our meta

File: launcher/meta/Index.cpp [hunk 3]
```diff
@@ -159,4 +159,53 @@ Version::Ptr Index::getLoadedVersion(const QString& uid, const QString& version)
...
+    auto vlist = get(uid);
+    if (!vlist) {
+        err = tr("Failed to get local metadata index for %1").arg(uid);
+        return {};
+    }
+
+    vlist->waitToLoad();
+    if (loaderVersion == "choose") {
+        return loaderVersion;
+    }
```
Comment (TheKodeToad) [inline launcher/meta/Index.cpp]:
```suggestion
```

File: launcher/modplatform/atlauncher/ATLPackInstallTask.cpp [hunk 4]
```diff
@@ -337,58 +335,33 @@ QString PackInstallTask::getDirForModType(ModType type, QString raw)
...
-
-            return m_support->chooseVersion(vlist, m_version.minecraft);
-        }
+    QString loaderVersion;
+    if (m_version.loader.recommended) {
+        loaderVersion = "recommended";
+    } else if (m_version.loader.latest) {
+        loaderVersion = "latest";
+    } else if (m_version.loader.choose) {
+        loaderVersion = "choose";
```
Comment (TheKodeToad) [inline launcher/modplatform/atlauncher/ATLPackInstallTask.cpp]:
```suggestion
```

File: launcher/modplatform/atlauncher/ATLPackInstallTask.cpp [hunk 5]
```diff
@@ -337,58 +335,33 @@ QString PackInstallTask::getDirForModType(ModType type, QString raw)
...
-    return m_version.loader.version;
+    if (m_version.loader.choose) {
+        auto vlist = APPLICATION->metadataIndex()->get(uid);
+        // Fabric Loader doesn't depend on a given Minecraft version.
+        if (m_version.loader.type == "fabric" || m_version.loader.type == "quilt") {
+            return m_support->chooseVersion(vlist, Q_NULLPTR);
+        }
+
+        return m_support->chooseVersion(vlist, m_version.minecraft);
+    }
```
Comment (TheKodeToad) [inline launcher/modplatform/atlauncher/ATLPackInstallTask.cpp]: Also need to remove duplicated logic above

```suggestion
    if (m_version.loader.choose) {
        auto vlist = APPLICATION->metadataIndex()->get(uid);
        // Fabric Loader doesn't depend on a given Minecraft version.
        if (m_version.loader.type == "fabric" || m_version.loader.type == "quilt") {
            return m_support->chooseVersion(vlist, Q_NULLPTR);
        }

        return m_support->chooseVersion(vlist, m_version.minecraft);
    } else {
        QString err;
        auto version = APPLICATION->metadataIndex()->getVersionForLoader(uid, m_version.loader.type, loaderVersion, m_version.minecraft, err);
        if (!err.isEmpty()) {
            emitFailed(err);
            return Q_NULLPTR;
        }
    }
```

**Review by TheKodeToad — CHANGES_REQUESTED** [review]

File: launcher/meta/Index.cpp (hunk 3 above)
Comment (Trial97) [reply launcher/meta/Index.cpp]: needed for atlauncer stuff

File: launcher/modplatform/atlauncher/ATLPackInstallTask.cpp (hunk 4 above)
Comment (Trial97) [reply launcher/modplatform/atlauncher/ATLPackInstallTask.cpp]: Not gonna happen: some atlauncher packs(not know any) require the user to select the version of the loader

File: launcher/modplatform/atlauncher/ATLPackInstallTask.cpp (hunk 5 above)
Comment (Trial97) [reply launcher/modplatform/atlauncher/ATLPackInstallTask.cpp]: Now it makes sense to choose before the `getVersionForLoader`
It should be fixed now

**Review by TheKodeToad — APPROVED** [review]
