### PR TITLE
Fix weird utf archive

### LINKED ISSUE #5166: Pack will not download on linux
### Operating System

Linux

### Version of Prism Launcher

10.0.5

### Version of Qt

6.10.2

### Description of bug

The pack waccy's fantasia does not download on linux but works fine on windows (i tested on wine but assuming it does), prism zip exported from wine installs fine on linux so this looks like an issue specifically with the curseforge install

### Steps to reproduce

attempt to add instance > waccys fantasia from curseforge then it fails to add

### Suspected cause

something with new zip extraction library probably

https://mclo.gs/9nzx3vy here is broken linux log

https://mclo.gs/ssoj20g here is working windows (wine) log

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #5166
CF project that has this weird archive: https://www.curseforge.com/minecraft/modpacks/waccyys-fantasia

So what happens is that some entries in this archive return empty string for `archive_entry_pathname_utf8` but not for `archive_entry_pathname` because they are not marked as utf or something.

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

File: launcher/archive/ArchiveReader.cpp [hunk 1]
```diff
@@ -36,25 +36,30 @@ QStringList ArchiveReader::getFiles()
...
         return f->skip();
     });
 }
 
 QString ArchiveReader::File::filename()
 {
-    return QString::fromUtf8(archive_entry_pathname_utf8(m_entry));
+    auto fileName = QString::fromUtf8(archive_entry_pathname_utf8(m_entry));
+    if (fileName.isEmpty()) {
+        fileName = QString::fromUtf8(archive_entry_pathname(m_entry));
```
Comment (getchoo) [inline launcher/archive/ArchiveReader.cpp]: Is it actually safe to use `fromUtf8()` if the pathname isn't actually guaranteed to be UTF-8..........?
Would also probably be worth putting a comment here, as this is Weird behavior

Comment (Ryex) [reply launcher/archive/ArchiveReader.cpp]: that's actually a good point. technically by the libarchive docs `archive_entry_pathname` is supposed to follow the set locale so while this should generally work fine on unix it should probably use [`fromLocal8Bit`](https://doc.qt.io/qt-6/qstring.html#fromLocal8Bit-1)

**Review by Ryex — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]
