### PR TITLE
validate metadata on instance launch 

### LINKED ISSUE #574: Launcher doesn't refresh Version json data
### Operating System

Windows, macOS, Linux

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

5.15

### Description of bug

Previously downloaded json used in the version selector are NOT updated even with the meta repo contains new information.

For example, LWJGL3 was updated in the meta repo but since I have 3.3.1.json cached locally, it does NOT pull the latest version of that json from the meta repo.

this means that if any json file gets updated on the meta repo without a version bump (mojang sometimes does this close to release of a new version even), the user will get stuck with whatever version they have cached until they manually clear out their local metadata

this is probably the cause of this issue: https://github.com/PrismLauncher/PrismLauncher/issues/162

### Steps to reproduce

- create instance before meta repo updates an existing file
- update meta repo file
- go back to instance and see that the old json file is still present and doesn't match meta repo. reload and download all do not change anything

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
This will ensure that the metadata is always up to date.
~I did not fully test it yet but this worked on  a small subset~
This is needed as we change the meta a lot
fixes #574

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

**Comment by Trial97** [comment]
This has a flaw that will not allow users to update meta when the app is running (the index is only updated once)

**Comment by Trial97** [comment]
Hopefully I do not find any more bugs on this. 
Now the validation happens on load from file(if the hash doesn't match yet it) and to ensure that the checksums alllways match the index path until the version is refetched starting the main index going into subfolder index and then the version itself.
The main index is refetched on the first Minecraft launch or the when a version list is manually refreshed by users(and a few obscure places). 
the other meta files are not downloaded again if the file checksum matches the one from the corresponding index.json
Other stuff now the task is not started by default and all loading happens in a dedicated task instead of combining the local loading when the load function is called and the download elsewhere.

**Review by Ryex — APPROVED** [review]

**Comment by Trial97** [comment]
This still has a bug that the versions on add instance are not instantly loaded on open

File: launcher/modplatform/atlauncher/ATLPackInstallTask.cpp [hunk 1]
```diff
@@ -1075,36 +1076,13 @@ void PackInstallTask::install()
...
-        if (!task->isRunning())
-            task->start();
-
-        loadVersionLoop.exec();
-    }
+    QEventLoop ev;
+    auto task = APPLICATION->metadataIndex()->loadVersion(uid, version);
+    QObject::connect(task.get(), &Task::finished, &ev, &QEventLoop::quit);
+    task->start();
+    ev.exec();
```
Comment (Ryex) [inline launcher/modplatform/atlauncher/ATLPackInstallTask.cpp]: I've seen this particular new sequence more than three times, > 3 is the point where I usually look to factor it out to a function.

also the creation of a sub event loop this many times makes my skin itch. should we perhaps look to create a `loadVersionAsync` method that takes a callback?

**Review by Ryex — CHANGES_REQUESTED** [review]

File: launcher/modplatform/atlauncher/ATLPackInstallTask.cpp (hunk 1 above)
Comment (Trial97) [reply launcher/modplatform/atlauncher/ATLPackInstallTask.cpp]: > I've seen this particular new sequence more than three times, > 3 is the point where I usually look to factor it out to a function.

Yeah it it is present in a few places but that is because previously the versions were partially loaded in sync( the first load where we read from files), now all that logic is handled async inside the task(when it succeeds the version is fully loaded).
I will consider moving all this inside one function but sadly in the places where it's used, I can't get rid of QEventLoop as they expect an immediate answer(and that needs to be refactored a lot to make the task load async).




> also the creation of a sub event loop this many times makes my skin itch. should we perhaps look to create a `loadVersionAsync` method that takes a callback?

I prefer the signal/task approach I return a task(object) and connect to the signals. That way I can chain them if needed in another ConcurrentTask.

**Review by Ryex — APPROVED** [review]

**Comment by Trial97** [comment]
And another bug: this doesn't work offline at all

**Comment by TayouVR** [comment]
I am not really sure how to test this, do we have any pending meta changes I could get from a alt meta url? or maybe multimc meta?
Need to find a way to actually get meta to require an update/refresh...

as far as the code goes, my untrained eyes (concerning C++) can't see anything obviously wrong, so its probably alright

**Comment by Trial97** [comment]
- delete meta folder
- restart prism
- create a new vanilla instance and launch it (if it starts we are good)
- navigate inside meta folder 
- close prism if open
- open the version.json file for that instance 
- change it (you can change a checksum there or even the entire file)
- save that 
- open prism 
- start instance 
- the file should be regenerated (your previous changes are nowhere to be seen)

if you change one checksum the start instance fails on the current version: 8.4

**Comment by TayouVR** [comment]
if I intentionally fuck up some urls in 1.21.json in the meta folder, the game doesn't launch. 
If I just fuck up sha1 checksums it still launches, but it doesn't seem to touch the file again and fix anything.
Following your comment it sounds like the launcher would attempt redownloading the file from meta when needed?

**Comment by Ryex** [comment]
> if I intentionally fuck up some urls in 1.21.json in the meta folder, the game doesn't launch. If I just fuck up sha1 checksums it still launches, but it doesn't seem to touch the file again and fix anything. Following your comment it sounds like the launcher would attempt redownloading the file from meta when needed?

did you restart the launcher after your edits to the files?

**Comment by TayouVR** [comment]
I did restart the launcher.
Commit 9d903175ab77fad96281b0f29ed29cf7b6c10c16 is the correct one to build from, right?
Tried to get a build from CI first, but could fine the right run for the commit, so just built it myself.

I'm testing this on win10 with Qt6.7.1 in a portable configuration (as to not mess with my system installed launcher data (meta cache, instances))
I feel like I'm missing something here, I'll see if i can have a look at the code and understand why its not working for me tomorrow (I generally don't go through the effort of analyzing and understanding changes if they exceed a certain complexity as my C++ skills aren't great, so it would take me a really long time (which I don't have) to actually understand things)

**Comment by Trial97** [comment]
> Following your comment it sounds like the launcher would attempt redownloading the file from meta when needed?

If the file is yet to be loaded in memory, then the file sha1 is checked against the index file and if differs it should delete the file and redownload it(that's why the restart of prism is needed, to unload the file from memory)




> Commit [9d90317](https://github.com/PrismLauncher/PrismLauncher/commit/9d903175ab77fad96281b0f29ed29cf7b6c10c16) is the correct one to build from, right?

Yes, that is the last commit to this PR. 
I will also retrigger the CI build to be sure.


Strange that for you doesn't work.
Because you are on windows please make sure that you do not have the file open before you reopen Prism, as it may fail to delete it being open by another program.

**Review by DioEgizio — APPROVED** [review]

**Review by TayouVR — APPROVED** [review]
seems to work now
