### PR TITLE
Fix system icons on Linux

### LINKED ISSUE #2769: Icon theme is not respected on KDE Plasma
### Operating System

Linux

### Version of Prism Launcher

8.4

### Version of Qt

6.7.2

### Description of bug

When using `Icons: Simple (Colored)` and `Widgets: System` with Breeze style and a custom icon pack, the custom icon pack is ignored.

In my case, I use [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme), and it's ignored.

### Steps to reproduce

1. Use Papirus icon theme.
2. Go to settings and try to change the download folder by clicking on the change folder button. You will notice the icon pack is not applied.

This is also not only true for folders icon etc., but also for buttons, since icon packs can also change them.

### Suspected cause

Some kind of sandbox Prism is creating or isn't looking for the correct variables from the host system.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by leia-uwu**
This sets the fallback icon theme to the current(system default) icon theme before
launcher specific themes are applied

And removes `Inherits` line of multimc/legacy icon theme because it can end up making it
inherit a default theme set from /usr/share/icons/default/index.theme
instead of the user configured theme (probably a qt bug?)

fixes #2769

### CODE REVIEW

File: launcher/ui/themes/ThemeManager.cpp [hunk 1]
```diff
@@ -36,6 +36,7 @@
 
 ThemeManager::ThemeManager()
 {
+    QIcon::setFallbackThemeName(QIcon::themeName());
```
Comment (TheKodeToad) [inline launcher/ui/themes/ThemeManager.cpp:39]: It's probably safer to also set the fallback path and set the main path to just :/icons and PrismLauncher/iconthemes

**Review by TheKodeToad — APPROVED** [review]
Works on my machine
On GNOME it makes the icons look like the modern adwaita instead of the old one, and on KDE it makes them look like the correct breeze icons

I don't know if removing the fallback icon set is spec compliant but it's certainly a lot better :P

**Comment by TheKodeToad** [comment]
Hey wait, it's probably a good idea to test this on Windows, just in case...

**Comment by TheKodeToad** [comment]
Works just fine on Windows, fluent icon being used for instance delete. Makes sense, the fallback icons is documented only do anything on linux

**Review by TayouVR — APPROVED** [review]

**Review by Trial97 — APPROVED** [review]
