### PR TITLE
LaunchController: fix offline launches always failing

### LINKED ISSUE #4429: Launch offline/demo does not launch
### Operating System

Linux

### Version of Prism Launcher

develop

### Version of Qt

6.8.2

### Description of bug

The launch offline button shows a dialog to input the offline player name but upon pressing OK, the game does not start.

This is shown in the log
```
    34.344 D: [launcher.task] Task "LaunchController(0x512000196e40 ID: 0ae1917e-d0f5-4b5f-96ec-cd07c600e337)" starting for the first time (Task::start:80)
    35.011 C: [launcher.task] Task "LaunchController(0x512000196e40 ID: 0ae1917e-d0f5-4b5f-96ec-cd07c600e337)" failed:  "Failed to launch." (Task::emitFailed:119)
```

### Steps to reproduce

- Make sure the selected account is an online account
- Click on the triangle next to launch
- Press launch offline

### Suspected cause

_No response_

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Octol1ttle**
Closes #4429

### CODE REVIEW

**Review by DioEgizio — APPROVED** [review]

File: launcher/LaunchController.cpp [hunk 1]
```diff
@@ -148,8 +148,12 @@ bool LaunchController::askPlayDemo()
     return box.clickedButton() == demoButton;
 }
 
-QString LaunchController::askOfflineName(QString playerName, bool demo, bool& ok)
+QString LaunchController::askOfflineName(QString playerName, bool demo, bool* ok)
 {
+    if (ok) {
```
Comment (TheKodeToad) [inline launcher/LaunchController.cpp]: Nitpick: when it's a boolean pointer it's a little confusing to coerce to a boolean 
```suggestion
    if (ok != nullptr) {
```

File: launcher/LaunchController.cpp [hunk 2]
```diff
@@ -166,9 +170,12 @@ QString LaunchController::askOfflineName(QString playerName, bool demo, bool& ok
...
     }
 
-    if (const QString name = dialog.getUsername(); !name.isEmpty()) {
-        usedname = name;
-        APPLICATION->settings()->set("LastOfflinePlayerName", usedname);
+    const QString name = dialog.getUsername();
+    usedname = name;
+    APPLICATION->settings()->set("LastOfflinePlayerName", usedname);
+
+    if (ok) {
```
Comment (TheKodeToad) [inline launcher/LaunchController.cpp]:
```suggestion
    if (ok != nullptr) {
```

**Review by TheKodeToad — APPROVED** [review]

**Review by TayouVR — APPROVED** [review]

**Review by Ryex — APPROVED** [review]
