### PR TITLE
fix: segfault in progress dialog

### LINKED ISSUE #1229: Desktop shortcuts cause Segmentation Fault
### Operating System

macOS, Linux

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.0

### Description of bug

Desktop shortcuts of Minecraft Instances do not successfully start the game. Instead, they open a terminal window showing a segmentation fault error message.

### Steps to reproduce

1. Click "Add Instance", select "Vanilla", and click "OK"
2. Click "Create Shortcut"
3. Close Prism Launcher
4. Double-click the file created on the desktop

### Suspected cause

It seems related to downloading assets. This also seems specific to the `--launch` command line flag and doesn't happen when using the app manually.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Ryex**
### Breakdown
- dialog tries to resize after unhiding the sub-task scroll area
- after resize attempts to recenter on parent
  - calls `parentWidget()->{x|y}()`
  - what if there is no parent? `nullptr->()` = segfault
### Fix
- recenter on last pos, don't access parent

~~potentially~~ fixes: #1229

### CODE REVIEW

File: launcher/ui/dialogs/ProgressDialog.cpp [hunk 1]
```diff
@@ -34,6 +34,7 @@
  */
 
 #include "ProgressDialog.h"
+#include <qpoint.h>
```
Comment (Ryex) [inline launcher/ui/dialogs/ProgressDialog.cpp]:
```suggestion
#include <QPoint>
```

File: launcher/ui/dialogs/ProgressDialog.cpp [hunk 2]
```diff
@@ -96,22 +98,29 @@ ProgressDialog::~ProgressDialog()
...
+    minHeight = std::max(minHeight, 60);
+    QSize minSize = QSize(480, minHeight);
+
+    setMinimumSize(minSize);
+    adjustSize();
+
+    QSize newSize = this->size();
     // if the current window is too small
-    if ((lastSize != qSize) && (lastSize.height() < qSize.height()))
+    if ((lastSize != minSize) && (lastSize.height() < minSize.height()))
```
Comment (Ryex) [inline launcher/ui/dialogs/ProgressDialog.cpp]:
```suggestion
    if ((lastSize != minSize) && (lastSize.height() < newSize.height()))
```

File: launcher/ui/dialogs/ProgressDialog.cpp [hunk 3]
```diff
@@ -96,22 +98,29 @@ ProgressDialog::~ProgressDialog()
...
+    minHeight = std::max(minHeight, 60);
+    QSize minSize = QSize(480, minHeight);
+
+    setMinimumSize(minSize);
+    adjustSize();
+
+    QSize newSize = this->size();
     // if the current window is too small
-    if ((lastSize != qSize) && (lastSize.height() < qSize.height()))
+    if ((lastSize != minSize) && (lastSize.height() < newSize.height()))
```
Comment (Ryex) [inline launcher/ui/dialogs/ProgressDialog.cpp]:
```suggestion
    if ((lastSize != newSize) && (lastSize.height() < newSize.height()))
```

**Review by Scrumplex — APPROVED** [review]

**Review by getchoo — APPROVED** [review]
nice!
