### PR TITLE
Fix image width in project description

### LINKED ISSUE #2155: Image Width property in HTML not respected in "Download Mods" window.
### Operating System

Windows

### Version of Prism Launcher

8.0

### Version of Qt

6.6.0

### Description of bug

Some images are displayed with incorrect formatting.

### Steps to reproduce

As seen in Entity Texture Features page.
image

### Suspected cause

Not exactly sure how the images are included in the modrinth page, but on the github readme those images are html. The images display correctly on the modrinth website.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #2155

### CODE REVIEW

File: launcher/ui/widgets/VariableSizedImageObject.cpp [hunk 1]
```diff
@@ -36,6 +37,30 @@ QSizeF VariableSizedImageObject::intrinsicSize(QTextDocument* doc, int posInDocu
 
     auto image = qvariant_cast<QImage>(format.property(ImageData));
     auto size = image.size();
+    if (size.isEmpty())  // can't resize a empty image
```
Comment (StupidRepo) [inline launcher/ui/widgets/VariableSizedImageObject.cpp]:
```
// can't resize a empty image
```
should be
```
// can't resize an empty image
```
👍🏽 I know this is a small change but someone somewhere will probably get triggered by it. (I won't!)

Comment (Trial97) [reply launcher/ui/widgets/VariableSizedImageObject.cpp]:
```suggestion
    if (size.isEmpty())  // can't resize an empty image
```

**Review by StupidRepo — APPROVED** [review]
Perfect 👍

**Review by timoreo22 — APPROVED** [review]

**Review by TheKodeToad — APPROVED** [review]
