### PR TITLE
fix(launcher): set correct bin path for self-contained appimages

### LINKED ISSUE #4411: Java checker library could not be found
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 10.0.0-develop

### Version of Qt

Qt 6.9.3

### Description of bug

The newest nightly appimage (603da29) seems to not contain the Java checker library.

### Steps to reproduce

Try to run any instance and you will receive this error; 
"Java checker library could not be found. Please check your installation."

### Suspected cause

_No response_

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by getchoo**
Fixes https://github.com/PrismLauncher/PrismLauncher/issues/4411

Follow up on https://github.com/PrismLauncher/PrismLauncher/pull/4314. This fixes the updater and other things reliant on an actually correct m_binPath

### CODE REVIEW

File: launcher/Application.cpp [hunk 1]
```diff
@@ -371,7 +371,25 @@ Application::Application(int& argc, char** argv) : QApplication(argc, argv)
...
+    // Yes, this can technically trigger the logic below if someone makes an AppImage with an actual launcher exe named "ld-linux"
+    // Please don't :)
+    const bool executedFromLinker = QFileInfo(binFilePath).fileName().startsWith("ld-linux");
+
+    // NOTE(@getchoo): In order for `go-appimage` to generate self-contained AppImages, it executes apps from a bundled linker at
+    // <root>/lib64
+    // This is not the path to our actual binary, which we want
+    QString binPath;
+    if (isAppImage && executedFromLinker) {
+        binPath = FS::PathCombine(binFilePath, "../bin");
```
Comment (DioEgizio) [inline launcher/Application.cpp]:
```suggestion
        binPath = FS::PathCombine(binFilePath, "../../bin");
```
image

File: launcher/Application.cpp [hunk 2]
```diff
@@ -371,7 +371,25 @@ Application::Application(int& argc, char** argv) : QApplication(argc, argv)
...
+    // Yes, this can technically trigger the logic below if someone makes an AppImage with an actual launcher exe named "ld-linux"
+    // Please don't :)
+    const bool executedFromLinker = QFileInfo(binFilePath).fileName().startsWith("ld-linux");
+
+    // NOTE(@getchoo): In order for `go-appimage` to generate self-contained AppImages, it executes apps from a bundled linker at
+    // <root>/lib64
+    // This is not the path to our actual binary, which we want
+    QString binPath;
+    if (isAppImage && executedFromLinker) {
+        binPath = FS::PathCombine(applicationDirPath(), "../bin");
```
Comment (DioEgizio) [inline launcher/Application.cpp]:
```suggestion
        binPath = FS::PathCombine(applicationDirPath(), "../usr/bin");
```

**Review by DioEgizio — APPROVED** [review]
IT FINALLY WORKS :D

**Review by Trial97 — APPROVED** [review]
