### PR TITLE
Fix portable if manifest is missing

### LINKED ISSUE #2191: Prism Launchr update ignores / removes portable.txt
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0 -> 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

After updating from 8.0 to 8.2 configuration window pops up with defaults and not previous configuration. After finishing the configuration no instances are displayed and all previous settings are lost.
This is because there is no portable.txt in the folder any more and prism is looking in the wrong directories for the files / folders.

It can be easily fixed by recreating the portable.txt inside the Prism Launcher folder, but should not be required to do every update.

### Steps to reproduce

- Install Prism Launcher 8.0
- Create portable.txt inside Prism Launcher folder
- Create some instances / change some settings (e.g.: default ram usage is a good one to see in configuration)
- Click on Update to install newest version (8.2 in my case)
- After going through install the portable.txt will be missing, instances will be gone and changes reset.

### Suspected cause

portable.txt removed during install process and not recreated after.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #2191
Basically, we should not touch the `portable.txt` file on the update

### CODE REVIEW

**Review by DioEgizio — CHANGES_REQUESTED** [review]
That's not gonna fix that, look into the nsis code, we uninstall everything that was in the folder and reinstall again to not having residual DLLs that could cause issues. Honestly adding portable.txt to nsis installs shouldn't be a supported configuration, just use the portable .zip if you need that

**Comment by Trial97** [comment]
This is more like a fix for portable in case they delete the manifest file.
Here is the situation this solves:
- download and extract portable version
- delete the manifest file
- do a prism update
- now prism is no longer portable

Yeah I know that the situation described in the issue is not desired, but this doubles as both a fix for that situation but also for the mentioned one.  
So if this is not desired please close both the issue and PR.

File: launcher/updater/prismupdater/PrismUpdater.cpp [hunk 1]
```diff
@@ -474,8 +474,7 @@ PrismUpdaterApp::PrismUpdaterApp(int& argc, char** argv) : QApplication(argc, ar
             target_dir = QDir(m_rootPath).absoluteFilePath("..");
         }
 
-        QMetaObject::invokeMethod(
-            this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);
+        QMetaObject::invokeMethod(this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);
```
Comment (Trial97) [inline launcher/updater/prismupdater/PrismUpdater.cpp]:
```suggestion
        QMetaObject::invokeMethod(
           this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);Qt::QueuedConnection);
```

File: launcher/updater/prismupdater/PrismUpdater.cpp [hunk 2]
```diff
@@ -475,7 +475,7 @@ PrismUpdaterApp::PrismUpdaterApp(int& argc, char** argv) : QApplication(argc, ar
         }
 
         QMetaObject::invokeMethod(
-            this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);
+           this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);Qt::QueuedConnection);
```
Comment (Trial97) [inline launcher/updater/prismupdater/PrismUpdater.cpp]:
```suggestion
            this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);
```

**Review by Ryex — APPROVED** [review]
*le sigh* This is such a silly use case to support...

I suppose this is fine because portable is just a marker file and we won't be adding any data to it

**Review by DioEgizio — APPROVED** [review]
