### PR TITLE
Assign java max mem based on system RAM

### LINKED ISSUE #390: Set default Max Ram under the system Ram amount
### Role

Users with 4GB and lower ram amounts exist

### Suggestion

change default max ram to be dynamic instead of hardcoded

### Benefit

users don't crash from not changing the ram amount from default when their actual system has 4GB of ram

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

the below should not be hardcoded to 4GB:
https://github.com/PrismLauncher/PrismLauncher/blob/2cf4d5f8ecd4afb1179b5a4e3bf694bcd359b628/launcher/Application.cpp#L569

this should be a function of the system ram (like already obtained in other parts of the codebase, eg: 
https://github.com/PrismLauncher/PrismLauncher/blob/a9d4370ad462b4ad3dd91f6bc38b40262967b5b2/launcher/ui/widgets/JavaSettingsWidget.cpp#L27

something like the below sudo-code would be nice for the default MaxMemoryAlloc that the user will see in the initial setup GUI:

```
if (Sys::getSystemRam() / Sys::mebibyte) < (4096 * 1.5); then
  MaxMemoryAlloc = Sys::getSystemRam() / Sys::mebibyte / 1.5
else
  MaxMemoryAlloc = 4096
fi
```

that will only set MaxMemoryAlloc to 4GB if the system ram is greater than 1.5X4GB (6GB). if the system ram is less than that, then it sets the default max to the system ram divided by 1.5

### PR DESCRIPTION
**Pull request by txtsd**
If the system has <6GB RAM, it uses (system RAM / 1.5) If the system has >=6GB, it uses 4GB

Uses suggestions from and closes #390

### CODE REVIEW

**Comment by theofficialgman** [comment]
@txtsd built and tested. works great.

I'll leave it up to you and the other developers to chose reasonable cutoff points and constants

File: launcher/Application.cpp [hunk 1]
```diff
@@ -1633,3 +1633,17 @@ QString Application::getUserAgentUncached()
...
 }
+
+int Application::suitableMaxMem()
+{
+    float totalRAM = (float)Sys::getSystemRam() / (float)Sys::mebibyte;
+    int maxMemoryAlloc;
+
+    // If totalRAM < 6GB, use (totalRAM / 1.5), else 4GB
+    if (totalRAM < (4096 * 1.5))
+        maxMemoryAlloc = (int) (totalRAM / 1.5);
```
Comment (DioEgizio) [inline launcher/Application.cpp:1644]: Wouldn't it make more sense to divide by 2? (e.g. if I have 4gb of ram, I'd want to allocate just 2)

Comment (txtsd) [reply launcher/Application.cpp:1644]: These are just defaults. People can reduce the RAM they want to allocate. But yea, I'll wait for more people to chime in.

Comment (theofficialgman) [reply launcher/Application.cpp:1644]: There was another user in discord suggesting the divide by two and letting the default max be 12GB

I'm personally fine with both of those suggestions

**Review by Scrumplex — APPROVED** [review]

File: launcher/Application.cpp (hunk 1 above)
Comment (ghost) [reply launcher/Application.cpp:1644]: let's have the default max at 8GB. 12 seems a bit too overkill.

Comment (jn64) [reply launcher/Application.cpp:1644]: How about simply:

```c++
int maxMemoryAlloc = std::min(int(totalRAM / 2), 4096);
```

Comment (ghost) [reply launcher/Application.cpp:1644]: let's settle at 6gb. ~~also i don't know programming but could totalRAM be not integer since we measure it down to megabytes~~

**Review by flowln — APPROVED** [review]

**Comment by flowln** [comment]
(forgor review message) Either way, with it as-is or with jn64's suggestion, it's fine for me. Just keep the comment!

File: launcher/Application.cpp (hunk 1 above)
Comment (txtsd) [reply launcher/Application.cpp:1644]: Thanks for y'all's inputs. We'll merge it as-is for now.
