### PR TITLE
Enhance the process of removing invalid characters from a path

### LINKED ISSUE #2455: Configs with "+" symbol get renamed to "-"
### Operating System

Windows 10

### Version of Prism Launcher

8.3

### Version of Qt

6.6.3

### Description of bug

It seems like configs with "+" symbol get converted to "-". 

When downloading a modpack with set bonus mod, 1.12.2.009+.cfg is the config that should be used, however it gets renamed into 1.12.2.009-.cfg, which isn't used by the mod thus the mod generating a new config and resetting all config values.
image

This is what is shipped with the modpack.
image

I don't know if this occurs with other files.

This only occurs on Prism launcher. Installing from CurseForge doesn't rename the file.

### Steps to reproduce

Install RotN or any modpack with set bonus, or just the mod itself.
Verify that it's shipped with 1.12.2.009+.cfg
Check config and notice it's been renamed to 1.12.2.009-.cfg

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
not sure why + was considered as needing to be removed in Windows but still if there are any other char let me know
see: https://discord.com/channels/1031648380885147709/1241690850287681617 and the https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file for more info

fixes #2455

### CODE REVIEW

**Comment by ColonelGerdauf** [comment]
I wonder if it is worthwhile to deal with the non-printable characters, particularly from 1 to 31.

And, to be on the safe side, `^` is also known to cause issues in the FAT file system family.

**Comment by Trial97** [comment]
> I wonder if it is worthwhile to deal with the non-printable characters, particularly from 1 to 31.

I don't think we should bother as that is not a correct filename in both linux and windows.


> And, to be on the safe side, `^` is also known to cause issues in the FAT file system family.

I'm ok with adding that to the list but can you provide a link or some piece of documentation that mentioned this?

**Comment by ColonelGerdauf** [comment]
This is the most semi-formal document I can find for the time being:
https://jpsoft.com/help/filenames.htm

**Comment by ColonelGerdauf** [comment]
While character 0 (NUL) is impossible across the board, between NUL and 32 (space) has been repeatedly cited as a limitation specific to Windows. Apparently those are fine in Linux, which I suppose can happen when you write the filenames via CLI.

Linux is a confusing operating system.

**Comment by Trial97** [comment]
I'm not comfortable implementing all that stuff. There were no issue reports regarding the characters set on linux .
So if you want all that just do a PR that does that(right now that function is called only for windows).

**Comment by kappa-maintainer** [comment]
I don't think handling extra characters is even needed - all known loader either uses `.` or `-`, `+` from semantic version is the only new thing here. IMO even making semver available chars into a white list won't crash 0.1% instances

**Comment by Ryex** [comment]
As a deeper issue I just discovered that fabric packs have likely been failing to launch on windows forever because of this.

```
Exception caught from launcher
java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap
	at net.fabricmc.loader.impl.game.LoaderLibrary.<clinit>(LoaderLibrary.java:41)
	at net.fabricmc.loader.impl.game.LibClassifier.<init>(LibClassifier.java:100)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:173)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:175)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinBootstrap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more
Exiting with ERROR
[21:59:49] [WARN] [FabricLoader/Knot]: Class path entries reference missing files: C:/Users/ryexc/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar - the game may not load properly!
```
image

because `sponge-mixin` is uing a `+` in it's file name

we need to take a look at our library path code and at least ensure we are *consistent* with our replacement of bad path charaters

**Comment by Ryex** [comment]
```patch
diff --git a/launcher/minecraft/launch/LauncherPartLaunch.cpp b/launcher/minecraft/launch/LauncherPartLaunch.cpp
index 4e021c4a8..90e4e141a 100644
--- a/launcher/minecraft/launch/LauncherPartLaunch.cpp
+++ b/launcher/minecraft/launch/LauncherPartLaunch.cpp
@@ -118,7 +118,7 @@ void LauncherPartLaunch::executeTask()
 #ifdef Q_OS_WIN
     QStringList processed;
     for (auto& item : classPath) {
-        processed << FS::getPathNameInLocal8bit(item);
+        processed << FS::getPathNameInLocal8bit(FS::RemoveInvalidPathChars(item));
     }
     args << processed.join(';');
 #else
 ```
 
 This should help make things consistent and allow things to launch

**Comment by Ryex** [comment]
```patch
diff --git a/launcher/minecraft/Library.cpp b/launcher/minecraft/Library.cpp
index 2c3f2035f..6c6ec78c7 100644
--- a/launcher/minecraft/Library.cpp
+++ b/launcher/minecraft/Library.cpp
@@ -51,6 +51,9 @@ void Library::getApplicableFiles(const RuntimeContext& runtimeContext,
 {
     bool local = isLocal();
     auto actualPath = [&](QString relPath) {
+#ifdef Q_OS_WIN
+            relPath = FS::RemoveInvalidPathChars(relPath);
+#endif
         QFileInfo out(FS::PathCombine(storagePrefix(), relPath));
         if (local && !overridePath.isEmpty()) {
             QString fileName = out.fileName();
```

tested, this should keep things consistant

**Comment by Trial97** [comment]
This PR did become too much for its initial purpose but now this should handle most of the weird cases with filename naming.  
Needs testing ~~and a fix of the CI.~~

File: launcher/FileSystem.cpp [hunk 1]
```diff
@@ -872,16 +831,35 @@ QString RemoveInvalidPathChars(QString path, QChar replaceWith)
...
-
-    if (fileSystemType == "FAT32") {
-        invalidChars += BAD_FAT32_CHARS;
-    } else if (fileSystemType == "NTFS") {
-        invalidChars += BAD_NTFS_CHARS;
-    } else if (fileSystemType == "HFS+" || fileSystemType == "APFS") {
-        invalidChars += BAD_HFS_CHARS;
-    } else if (fileSystemType == "exFAT") {
-        invalidChars += BAD_EXFAT_CHARS;
+    switch (statFS(path).fsType) {
```
Comment (Ryex) [inline launcher/FileSystem.cpp:834]: Oh good, I was wondering why you were trying to reimpliment that function :P I only did hours of research to implement it :P

Comment (Ryex) [inline launcher/FileSystem.cpp:835]: Oh good, I was wondering why you were trying to reimpliment that function :P I only did hours of research to implement it :P

File: launcher/FileSystem.cpp [hunk 2]
```diff
@@ -872,16 +831,35 @@ QString RemoveInvalidPathChars(QString path, QChar replaceWith)
...
+            invalidChars += BAD_NTFS_CHARS;
+            break;
+        // case FilesystemType::REFS:
+        // case FilesystemType::EXT:
+        // case FilesystemType::EXT_2_OLD:
+        // case FilesystemType::EXT_2_3_4:
+        // case FilesystemType::XFS:
+        // case FilesystemType::BTRFS:
+        // case FilesystemType::NFS:
+        // case FilesystemType::ZFS:
```
Comment (Ryex) [inline launcher/FileSystem.cpp:850]: The only invalid "path" character on these filesystesms would be a null byte `\0` (also invalid on windows), but I'm not sure that needs to be checked for. but I do feel it should be commented on in this code to avoid confusion from others

File: launcher/FileSystem.cpp [hunk 3]
```diff
@@ -872,16 +831,35 @@ QString RemoveInvalidPathChars(QString path, QChar replaceWith)
...
-    } else if (fileSystemType == "exFAT") {
-        invalidChars += BAD_EXFAT_CHARS;
+    switch (statFS(path).fsType) {
+        case FilesystemType::FAT:
+            invalidChars += BAD_FAT_CHARS;
+            break;
+        case FilesystemType::NTFS:
+            invalidChars += BAD_NTFS_CHARS;
+            break;
+        // case FilesystemType::REFS:
```
Comment (Ryex) [inline launcher/FileSystem.cpp]: REFS afaik has the same limitations in names as NTFS but considering it's covered it only availble on window it should be covered the default bad win chars above. still feell it should be added to the NTFS fall-through

**Review by Ryex — CHANGES_REQUESTED** [review]

File: launcher/FileSystem.cpp (hunk 1 above)
Comment (Trial97) [reply launcher/FileSystem.cpp:835]: And it took me hours to find it in the code(after I had a semi-working implementation).
I need it mostly to ensure that I replace bad characters in the path based on the filesystem.

**Comment by Trial97** [comment]
Mostly this PR was just the removal of '+' character from the original list. 
Now I opted to implement a subset of path sanitization for some of the most known filesystems and operating systems.
This is not a complete map of a filesystem to bad characters and can be expanded.

**Review by Ryex — APPROVED** [review]
LGTM now. 
you sure this shouldn't be an 8.4 and backport pr? it will fix a fairly major issue launching modern fabric packs on windows.

EDIT: Just tested, works with windows paths as expected

**Comment by Trial97** [comment]
I will leave that decision to other maintainers.
Either way, I need approvals from them to get anything merged so if other maintainers feel that it is for 8.4 then let them change it. As for me, I push to major anything that I feel it may impact more users or needs a little bit more testing

**Review by 3gf8jv4dv — APPROVED** [review]
I was unable to launch some modded versions (e.g. 1.20.6 NeoForge/Fabric, etc.) in builds on the `develop` branch. On my side, [`8.3` (release)](https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.3) everything works fine.

I noticed the problem with the path by looking at the logs (Similar to the case of Ryex). After trying the build generated by this PR, I can confirm that this PR fixed the issue of the game not launching. 👍 

I think this PR needs to be reviewed and merged as soon as possible.

**Review by ColonelGerdauf — APPROVED** [review]
I concur.

**Review by DioEgizio — APPROVED** [review]
