### PR TITLE
fix heap overflow with unstable version comparation

### LINKED ISSUE #5210: Heap buffer overflow when reading Packwiz mod index
### Operating System

Linux

### Version of Prism Launcher

`develop` branch commit `53385fdfea8e0cfb91f147c29b9f47cb04535422`

### Version of Qt

Qt 6.10.2

### Description of bug

Sanitizer back trace:

Image

### Steps to reproduce

You can reproduce this crash by simply downloading the latest version of `Fabric Language Kotlin`

File attachment in case the above step does not work:
[fabric-language-kotlin.pw.toml.txt](https://github.com/user-attachments/files/26084763/fabric-language-kotlin.pw.toml.txt)

### Suspected cause

https://github.com/PrismLauncher/PrismLauncher/pull/5194

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #5251: version "26.1" is listed twice
### Operating System

Windows 11

### Version of Prism Launcher

Launcher 10.0.5

### Version of Qt

Qt 6.10.2

### Description of bug

Granted, this may be a matter of early usage. When I create a 26 instance with Fabric or Quilt, and I download the mods available in the new version, "26.1" gets listed twice in the "Minecraft Version" column.

### Steps to reproduce

- Create a 26.1 instance
- load it with either Fabric or Quilt modloader
- download an available mod
- look in the "Minecraft Version" tab for the listed mod

### Suspected cause

It is possible for a "26.0" version to be written as "26.1", or otherwise could have a double entry in either the mod metadata, or Modrinth data.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #5210
fixes #5251 (the removeDuplicates line)

The issue was mostly with the Version parsing and compring implementation.
Refactored that based on the https://git.sleeping.town/exa/FlexVer examples.

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

File: tests/Version_test.cpp [hunk 1]
```diff
@@ -181,8 +181,34 @@ class VersionTest : public QObject {
...
+        QCOMPARE(r(a, c), true);
+        // transitive equivalence
+        QCOMPARE(e(a, b) && e(b, c), e(a, c));
+    }
 };
 
 QTEST_GUILESS_MAIN(VersionTest)
 
 #include "Version_test.moc"
+// drumul jilavei 70
```
Comment (Octol1ttle) [inline tests/Version_test.cpp]: wot

Comment (Trial97) [reply tests/Version_test.cpp]: ups

**Comment by 0x189D7997** [comment]
Yep, this fixes ATM10: To the Sky install. Huge thanks!

File: flake.nix [hunk 2]
```diff
@@ -9,7 +9,7 @@
   };
 
   inputs = {
-    nixpkgs.url = "https://channels.nixos.org/nixos-25.11/nixexprs.tar.xz";
+    nixpkgs.url = "https://channels.nixos.org/nixos-unstable/nixexprs.tar.xz";
```
Comment (DioEgizio) [inline flake.nix:12]: is this really necessary?

Comment (Trial97) [reply flake.nix:12]: this was the start of https://github.com/PrismLauncher/PrismLauncher/pull/5292
I can remove the commit if it makes it easier to merge but then the clang tidy will fail
And to answer yes we need to be on unstable to support all the clang tidy configs.
So should I remove the commit from this PR? (warning the clang tidy will fail without that commit)

Comment (DioEgizio) [reply flake.nix:12]: remove the commits and rebase after the other pr is merged

**Review by DioEgizio — APPROVED** [review]

**Comment by Trial97** [comment]
did the rebase:
 - fixed some clang-tidy reported issues
 - the QTest one I have no idea how and why is reported
 - and disable the lint on the Version constructor (I do not want to touch 50 files to make that constructor explicit); it can be done if somebody wants that but I will need to touch a bunch of files
