### PR TITLE
Try refreshing account on launch if needed

### LINKED ISSUE #293: Prism Launcher does not check if it has regained internet access
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

If you start prism launcher without internet access, and then later re-gain internet access, prism launcher continues to assume its offline and will not recheck until restarted.

### Steps to reproduce

1. Turn off your internet
2. Start Prism Launcher
3. Note that Prism Launcher prompts for an offline name when launching an instance
4. Enable internet (and wait for it to connect)
5. Prism Launcher continues to assume it is offline when launching an instance

### Suspected cause

Best guess is the check is only done once on startup rather than each time required.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #520: Refresh account on Launch
### Role

I play too much modded.

### Suggestion

I want the launcher to automatically refresh my account when I launch the instance.

### Benefit

I never see the "Invalid Session Token" message again.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### LINKED ISSUE #592: Cannot launch in online mode after system is suspended
### Operating System

Windows 10

### Version of Prism Launcher

Prism Launcher 5.1
(assume it still happens in 5.2)

### Version of Qt

Qt 6.4.0

### Description of bug

Launcher works as intended before putting my computer in "sleep" mode.
After "waking" it up, the launcher is unable to launch in online mode, and instead prompts me to play offline.

Note: This is fixed after I restart the launcher. 
I have experienced this bug on a multitude of different Windows devices; have not tested other operating systems.

### Steps to reproduce

Open Prism
Put computer in sleep mode
Turn computer back on
Press launch on an instance

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #920: Prism "Offline account" bug
### Operating System

_No response_

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

Qt 6.4.2.

### Description of bug

The launch button sometimes decides i am not connected into my account, and automatically forces me to choose an offline name.

### Steps to reproduce

I don't know how to reproduce the bug, but it happens randomly.

### Suspected cause

None

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #920
fixes #592
fixes #520
fixes #293
maybe #699 (not sure but looks similar)

This is the same as https://github.com/PrismLauncher/PrismLauncher/pull/1558 but it's ready to review( and also the mentioned PR did not have any activity for some time)

A good way to test this:
- stop your internet(disable the wifi)
- start prism
- check if you are prompted with the offline dialog when you try to start an instance( you do not need to start it)
- connect to internet
- start a instance
- you should not be prompted with anything starting the game online

### CODE REVIEW

File: launcher/LaunchController.cpp [hunk 1]
```diff
@@ -249,17 +257,30 @@ void LaunchController::login()
...
-            */
             case AccountState::Expired: {
-                auto errorString = tr("The account has expired and needs to be logged into manually again.");
-                QMessageBox::warning(m_parentWidget, tr("Account refresh failed"), errorString, QMessageBox::StandardButton::Ok,
-                                     QMessageBox::StandardButton::Ok);
-                emitFailed(errorString);
+                auto errorString = tr("The account has expired and needs to be logged into manually. Press OK to log in again.");
+                auto button = QMessageBox::warning(m_parentWidget, tr("Account refresh failed"), errorString,
+                                                   QMessageBox::StandardButton::Ok | QMessageBox::StandardButton::Cancel,
+                                                   QMessageBox::StandardButton::Ok);
```
Comment (Scrumplex) [inline launcher/LaunchController.cpp]: A Yes/No messagebox might be better UX.

Question could be `The account has expired and needs to be reauthenticated. Do you want to reauthenticate this account?`

File: launcher/LaunchController.cpp [hunk 2]
```diff
@@ -249,17 +257,30 @@ void LaunchController::login()
...
+                        auto newAccount = MSALoginDialog::newAccount(
+                            m_parentWidget, tr("Please enter your Mojang account email and password to add your account."));
+                        accounts->addAccount(newAccount);
+                        if (isDefault) {
+                            accounts->setDefaultAccount(newAccount);
+                        }
+                        m_accountToUse = nullptr;
+                        decideAccount();
+                        continue;
+                    }
```
Comment (Scrumplex) [inline launcher/LaunchController.cpp]: I don't feel like this code belongs here. Ideally this should just call some function somewhere else that does all of this

Comment (Trial97) [reply launcher/LaunchController.cpp]: Not sure where else to put this code so for now I just extracted it as a separate function on the `LaunchController` I could not move it in AccountList as I would have polluted that with UI stuff. 
Do you have any suggestions about where you want it to be?

**Review by Scrumplex — APPROVED** [review]

**Review by getchoo — APPROVED** [review]
