### PR TITLE
Fix Trash issues

### LINKED ISSUE #143: No warning for deleting instances
### Operating System

Windows

### Description of bug

If you click the 'Delete' button on an instance, you should normally get a warning. However, there is no warning. This is problematic as people can easily permanently delete instances.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #150: Undo Last Instance Deletion Doesn't Work
### Operating System

Windows

### Version of PolyMC

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

The "Undo Last Instance Deletion" command doesn't seem to work

### Steps to reproduce

- Create an instance and delete it
- If you don't have a menu bar, press Alt to show it
- Go to the Edit menu
- The "Undo Last Instance Deletion" option is grayed out

### Suspected cause

Likely a conflict with the new feature that moves trashes instances instead of deleting them

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #150 
Closes #143 

This also disables the Trash feature on Flatpak as Qt does not use XDG Trash portal.

### CODE REVIEW

File: launcher/FileSystem.cpp [hunk 1]
```diff
@@ -228,6 +229,9 @@ bool trash(QString path, QString *pathInTrash = nullptr)
 #if QT_VERSION < QT_VERSION_CHECK(5, 15, 0)
     return false;
 #else
+    // FIXME: Figure out trash in Flatpak. Qt seemlingly doesn't use the Trash portal
```
Comment (flowln) [inline launcher/FileSystem.cpp]:
```suggestion
    // FIXME: Figure out trash in Flatpak. Qt seemingly doesn't use the Trash portal
```

:slightly_smiling_face:

**Review by ryanccn — APPROVED** [review]
lgtm other than what flow commented

**Review by DioEgizio — APPROVED** [review]

**Review by flowln — APPROVED** [review]
