### PR TITLE
Apply selected style to NSWindow elements (e.g. title bar) on macOS

### LINKED ISSUE #3814: [Suggestion] Remove/Style Top Bar for MacOS
### Role

I play Minecraft, modded and vanilla, mostly multiplayer.  I sometimes stream it on Twitch.

### Suggestion

I would like to have the top bar that appears on windows/apps in MacOS to be either styled or removed.

### Benefit

I use a dark mode theme for the launcher, but light mode theme for my system. This majorly clashes visually when the top bar is round and bright while the rest of the launcher window is dark and sharp.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I found online that the top bar can be removed or changed by the program itself, but I'm not sure how since I'm not an app developer.  This website however seems to show a way to do it, but frankly I don't understand it much myself.  All I know is that it can be done somehow: 
[https://developer.apple.com/documentation/swiftui/customizing-window-styles-and-state-restoration-behavior-in-macos](url)

It looks so badly with the light-theme bar on a dark-theme program, especially since the bar is so rounded.  It's not a huge issue, but it's enough to annoy me lol.

Image

### LINKED ISSUE #3825: MacOS System Wide Font Styling Overwrites Tooltip Style
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 8.4, 9.4, 10.0.0-develop

### Version of Qt

Qt 6.9.0, 6.7.3, 6.6.3

### Description of bug

When Prism Launcher is in Dark Mode and MacOS is in light mode it will use the MacOS light mode font styling for the launcher display name in the tooltip to create or view an instance. This creates really messy looking grey text with a white drop shadow as seen in the image below.

Image

However with both MacOS and Prism Launcher in dark mode it replaces the font style appropriately with the dark mode styling as seen below.

Image

### Steps to reproduce

Left click anywhere in the Minecraft instances field with MacOS light mode and Prism Launcher dark mode.

### Suspected cause

As above, the style is taken from MacOS styling which is conflicting with the Prism Launcher theme.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by kthchew**
Closes #3814
Closes #3825

Qt doesn't apply the proper style to elements such as the title bar or text shadows, so this must be done in native code.

Example screenshots (see linked issues for before screenshots):

Screenshot 2025-07-16 at 12 37 26 AM

Screenshot 2025-07-16 at 12 29 51 AM

Screenshot 2025-07-16 at 12 37 44 AM

Screenshot 2025-07-16 at 12 29 45 AM

### CODE REVIEW

File: launcher/ui/themes/ThemeManager.h [hunk 1]
```diff
@@ -39,6 +39,7 @@ inline auto themeWarningLog()
 class ThemeManager {
    public:
     ThemeManager();
+    ~ThemeManager();
```
Comment (Trial97) [inline launcher/ui/themes/ThemeManager.h:42]: I would like to be virtual if possible(not necessary but a good practice)

**Review by Trial97 — APPROVED** [review]

**Review by Ryex — APPROVED** [review]
