### PR TITLE
Ensure correct image format when importing skin files

### LINKED ISSUE #4032: Launcher crashes when trying to manage skins
### Operating System

Linux

### Version of Prism Launcher

Prism launcher 10.0.0-develop

### Version of Qt

Qt 6.9.1

### Description of bug

Prism crashes whenever i try to manage skins
This is self explanatory.

### Steps to reproduce

* Open skin manager
* Put in a png
* Prism crashes
* Try to open skin manager again
* Prism crashes again

### Suspected cause

Maybe i put in an oversized png?
I dunno though.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #4032

### CODE REVIEW

**Review by Ryex — APPROVED** [review]

File: launcher/minecraft/skins/SkinModel.cpp [hunk 1]
```diff
@@ -23,10 +23,14 @@
...
-static QImage improveSkin(const QImage& skin)
+static QImage improveSkin(const QImage& _skin)
 {
+    auto skin = _skin;
+    if (skin.format() != QImage::Format_RGBA8888) {
+        skin = skin.convertToFormat(QImage::Format_RGBA8888);
+    }
     if (skin.size() == QSize(64, 32)) {  // old format
-        QImage newSkin = QImage(QSize(64, 64), skin.format());
+        auto newSkin = QImage(QSize(64, 64), skin.format());
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp:35]:
```suggestion
        auto newSkin = QImage(QSize(64, 64), QImage::Format_RGBA8888);
```
It seems the skin from the issue was in the "old format". I *assume* this is a part of it since we haven't gotten other reports, so I'm not sure why we would always convert to this format

**Review by getchoo — COMMENTED** [review]
I'm skeptical of the underlying issue here

The traceback on Windows makes me think this is to do with the preview instead, rather than any other parsing or uploading of this skin

image

Why is that function dependent on copying from this specific format? Shouldn't this kind of logic be there instead? Or at least an assertion?

And why do we need this specific format? We don't use it anywhere else here. In fact, the *only* format we specifically declare here is `QImage::Format_ARGB32` for the previews, and that's obviously still different from the format we're explicitly converting to. Why not use `ARGB32` instead?

Some context as to how you solved this would be great

**Comment by Trial97** [comment]
Context: the image has a format that is not supported by qpainter and when the image with that unsupported format is drawn for the preview it crashes 


Extra:
The crash happens because a PNG skin loads as an indexed‐color QImage without a valid color table (palette).
When QPainter::drawImage() tries to render it, Qt dereferences a null palette pointer (clut), causing a SIGSEGV.

**Comment by getchoo** [comment]
> the image has a format that is not supported by qpainter and when the image with that unsupported format is drawn for the preview it crashes

It seems the format you're referring to here is `QImage::Format_Indexed8` based on [this](https://doc.qt.io/qt-6/qpainter.html#begin) part of the docs

If only that image format is unsupported, why bother always converting other formats?

File: launcher/minecraft/skins/SkinModel.cpp [hunk 2]
```diff
@@ -23,10 +23,14 @@
 #include "FileSystem.h"
 #include "Json.h"
 
-static QImage improveSkin(const QImage& skin)
+static QImage improveSkin(const QImage& _skin)
 {
+    auto skin = _skin;
+    if (skin.format() != QImage::Format_RGBA8888) {
+        skin = skin.convertToFormat(QImage::Format_RGBA8888);
+    }
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp]:
```suggestion
```

File: launcher/minecraft/skins/SkinModel.cpp [hunk 3]
```diff
@@ -23,10 +23,14 @@
...
     if (skin.size() == QSize(64, 32)) {  // old format
-        QImage newSkin = QImage(QSize(64, 64), skin.format());
+        auto newSkin = QImage(QSize(64, 64), QImage::Format_RGBA8888);
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp]:
```suggestion
        // It seems some older skins may use this format, which can't be drawn onto
        // https://github.com/PrismLauncher/PrismLauncher/issues/4032
        // https://doc.qt.io/qt-6/qpainter.html#begin
        if (skin.format() == QImage::Format_Indexed8) {
          skin = skin.convertToFormat(QImage::Format_RGB32);
        }
        auto newSkin = QImage(QSize(64, 64), skin.format());
```

**Review by getchoo — COMMENTED** [review]
An assertion in `generatePreviews` for the source image format would also be nice (as to easily catch anything similar later)

File: launcher/minecraft/skins/SkinModel.cpp (hunk 3 above)
Comment (Trial97) [reply launcher/minecraft/skins/SkinModel.cpp]: I do not want to make it dependent(the check for the format) on the file size, as this would crash if the user puts an image that is 64x64 with that format(even if that is not a valid format it can happen and I would want not to have a crash if the user inputs weird stuff).

File: launcher/minecraft/skins/SkinModel.cpp [hunk 4]
```diff
@@ -23,10 +23,17 @@
 #include "FileSystem.h"
 #include "Json.h"
 
-static QImage improveSkin(const QImage& skin)
+static QImage improveSkin(const QImage& _skin)
 {
+    auto skin = _skin;
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp]: Am I missing something here? What's up with this binding?

File: launcher/minecraft/skins/SkinModel.cpp [hunk 5]
```diff
@@ -23,10 +23,17 @@
...
+    // It seems some older skins may use this format, which can't be drawn onto
+    // https://github.com/PrismLauncher/PrismLauncher/issues/4032
+    // https://doc.qt.io/qt-6/qpainter.html#begin
+    if (skin.format() != QImage::Format_RGBA8888) {
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp]:
```suggestion
    if (skin.format() == QImage::Format_Indexed8 {
```
This is wrong. See the previous review

File: launcher/minecraft/skins/SkinModel.cpp [hunk 6]
```diff
@@ -23,10 +23,17 @@
...
+        skin = skin.convertToFormat(QImage::Format_RGBA8888);
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp]:
```suggestion
        skin = skin.convertToFormat(QImage::Format_RGB32);
```
Any reason to convert to this format specifically? According to [the docs](https://doc.qt.io/qt-6/qpainter.html#performance), this will have "significantly worse" performance when painting

File: launcher/minecraft/skins/SkinModel.cpp [hunk 7]
```diff
@@ -23,10 +23,17 @@
...
+    }
     if (skin.size() == QSize(64, 32)) {  // old format
-        QImage newSkin = QImage(QSize(64, 64), skin.format());
+        auto newSkin = QImage(QSize(64, 64), QImage::Format_RGBA8888);
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp]:
```suggestion
        auto newSkin = QImage(QSize(64, 64), skin.format());
```
We can keep grabbing the format from the skin itself, since it should be safe after the above check

File: launcher/minecraft/skins/SkinModel.cpp (hunk 4 above)
Comment (Trial97) [reply launcher/minecraft/skins/SkinModel.cpp]: Yes you are missing the part where I pass the `_skin` as a const reference, as I did not want to copy the image when the function was called.
Should I just remove the const reference from the function argument?

Comment (Trial97) [inline launcher/minecraft/skins/SkinModel.cpp]:
```suggestion
static QImage improveSkin(QImage skin)
{
```

Comment (Trial97) [reply launcher/minecraft/skins/SkinModel.cpp]: Like this

**Review by TayouVR — APPROVED** [review]

File: launcher/minecraft/skins/SkinModel.cpp [hunk 8]
```diff
@@ -110,7 +116,7 @@ SkinModel::SkinModel(QDir skinDir, QJsonObject obj)
         m_model = Model::SLIM;
     }
     m_path = skinDir.absoluteFilePath(name) + ".png";
-    m_texture = QImage(getSkin(m_path));
+    m_texture = getSkin(m_path);
```
Comment (getchoo) [inline launcher/minecraft/skins/SkinModel.cpp:119]: Indenting mistake? Not sure why this isn't picked up....

**Review by getchoo — APPROVED** [review]
Otherwise LGTM. Thanks!

File: launcher/minecraft/skins/SkinModel.cpp (hunk 8 above)
Comment (Trial97) [reply launcher/minecraft/skins/SkinModel.cpp:119]: Maybe I'm missing something, but could you possibly be more specific? I see no indenting mistake on line 119. Are you referring to other lines? Or if it is on this line, what is the mistake(as to me it looks like the indent is the same as on 118)?

Comment (TayouVR) [reply launcher/minecraft/skins/SkinModel.cpp:119]: I don't see a problem here either...
