### PR TITLE
Don't use .index for shaderpacks

### LINKED ISSUE #4644: The .index folder which is generated to keep track of Shaderpacks also shows up in-game with shader loaders, not ideal for UX
### Operating System

_No response_

### Version of Prism Launcher

v10.0

### Version of Qt

6.10.1

### Description of bug

The .index folder also shows in-game with shader loader mods as shader loaders assume any zip file or directory is a shaderpack

Image

Image

A different iris version to prove that it's version independant
Image

### Steps to reproduce

1. Download any shader via the Launcher
2. Use any iris version
3. See .index in-game

### Suspected cause

.index is the cause.
A solution would be to save it in a different dir than the shaderpacks folder or directly sotre the .toml files inside the shaderpacks folder (not as clean)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by TheKodeToad**
Fixes #4644
Puts the .toml files directly in shaderpacks rather than a separate .index
A better long term solution would probably be to rework the meta format :p

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Honestly I don't really like this
Edit: eh better to fix problems quickly rather than leave them broken I suppose

**Comment by Trial97** [comment]
Wouldn't it been easier to instead of moving them on same level designate the shader index folder as
`<instance root>/.minecraft/.shader_index` (like instead of being inside shader moved out in a hidden folder on same level as shaders folder.

P.s. this hole stuff would have been easier if we would have a central file that keeps all this instead of spreading them in multiple files and folders, but this is another discussion not meant for this PR

**Comment by TheKodeToad** [comment]
Well this creates the least breakage for now if there are symlinks involved - currently different instances can share the shaderpack meta just by having shaderpacks linked - and the migration could "steal" the metadata from another instance

**Comment by TheKodeToad** [comment]
Should be ready

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+                qDebug() << "Moved" << src << "to" << dest;
+            } else {
+                movedAll = false;
+                qDebug() << "Error moving" << src << "to" << dest;
+            }
+        }
+
+        if (!movedAll) {
+            // FIXME: not shown in the UI
+            emitFailed(tr("Failed to migrate everything from .index"));
```
Comment (Octol1ttle) [inline launcher/minecraft/mod/ShaderPackFolderModel.cpp]:
```suggestion
            emitFailed(tr("Failed to migrate shaderpack metadata from .index"));
```

File: launcher/ui/dialogs/ExportPackDialog.cpp [hunk 2]
```diff
@@ -103,8 +104,19 @@ ExportPackDialog::ExportPackDialog(MinecraftInstancePtr instance, QWidget* paren
...
-                m_proxy->ignoreFilesWithPath().insert(instanceRoot.relativeFilePath(resourceModel->indexDir().absolutePath()));
+            if (resourceModel == nullptr) {
+                continue;
+            }
+
+            if (!resourceModel->indexDir().exists()) {
+                continue;
+            }
+
+            if (resourceModel->indexDir() == resourceModel->indexDir()) {
```
Comment (Octol1ttle) [inline launcher/ui/dialogs/ExportPackDialog.cpp]: am I missing something here? you're comparing an object to itself

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+        }
+
+        QStringList pwFiles = m_indexDir.entryList({ "*.pw.toml" }, QDir::Files);
+        bool movedAll = true;
+
+        for (const auto& file : pwFiles) {
+            QString src = m_indexDir.filePath(file);
+            QString dest = m_resourceDir.filePath(file);
+
+            if (QFile::rename(src, dest)) {
```
Comment (Octol1ttle) [inline launcher/minecraft/mod/ShaderPackFolderModel.cpp]: `FS::move`?

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp (hunk 1 above)
Comment (Octol1ttle) [inline launcher/minecraft/mod/ShaderPackFolderModel.cpp]: is `tr()` necessary if its not shown in UI

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+        }
+
+        if (!movedAll) {
+            // FIXME: not shown in the UI
+            emitFailed(tr("Failed to migrate everything from .index"));
+            return;
+        }
+
+        if (FS::deletePath(m_indexDir.absolutePath())) {
+            emitFailed(tr("Failed to remove old .index dir"));
```
Comment (Octol1ttle) [inline launcher/minecraft/mod/ShaderPackFolderModel.cpp:39]: is `tr()` necessary if its not shown in UI

**Review by Octol1ttle — CHANGES_REQUESTED** [review]

File: launcher/minecraft/mod/ResourceFolderModel.cpp [hunk 5]
```diff
@@ -334,7 +335,17 @@ bool ResourceFolderModel::update()
...
+
+    Task::Ptr preUpdate(createPreUpdateTask());
+    if (preUpdate != nullptr)
+        task->addTask(preUpdate);
+
+    task->addTask(m_current_update_task);
+
+    connect(task, &Task::finished, [task] { task->deleteLater(); });
+
+    QThreadPool::globalInstance()->start(task);
```
Comment (Trial97) [inline launcher/minecraft/mod/ResourceFolderModel.cpp]: I would not wrap if the preUpdate is null

File: launcher/FileIgnoreProxy.cpp [hunk 6]
```diff
@@ -266,7 +266,21 @@ bool FileIgnoreProxy::filterAcceptsRow(int sourceRow, const QModelIndex& sourceP
...
+        if (fileInfo.fileName().endsWith(suffix)) {
+            return true;
+        }
+    }
+
+    if (m_ignoreFilePaths.covers(relPath(fileInfo.absoluteFilePath()))) {
+        return true;
+    }
+
+    return false;
```
Comment (Trial97) [inline launcher/FileIgnoreProxy.cpp:283]:
```suggestion
    return m_ignoreFilePaths.covers(relPath(fileInfo.absoluteFilePath()));
```

File: launcher/ui/dialogs/ExportPackDialog.cpp (hunk 2 above)
Comment (Trial97) [inline launcher/ui/dialogs/ExportPackDialog.cpp]: Please combine the conditions:
```suggestion
     if (resourceModel == nullptr||!resourceModel->indexDir().exists()||resourceModel->indexDir() == resourceModel->indexDir()) {
```
given that the last one is updated with the correct check( checking a == a is bad)

Comment (TheKodeToad) [reply launcher/ui/dialogs/ExportPackDialog.cpp]: it's meant to compare dir with indexDir

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp (hunk 1 above)
Comment (TheKodeToad) [reply launcher/minecraft/mod/ShaderPackFolderModel.cpp]: Well, we should just fix it not being shown in the UI

Comment (Trial97) [reply launcher/minecraft/mod/ShaderPackFolderModel.cpp]: Not necessary, but it is a good standard as the failed status may be presented to the user in modals.
This is not the case for this but still better safe.

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp (hunk 4 above)
Comment (Trial97) [reply launcher/minecraft/mod/ShaderPackFolderModel.cpp:39]: Not necessary, but it is a good standard as the failed status may be presented to the user in modals.
This is not the case for this but still better safe.

File: launcher/FileIgnoreProxy.cpp (hunk 6 above)
Comment (TheKodeToad) [reply launcher/FileIgnoreProxy.cpp:283]: This is the sort of thing I'd prefer if was avoided in code reviews: it is a trivial matter of taste

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp (hunk 3 above)
Comment (Trial97) [reply launcher/minecraft/mod/ShaderPackFolderModel.cpp]: I would also like to use FS::move here

File: launcher/FileIgnoreProxy.cpp (hunk 6 above)
Comment (Trial97) [reply launcher/FileIgnoreProxy.cpp:283]: I do not want to avoid: is a bad design to have the last lines of a function:
if condition return true else return false

Comment (TheKodeToad) [reply launcher/FileIgnoreProxy.cpp:283]: Well, I don't agree - it's as simple as that lol

Comment (Trial97) [reply launcher/FileIgnoreProxy.cpp:283]: Well, this remains open until another maintainer either sides with me or you.

Comment (TheKodeToad) [reply launcher/FileIgnoreProxy.cpp:283]: The main point is that this sort of stuff doesn't make sense to block merge and I hope you bear this in mind in future

you could also do this
```c++
auto thing = Thing{"hello"};
```
or this
```c++
Thing thing{"hello"};
```
and they're essentially the same yet two people might have pretty strong opinions...  let's not block on things like this

File: launcher/minecraft/mod/ResourceFolderModel.cpp (hunk 5 above)
Comment (TheKodeToad) [reply launcher/minecraft/mod/ResourceFolderModel.cpp]: This would segfault so... that's not good? lol

Comment (TheKodeToad) [reply launcher/minecraft/mod/ResourceFolderModel.cpp]: https://github.com/PrismLauncher/PrismLauncher/blob/develop/launcher/tasks/ConcurrentTask.cpp#L60-L62 there's no checking here and upon dequeueing it's dereferenced

File: launcher/FileIgnoreProxy.cpp (hunk 6 above)
Comment (Trial97) [reply launcher/FileIgnoreProxy.cpp:283]: I disagree with you: If I don't like the code being written that way, I will block it. Obviosly if there are multiple maintainers being ok with the change, then I'm happy to oblige and let the PR be merged.
And again, this suggestion is not something unreasonable or makes the code uglier or run worse, so I do not understand why there is this friction. 
You wanted a review, you got a review is not like I will cherry-pick only the stuff you want to change.
And from what you saw, I did not "request changes" on the PR but commented suggestions: that means that you can merge this PR even without my approval(given two other maintainers are ok with it).

File: launcher/minecraft/mod/ResourceFolderModel.cpp (hunk 5 above)
Comment (Trial97) [reply launcher/minecraft/mod/ResourceFolderModel.cpp]: What I meant is someting along the lines:
```
auto task = m_current_update_task;
Task::Ptr preUpdate(createPreUpdateTask());
    if (preUpdate != nullptr){
 task = new SequentialTask("ResourceFolderModel::update");
        task->addTask(preUpdate);
 task->addTask(m_current_update_task);

    connect(task, &Task::finished, [task] { task->deleteLater(); });
}
QThreadPool::globalInstance()->start(task);

```
this way the current task is not wrapped in a SequentialTask

File: launcher/ui/dialogs/ExportPackDialog.cpp (hunk 2 above)
Comment (Trial97) [reply launcher/ui/dialogs/ExportPackDialog.cpp]: I still want them to be one single condition

File: launcher/FileIgnoreProxy.cpp (hunk 6 above)
Comment (TheKodeToad) [reply launcher/FileIgnoreProxy.cpp:283]: I'm not trying to be difficult - I don't want this sort of review to be encouraged on anyone's PRs! I could just go along with this but it wouldn't be setting a good precedent.

Comment (Trial97) [reply launcher/FileIgnoreProxy.cpp:283]: We both are... difficult. But again, you can merge this without me giving an "approval" is not like I will block it on this. As mentioned above lets wait and see the opinion of other maintainers on how we should solve this.
Should we move this to discord or are you ok with just waiting for another maintainer to say if it's ok with my suggestion or not? 
This is the last one from me anyway until another maintainer steps in, so if you want, we can discuss on Discord.

Comment (TheKodeToad) [reply launcher/FileIgnoreProxy.cpp:283]: To be clear: nitpicking is fine. but I feel like it's never gone this far lol

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+
+        for (const auto& file : pwFiles) {
+            QString src = m_indexDir.filePath(file);
+            QString dest = m_resourceDir.filePath(file);
+
+            if (FS::move(src, dest)) {
+                qDebug() << "Moved" << src << "to" << dest;
+            } else {
+                movedAll = false;
+                qDebug() << "Error moving" << src << "to" << dest;
```
Comment (Octol1ttle) [inline launcher/minecraft/mod/ShaderPackFolderModel.cpp]: `FS::move` already logs if failed
```suggestion
```

File: launcher/minecraft/mod/ShaderPackFolderModel.cpp [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+            }
+        }
+
+        if (!movedAll) {
+            // FIXME: not shown in the UI
+            emitFailed(tr("Failed to migrate shaderpack metadata from .index"));
+            return;
+        }
+
+        if (FS::deletePath(m_indexDir.absolutePath())) {
```
Comment (Octol1ttle) [inline launcher/minecraft/mod/ShaderPackFolderModel.cpp]:
```suggestion
        if (!FS::deletePath(m_indexDir.absolutePath())) {
```

**Review by Octol1ttle — APPROVED** [review]

File: launcher/minecraft/mod/ResourceFolderModel.cpp [hunk 9]
```diff
@@ -334,7 +335,22 @@ bool ResourceFolderModel::update()
         },
         Qt::ConnectionType::QueuedConnection);
 
-    QThreadPool::globalInstance()->start(m_current_update_task.get());
+    Task::Ptr preUpdate{createPreUpdateTask()};
+
+    if (preUpdate != nullptr) {
+        auto task = new SequentialTask("ResourceFolderModel::update");
+
+        if (preUpdate != nullptr)
```
Comment (Trial97) [inline launcher/minecraft/mod/ResourceFolderModel.cpp]: I know you will hate me but this if is not needed now as it is checked at line 340

File: launcher/minecraft/mod/ResourceFolderModel.cpp (hunk 5 above)
Comment (TheKodeToad) [reply launcher/minecraft/mod/ResourceFolderModel.cpp]: Done

File: launcher/minecraft/mod/ResourceFolderModel.cpp (hunk 9 above)
Comment (TheKodeToad) [reply launcher/minecraft/mod/ResourceFolderModel.cpp]: nah, that is genuinely appreciated

**Review by Trial97 — APPROVED** [review]
Still not liking the `if codition return true else return false` thing but you get the approval ( I will fix it myself in the worst case :) )

File: launcher/FileIgnoreProxy.cpp (hunk 6 above)
Comment (Ryex) [reply launcher/FileIgnoreProxy.cpp:283]: it's about intention of the function.

does the function return the result of the state of that conditional statement? or does the function generically return a boolean state and that particular condition is one among many?

Comment (Ryex) [reply launcher/FileIgnoreProxy.cpp:283]: in this case I feel it's more of the latter so the existing way it's written is correct imo.

**Review by Ryex — APPROVED** [review]
