### PR TITLE
fix world size uninitialized memory and UI refresh signal

### LINKED ISSUE #4737: World size says 76Gib until resizing the corresponding column
### Operating System

_No response_

### Version of Prism Launcher

Prism Launcher 10.0.0 to 10.0.2 (tested on all 3)

### Version of Qt

Qt 6.10.1

### Description of bug

When opening the "Edit Instance" menu and selecting "Worlds", the "Size" column always says "76 GiB" until you resize this column.

Before resizing:
Image

After resizing:
Image

### Steps to reproduce

- Edit instance > Worlds

### Suspected cause

_No response_

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by qaptivator**
fixes #4737

to prevent arbitrary values in m_size we force it to be 0 in the World constructor, and fixed the view notifying issue.
`index(row, column = 0)` also takes a column value, so for `loadWorldsAsync` i had to specify it as `index(row, SizeColumn);`

to prevent ambiguity i also updated `index()` at `resetIcon`. that worked before without specifying column because the icon sat in the first column, so it worked fine. then whoever added the size column didn't know about this quirk so it didn't properly update. although i still don't know how or why for some instances this worked fine.

### CODE REVIEW

File: launcher/minecraft/World.cpp [hunk 1]
```diff
@@ -212,6 +212,7 @@ bool putLevelDatDataToFS(const QFileInfo& file, QByteArray& data)
 }
 
 World::World(const QFileInfo& file)
+    : m_size(0), m_randomSeed(0), m_isValid(false)
```
Comment (Octol1ttle) [inline launcher/minecraft/World.cpp]: https://github.com/PrismLauncher/PrismLauncher/blob/4872ec634ca5da054c93dad9a2f5a05885955f9a/launcher/minecraft/World.h#L90-L93

**Comment by qaptivator** [comment]
signed off properly

**Review by Octol1ttle — CHANGES_REQUESTED** [review]

File: launcher/minecraft/World.cpp (hunk 1 above)
Comment (qaptivator) [reply launcher/minecraft/World.cpp]: removed redundancy

**Review by Trial97 — APPROVED** [review]

File: launcher/minecraft/World.cpp (hunk 1 above)
Comment (qaptivator) [reply launcher/minecraft/World.cpp]: can you approve the changes please?

**Review by Ryex — APPROVED** [review]

**Comment by qaptivator** [comment]
huh, i wonder why the build for aarch64-linux failed. others worked just fine and in my last PR all builds worked alright.

**Comment by Ryex** [comment]
> huh, i wonder why the build for aarch64-linux failed. others worked just fine and in my last PR all builds worked alright.

don't worry about it too much. it's a test that faiks sometimes on aarch64 or mingw buulds. we still can't figure out why because we can never reproduce the cause.
