### PR TITLE
Fix linux non portable update

### LINKED ISSUE #2586: Autoupdater does not work on Linux systems
### Role

I use Linux

### Suggestion

Fix autoupdater

### Benefit

Just makes updating easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

```
[pid 34208] 01:07:12 execve("/tmp/PrismLauncher-Linux-Qt5-8.4.tar.gz", ["/tmp/PrismLauncher-Linux-Qt5-8.4"...], 0x7fff7c096ac8 /* 63 vars */ <unfinished ...>
[pid 34207] 01:07:12 +++ exited with 1 +++
[pid 34178] 01:07:12 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=34207, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
[pid 34208] 01:07:12 <... execve resumed>) = -1 ENOEXEC (Exec format error)
```
Running the autoupdater on Linux systems tries to execute the tar.gz archive as a binary. That obviously doesn't work. Maybe some code should be added to properly extract the archive into the directory the binary was executed from?

Looks like modifying this line could resolve the issue:
https://github.com/PrismLauncher/PrismLauncher/blob/196b2b5a3ed20dc4a23f4c2d62e1f46e886aba6a/launcher/updater/prismupdater/PrismUpdater.cpp#L1023

I just tested 8.3 portable version and it works fine there. Not sure why running the non-portable version would be any different, except for the line linked above.

### PR DESCRIPTION
**Pull request by Ryex**
Fix #2586
non portable linux updates technically works via a `.tar.gz` just like the portable version would even if not generally a good idea.

We probably want some sort of way to flag that the updater should be disabled if some packager is reusing our binary builds, that can be another PR though.

### CODE REVIEW

**Review by Trial97 — APPROVED** [review]

**Comment by Trial97** [comment]
If you rebase on latest develop the clang format should be fixed

File: launcher/updater/prismupdater/PrismUpdater.cpp [hunk 1]
```diff
@@ -788,6 +787,10 @@ QList<GitHubReleaseAsset> PrismUpdaterApp::validReleaseArtifacts(const GitHubRel
     if (BuildConfig.BUILD_ARTIFACT.isEmpty())
         qWarning() << "Build platform is not set!";
     for (auto asset : release.assets) {
+        if (asset.name.endsWith("zsync")) {
```
Comment (TheKodeToad) [inline launcher/updater/prismupdater/PrismUpdater.cpp]:
```suggestion
        if (asset.name.endsWith(".zsync")) {
```
?

**Comment by Ryex** [comment]
> If you rebase on latest develop the clang format should be fixed

... dam it now I have to force my clang-format version back :P

**Review by TayouVR — APPROVED** [review]

**Comment by DioEgizio** [comment]
We dropped this builds in 9.0 anyways...
