### PR TITLE
Fix crash when selecting same mod from different providers

### LINKED ISSUE #1028: Crash(with debug) when selectig same  mod on different providers
### Operating System

_No response_

### Version of Prism Launcher

Prism launcher 7.0-develop
Commit: 8dc3267925537d58a1e9418863b78e4cc55bd1c1

### Version of Qt

Qt 6.4.3

### Description of bug

When selecting the same mod over different providers the application will crash.

### Steps to reproduce

- build the latest develop`` using the debug information:`cmake -S . -B build -G Ninja -DCMAKE_INSTALL_PREFIX="/usr" -DENABLE_LTO=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug;cmake --build build`
- start the build application
- create a new instance with forge/fabric installed
- edit that instance and navigate to the mods tab
- click on the `Download mods` button
- select from modrinth a mod (e.g. `Fabric API`); the version doesn't matter
- navigate on curseforge and select the same mod(they need to have the same name)

### Suspected cause

The application tries to deselect a non-existent version on the selected mod.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
Fixes #1028

### CODE REVIEW

**Review by Scrumplex — COMMENTED** [review]
Changes look okay. Need to test and reproduce the original issue though

**Comment by Trial97** [comment]
If it helps this is the log from my other PR: https://github.com/PrismLauncher/PrismLauncher/pull/986#issuecomment-1517935920 credits @DioEgizio

**Comment by Trial97** [comment]
Let me convert it back to draft; found another bug regarding mod selection

File: launcher/ui/dialogs/ResourceDownloadDialog.cpp [hunk 1]
```diff
@@ -155,24 +159,10 @@ void ResourceDownloadDialog::addResource(ModPlatform::IndexedPack& pack, ModPlat
...
-    if (auto selected_task_it = m_selected.find(pack.name); selected_task_it != m_selected.end()) {
-        auto selected_task = *selected_task_it;
-        auto old_version_id = selected_task->getVersionID();
-
-        // If the new and old version IDs don't match, search for the old one and deselect it.
-        if (ver.fileId != old_version_id)
-            getVersionWithID(pack, old_version_id).is_currently_selected = false;
-    }
+    dynamic_cast<ResourcePage*>(m_container->getPage(Modrinth::id()))->removeResourceFromPage(pack.name);
+    dynamic_cast<ResourcePage*>(m_container->getPage(Flame::id()))->removeResourceFromPage(pack.name);
```
Comment (flowln) [inline launcher/ui/dialogs/ResourceDownloadDialog.cpp]:
```suggestion
    static_cast<ResourcePage*>(m_container->getPage(Modrinth::id()))->removeResourceFromPage(pack.name);
    static_cast<ResourcePage*>(m_container->getPage(Flame::id()))->removeResourceFromPage(pack.name);
```

, though i'd suggest iterating over all the pages in `m_container`, so that this doesn't need to change when adding a new page in the future.

File: launcher/ui/pages/modplatform/ModModel.cpp [hunk 2]
```diff
@@ -6,12 +6,23 @@
...
 
 namespace ResourceDownload {
 
-ModModel::ModModel(BaseInstance const& base_inst, ResourceAPI* api) : ResourceModel(api), m_base_instance(base_inst) {}
+ModModel::ModModel(BaseInstance const& base_inst, ResourceAPI* api) : ResourceModel(api), m_base_instance(base_inst)
+{
+    auto folder = static_cast<MinecraftInstance const&>(m_base_instance).loaderModList();
+    for (auto mod : folder->allMods()) {
+        auto meta = mod->metadata();
+        ModPlatform::IndexedPack pack{ meta->project_id, meta->provider, meta->name, meta->slug };
```
Comment (flowln) [inline launcher/ui/pages/modplatform/ModModel.cpp]: not all mods have metadata, in which cases `meta` is `nullptr`, and this line segfaults.

File: launcher/ui/pages/modplatform/ResourceModel.cpp [hunk 3]
```diff
@@ -441,4 +457,51 @@ void ResourceModel::infoRequestSucceeded(QJsonDocument& doc, ModPlatform::Indexe
...
+                if (!pred(*it)) {
+                    *dest = std::move(*it);
+                    ++dest;
+                }
+            }
+
+            result = std::distance(dest, e);
+            m_selected.erase(dest, e);
+        }
+    }
```
Comment (flowln) [inline launcher/ui/pages/modplatform/ResourceModel.cpp]: a simple for loop removing the unwanted elements would be more legible, no need to take the qt code.

**Review by flowln — COMMENTED** [review]
instead of duplicating a list of selected mods (which already exists on ResourceDownloadDialog), i think it would make more sense to differentiate between selected mods for download and already downloaded mods in `IndexedPack` itself. Then, for some effects, like the selected indication, both types would have visual impact, whereas only the selected mods for download would show up in the confirmation page, for instance.

Note, however, that not only are you fixing a bug in this PR, you're also making a behavioral change in the downloader, by marking the already downloaded mods as selected. While I don't personally favor this feature, i'm not against it, but I think you should be more clear in what you're aiming to achieve in your PR.

Also, I'd like to ask you to please be careful to only clang-format the portions of the file you have actually touched, since it currently leaves a lot of noise when reviewing, due to the formatting changes :p

File: launcher/ui/dialogs/ResourceDownloadDialog.cpp (hunk 1 above)
Comment (Trial97) [reply launcher/ui/dialogs/ResourceDownloadDialog.cpp]: I added a method on m_container to get all pages and iterate over it.

File: launcher/ui/pages/modplatform/ModModel.cpp (hunk 2 above)
Comment (Trial97) [reply launcher/ui/pages/modplatform/ModModel.cpp]: I will move this to other PR( to make sure I keep this one clean)

File: launcher/ui/pages/modplatform/ResourceModel.cpp (hunk 3 above)
Comment (Trial97) [reply launcher/ui/pages/modplatform/ResourceModel.cpp]: Done this with erase instead.

**Comment by Trial97** [comment]
- [x] need to remove the extra list of selected mods
- [x] removed the extra code regarding the downloaded mods

Regarding the clang-format, I let my editor(vscode) handle all the formatting right now.
In order to reduce the noise regarding the formating: 
- should I open an extra PR preceding each of my PRs with only the modified files formatted(no code change; so first accept the format PR then the actual PR) 
- or should I open a separate PR that adds a GitHub action that formats all the code using clang-format(this will be a massive PR as it will format all the files, and may create some conflicts with existing PRs; but after this initial PR is accepted this will ensure that all code is formatted)

**Comment by flowln** [comment]
> * should I open an extra PR preceding each of my PRs with only the modified files formatted(no code change; so first accept the format PR then the actual PR)
> 
> * or should I open a separate PR that adds a GitHub action that formats all the code using clang-format(this will be a massive PR as it will format all the files, and may create some conflicts with existing PRs; but after this initial PR is accepted this will ensure that all code is formatted)


neither, you can use range-formatting to format only the selected lines, so you only format the lines you change (though idk if vscode has that option), or you can `git add -p` to only put the changes that actually matter in the commit instead of whole files. You also don't have to revert the formattings you have already done, just be mindful of them in the future is  all i'm asking :slightly_smiling_face: 

also, you don't have to cherry-pick commits from one branch to another if they aren't dependent. When one of them gets merged into develop, you can then merge (or rebase) develop into your other branch (e.g. you don't have to cherry-pick the commits from this branch into your other PR's branch)

**Comment by Trial97** [comment]
Removed the need for an extra list in ResourceDownloadDialog, ~just needs some time to test the new implementation~(I tested it )

**Review by DioEgizio — APPROVED** [review]

**Review by Ryex — APPROVED** [review]
LGTM

**Review by flowln — COMMENTED** [review]
https://github.com/PrismLauncher/PrismLauncher/assets/9145768/415d202e-f34c-4483-a862-6257fd2e3ecc

This doesn't look quite right o.O
Qt 6.5.0, if it helps.

**Comment by Trial97** [comment]
The repaint issue should be addressed.

**Comment by Trial97** [comment]
Regarding the failing test, as I do not have a Windows machine, I cannot reproduce it.
Also, the same codebase was used in another PR open here and all the tests passed.

**Comment by Ryex** [comment]
> Regarding the failing test, as I do not have a Windows machine, I cannot reproduce it. Also, the same codebase was used in another PR open here and all the tests passed.

That Task test is unfortunately a bit wonky and randomly fails in the CI. code should be fine.

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
@flowln please take a look again, once you find the time :D

**Review by flowln — APPROVED** [review]
I couldn't find any issues this time. Great job! :D

~please stop formatting everything in the documents please~

**Comment by flowln** [comment]
I'll squash since the merge commits will make the history annoying to read in the future.
