### PR TITLE
Handle partial lines in LoggedProcess

### LINKED ISSUE #930: Log upload: Data Integrity Issue
### Operating System

Windows 11

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt 6.4.0 (Windows, so this must be bundled)

### Description of bug

When logs are uploaded to mclo.gs from within Prism, it seems that the data uploaded isn't entirely correct - in my case, this results in an extra line of broken data within Quilt Loader's mods table. Below, you can see a screenshot of VS Code with word wrap disabled, showing the difference between three methods of viewing the file - directly on mclo.gs as uploaded by Prism, directly in the file on disk, and within Prism's own log viewer.

This does not happen if I upload the file to mclo.gs myself.

image

* [The log file I'm working with](https://github.com/PrismLauncher/PrismLauncher/files/10958508/latest.log)
* [The log file Prism uploaded](https://mclo.gs/xdcIjE6)

This problem breaks Cozy's new log parser, as the data is broken in a way that my parser can't reasonably account for.

### Steps to reproduce

* Start a modpack making use of a recent version of Quilt Loader, and a large number of mods
* Close the game and upload the logs via Prism's "upload logs" button
* Compare the mods table in the logs that were uploaded to mclo.gs with the table in the latest.log file and in Prism's own log viewer

### Suspected cause

When copying logs from Prism's viewer into VS Code, it complains that Prism is adding strange line endings. It may be worth double-checking how Prism is sanitizing the line endings in the logs, if it is doing so at all.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #930

That explains the code about leftover lines we removed before :thinking: 

I am not sure about my FIXME comment here, though. Should we just call reprocess with an empty buffer when the process exits, just to make sure we got all lines?

### CODE REVIEW

File: launcher/LoggedProcess.cpp [hunk 1]
```diff
@@ -60,14 +61,26 @@ LoggedProcess::~LoggedProcess()
...
+    }
+
 #if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
     auto lines = str.remove(QChar::CarriageReturn).split(QChar::LineFeed, QString::SkipEmptyParts);
 #else
     auto lines = str.remove(QChar::CarriageReturn).split(QChar::LineFeed, Qt::SkipEmptyParts);
 #endif
+
+    if (!str.endsWith(QChar::LineFeed))
+        m_leftover_line = lines.takeLast();
```
Comment (flowln) [inline launcher/LoggedProcess.cpp]:
```suggestion
static QString s_leftover_line;

QStringList reprocess(const QByteArray& data, QTextDecoder& decoder)
{
    auto str = decoder.toUnicode(data);

    // FIXME: Flush this out when process exits
    if (!s_leftover_line.isEmpty()) {
        str.prepend(s_leftover_line);
        s_leftover_line = "";
    }

#if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
    auto lines = str.remove(QChar::CarriageReturn).split(QChar::LineFeed, QString::SkipEmptyParts);
#else
    auto lines = str.remove(QChar::CarriageReturn).split(QChar::LineFeed, Qt::SkipEmptyParts);
#endif

    if (!str.endsWith(QChar::LineFeed))
        s_leftover_line = lines.takeLast();
```

i was very eepy

**Review by flowln — COMMENTED** [review]
for the FIXME, i suppose there shouldn't be any normal case where the leftover is non-empty after the process exits, since the process already flushes the stdout every time.

The only reason why we're having this issue rn is because someone is throwing so much data to the stdout at once that the process can't flush in a single go, so you have partitioned calls. But when the process finishes, it either finishes cleanly and flushes stdout anyway, or it dies in a bad manner and the stdout is possibly left with some stuff which might not even compose entire codepoints - in which case we will just print some garbled mess, and it possibly won't even go to `latest.log` anyway.

As for the solution presented here, it works for this case, but beware that, since it's a static variable taking care of it, having more than one process running at once (e.g. two instances running at the same time) can garble this fellow, although it's unlikely to happen. i originally made it a member variable, before realizing that reprocess is a standalone function, so that's why i made it static instead. it could make sense to put both inside LoggedProcess though

and thanks for adding me as co-author :relaxed:

File: launcher/LoggedProcess.cpp (hunk 1 above)
Comment (Scrumplex) [reply launcher/LoggedProcess.cpp]: I made both the function and the QString members of LoggedProcess now.

**Review by flowln — APPROVED** [review]

**Review by DioEgizio — APPROVED** [review]
