### PR TITLE
fix FTBA instance loading

### LINKED ISSUE #4346: FTBA Import broken
### Operating System

Linux

### Version of Prism Launcher

latest git

### Version of Qt

6.10.0-3

### Description of bug

new FTBA instances can't be loaded

getting `275.318 D | Couldn't load ftb version json:  "FTB_APP version JSON file: Error parsing JSON: object is missing after a comma"`

### Steps to reproduce

Install a new pack from FTB

### Suspected cause

FTBA recently updated how they store modloader info, moved it from `version.json` -> `instance.json`

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Bryntet**
This fixes #4346

### CODE REVIEW

File: launcher/modplatform/import_ftb/PackHelpers.cpp [hunk 1]
```diff
@@ -74,17 +74,49 @@ Modpack parseDirectory(QString path)
...
+    auto iconFile = QFileInfo(FS::PathCombine(path, "folder.jpg"));
+    if (iconFile.exists() && iconFile.isFile()) {
+        modpack.icon = QIcon(iconFile.absoluteFilePath());
+    } else {  // the logo is a file that the first bit denotes the image tipe followed by the actual image data
+        modpack.icon = loadFTBIcon(FS::PathCombine(path, ".ftbapp", "logo"));
+    }
+    return modpack;
+}
 
+void legacyInstanceParsing(QString path, std::optional<ModPlatform::ModLoaderType>* loaderType, QString* loaderVersion)
```
Comment (Trial97) [inline launcher/modplatform/import_ftb/PackHelpers.cpp:111]: Wouldn't it be better to just use references, instead of pointers? 
```suggestion
void legacyInstanceParsing(QString path, std::optional<ModPlatform::ModLoaderType>& loaderType, QString& loaderVersion)
```

Comment (TheKodeToad) [reply launcher/modplatform/import_ftb/PackHelpers.cpp:111]: A mutable reference IMO isn't the best idea. Passing a value into a function you wouldn't necessarily expect it to be able to modify it.

**Review by Trial97 — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Comment by TayouVR** [comment]
I think this needs a rebase since #4330 is merged.

**Review by Ryex — APPROVED** [review]

**Review by DioEgizio — APPROVED** [review]

**Review by Trial97 — APPROVED** [review]
