### PR TITLE
Trim unexpected info from pack.mcmeta

### LINKED ISSUE #4331: Resource Pack is Installed but doesn't show listed on the edit screen list
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.4

### Version of Qt

Qt 6.8.2

### Description of bug

When adding resource packs to my Minecraft 1.21.8 instance through Prism Launcher "Download Packs" option, I noticed that one specific pack wasn't showing ([Enchanted Books: Re-covered](https://modrinth.com/mod/enchanted-books-re-covered)). I even tried install it again, thinking maybe I had deselected it. But no, still no show.

Image

But to my surprise, opening "resourcepacks" directory of the instance showed the zip file for it: Re-covered.zip (Image below).
Image

Tested in-game and the RP shows perfectly on the list and works fine too.

### Steps to reproduce

* Create a Minecraft Instance (1.21.8 for example).
* Run once just to create all the folders.
* Click on Edit> Resource Packs> Download packs.
* Search for Re-covered or Enchanted Books: Re-covered, and select the mod by user carl_classic.
* Select resource pack for download> Review and Confirm> OK.

### Suspected cause

I'm not knowledgeable of any of PrismLauncher's code or technical implementations. So, probably my guess isn't of much help. But I do believe this might be just a bug in the UI rendering of this item. Maybe while trying to parse/ retrieve some of the infos from the pack like name, image or pack format, one of those is in an unsupported format or too long (for the name string, for example). But again, what do I know..
I'm more then fine to help you with more info, specially if you can't reproduce the behaviour.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by dsch7705**
Fixes #4331 

This applies the same fix implemented in 5ebd386797bf7c65da079959d32b89cd3783eda0 to DataPackUtils::processMCMeta.

### CODE REVIEW

**Review by DioEgizio — APPROVED** [review]

**Review by Trial97 — APPROVED** [review]

File: launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp [hunk 1]
```diff
@@ -168,10 +168,20 @@ bool processZIP(DataPack* pack, ProcessingLevel level)
 // https://minecraft.wiki/w/Tutorials/Creating_a_resource_pack#Formatting_pack.mcmeta
 bool processMCMeta(DataPack* pack, QByteArray&& raw_data)
 {
+    QJsonParseError parse_error;
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp:171]: In case it's needed in more places probably best to create a helper in Json.h? (Json::parseUpToError or something, also no need to make it throw a JsonException as that seems like a bad idea anyway since it's easy to forget to catch)

Comment (dsch7705) [reply launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp:171]: Should I update McClient::parseResponse to use the helper or save for another PR?

Comment (TheKodeToad) [reply launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp:171]: Best to update it in this PR *IMO*

**Review by Trial97 — APPROVED** [review]

**Review by Ryex — CHANGES_REQUESTED** [review]
id prefer if this was explicitly checking for `QJsonParseError::GarbageAtEnd`
instead of ignoring all json errors. the function could also potentially return the "garbage" by a QString out param

**Comment by dsch7705** [comment]
> id prefer if this was explicitly checking for `QJsonParseError::GarbageAtEnd` instead of ignoring all json errors.

Excellent point.

**Review by TheKodeToad — APPROVED** [review]

**Review by Ryex — APPROVED** [review]
