### PR TITLE
Fix import skin if path is empty

### LINKED ISSUE #2940: Canceling "Import File" in Skin Manager causes unnecessary error popup
### Operating System

_No response_

### Version of Prism Launcher

9.0-develop
image

### Version of Qt

6.7.3

### Description of bug

--

### Steps to reproduce

1. click import file
2. cancel

### Suspected cause

probably task failure being propagated i assume.

"Import user" on the other hand doesn't have any feedback when the input field is empty

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #2940

### CODE REVIEW

**Review by TayouVR — APPROVED** [review]

File: launcher/ui/dialogs/skins/SkinManageDialog.cpp [hunk 1]
```diff
@@ -139,6 +139,9 @@ void SkinManageDialog::on_fileBtn_clicked()
 {
     auto filter = QMimeDatabase().mimeTypeForName("image/png").filterString();
     QString raw_path = QFileDialog::getOpenFileName(this, tr("Select Skin Texture"), QString(), filter);
+    if (raw_path.isEmpty()) {
```
Comment (TheKodeToad) [inline launcher/ui/dialogs/skins/SkinManageDialog.cpp]:
```suggestion
    if (raw_path.isNull()) {
```
should be sufficient

**Review by Ryex — APPROVED** [review]
