### PR TITLE
fix ftb import for old packs

### LINKED ISSUE #4786: FTB Import doesn't add any modloader/imports incorrectly
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 10.0.2

### Version of Qt

Qt 6.10.1

### Description of bug

The FTB App import function seems to not include any sort of modloader, the instance as it is imported runs as vanilla Minecraft. I'm not sure exactly how importing works, but I figured it would come with the correct version of Forge already set up.

### Steps to reproduce

* Download an instance from the FTB App with the default directory
* Import it into Prism Launcher
* Attempt to run the instance or check the Version tab of the instance

### Suspected cause

FTB App Import didn't work at all for me in the last major release (9.4), so it could have just been overlooked for this long? Or maybe this is just how it's supposed to work? I dunno.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #4786

### CODE REVIEW

**Review by DioEgizio — APPROVED** [review]

File: launcher/modplatform/import_ftb/PackHelpers.cpp [hunk 1]
```diff
@@ -80,24 +81,29 @@ Modpack parseDirectory(QString path)
...
                 } else if (loader == "forge") {
                     modpack.loaderType = ModPlatform::Forge;
+                    modloaderInfoLoaded = true;
                 } else if (loader == "fabric") {
                     modpack.loaderType = ModPlatform::Fabric;
+                    modloaderInfoLoaded = true;
                 } else if (loader == "quilt") {
                     modpack.loaderType = ModPlatform::Quilt;
+                    modloaderInfoLoaded = true;
                 }
```
Comment (Octol1ttle) [inline launcher/modplatform/import_ftb/PackHelpers.cpp:92]: why not just check that `modpack.loaderType` isn't `nullopt`?

**Review by Octol1ttle — CHANGES_REQUESTED** [review]

**Review by Ryex — APPROVED** [review]

**Review by Octol1ttle — APPROVED** [review]
