### PR TITLE
Auth abort fixes

### LINKED ISSUE #3311: Couldn't Launch after 3 tries
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 9.2

### Version of Qt

Qt 6.7.3

### Description of bug

A frequent bug for me, when trying to launch it will say 'working....' and 'logging in with Microsoft account.', and not continue to open the game. clicking 'play offline' brings up a window 'It looks like we couldn't launch after 3 tries. Do you want to continue trying?'.

### Steps to reproduce

- open launcher
- click on instance and click launch
- game will fall to open after 3 tries

### Suspected cause

Unsure what could be causing it. There were a few resource packs that I dropped into the folder instead of downloading from the launcher. No idea if that would have an effect. a few of my packs are 'for older versions' but still work in game.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by TheKodeToad**
- Changed Play Offline button to say Abort... because that's what it actually does
- Avoid retrying if abort was explicitly used
- Reset the account to Unchecked on abort so it actually ends up being refreshed on launch (fixes the infamous infinite retry where it doesn't actually retry)

Does not entirely fix #3311 - the infinite hang is a qt bug (it seems) which is only fixed in a pretty new version :/

### CODE REVIEW

File: launcher/minecraft/auth/MinecraftAccount.cpp [hunk 1]
```diff
@@ -181,8 +181,10 @@ void MinecraftAccount::authFailed(QString reason)
             data.validity_ = Validity::None;
             emit changed();
         } break;
+        case AccountTaskState::STATE_WORKING: {
+            data.accountState = AccountState::Unchecked;
+        } break;
         case AccountTaskState::STATE_CREATED:
```
Comment (Trial97) [inline launcher/minecraft/auth/MinecraftAccount.cpp:187]: Wouldn't created fall under Same unchecked category?

File: launcher/LaunchController.cpp [hunk 2]
```diff
@@ -296,11 +296,21 @@ void LaunchController::login()
...
+                progDialog.setSkipButton(true, tr("Abort"));
+
                 auto task = accountToCheck->currentTask();
+
+                bool aborted = false;
+                auto abortListener = connect(task.get(), &Task::aborted, [&aborted] { aborted = true; });
+
                 progDialog.execWithTask(task.get());
+
+                disconnect(abortListener);
```
Comment (Trial97) [inline launcher/LaunchController.cpp]: You do not need the signal stuff just the task status or is aborted function

File: launcher/minecraft/auth/MinecraftAccount.cpp (hunk 1 above)
Comment (TheKodeToad) [reply launcher/minecraft/auth/MinecraftAccount.cpp:187]: The other cases are not reachable - this accidentally was not accounted for!

File: launcher/LaunchController.cpp (hunk 2 above)
Comment (TheKodeToad) [reply launcher/LaunchController.cpp]: both wrong but thank you
(getState() should actually work)

**Comment by TheKodeToad** [comment]
Seems aborting is extremely inconsistent...

**Review by Trial97 — APPROVED** [review]

**Comment by TheKodeToad** [comment]
Well - I don't think I've actually introduced any problems! I hope...

**Review by Ryex — APPROVED** [review]
