### PR TITLE
Track dependencies in Mods page

### LINKED ISSUE #280: Disabling lib gray out mods that uses that package
### Role

modded MC

### Suggestion

In mods section, disabling lib mod should gray out mods that depends on it

### Benefit

Reduce launcher errors

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I've started playing around with mods. A some mods have their own specific libs that they depend on. After removing certain mod, I have some libs in leftover that I'd like to remove and/or disable (why load them if they aren't being used?)
If I disable some lib, It should gray out text for mods that depends on them. E.g. disabling `Fabric Api` would disable most of the mods as most of them depends on it. Now I'm not sure you can distinguish libs from regular mods, but I believe it can be generated when getting mod metadata, and saving dependencies as a separate config file.

This is in some way related to #154 and in some minor way related to #116 and #37 (relationship with libs and dependencies)

I believe we should be able to get all of this data from the API

### LINKED ISSUE #1844: Identify extraneous library mods
### Role

I make modpacks, where I am often adding and removing mods

### Suggestion

SInce you can now identify dependencies of mods, it would be nice to have a way to see mods that are not depended on by any others for the purpose of removing extraneous library mods.

### Benefit

For the purpose of removing extraneous library mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### LINKED ISSUE #2628: Automatic Dependency Handling for Mod Enabling/Disabling
### Role

I Play modded Minecraft and am a Modpack Maker

### Suggestion

Implement a feature that automatically disables all dependent mods when a base mod or library is disabled. Similarly, automatically re-enable the base mod or library if any of its dependent mods are re-enabled.

### Benefit

This feature would be incredibly valuable for modpack creators, serving as a significant time-saving optimization tool. By automating the handling of mod dependencies, it would streamline the process of troubleshooting crashes and conflicts, particularly in large modpacks with numerous dependencies. I believe no other launcher currently offers this functionality, which would make Prism Launcher the go-to choice for modpack creation.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As a modpack creator, managing mod dependencies manually can be cumbersome and error-prone. When disabling mods to identify conflicts or crashes, accidentally disabling a base mod or library can lead to further crashes, complicating the troubleshooting process. By automating the disabling and enabling of dependent mods, Prism Launcher can provide a smoother and more efficient experience for both modpack creators and players.

For example, if a user disables Architectury, the launcher should automatically disable all mods that require Architectury to function. If any of those dependent mods are re-enabled, Architectury should also be automatically re-enabled.

Considering that the launcher already uses metadata to determine and download necessary dependencies when selecting mods, it seems feasible to extend this functionality to the disabling and re-enabling process. While I'm not a developer, I assume leveraging this existing metadata should make implementing this feature relatively straightforward.

This feature would save significant time and reduce frustration, making Prism Launcher even more user-friendly and powerful for managing modded Minecraft.

### PR DESCRIPTION
**Pull request by Trial97**
To do:
- [x] get dependencies from mod
- [x] get dependencies from provider data(save them in packwiz)
- [x] add columns to sort the mods based on the number of dependencies and the number of required by
- [x] auto disable/enable dependencies
- [ ] a way to visualize the dependencies for each mod

This is more like a personal build, but I want to have a place to track it.
Stuff that blocks this PR(aka known issues): 
- Because the mod parsing was updated to fetch more information, the mods page loads slower 
- This doesn't tell you if you are missing stuff: use the `Verify Dependencies` button to fetch the deps from providers (some loaders do put libraries as dependency information, and I can't determine if it is a mod that needs to be installed or included in the jar)
- There are edge cases: AE2 QoL Recipes doesn't report that AE2 is a dependency in the mod file, so if you download AE2 from CF and AE2 QoL Recipes from Modrinth, the relation may not be shown (as there is no link between the CF project ID and Modrinth); other example what falls here is Iris and Sodium
- Incompatible mods will not be tackled in this PR

Other than that, feel free to test it out.

fixes #1844
fixes #280
fixes #2628

### CODE REVIEW

**Comment by aurora-1-2-3** [comment]
Any update on whether this is going to be merged?

Also trial, is there a way to try your builds early? I really need the new features and am eager to get started.

**Comment by Mick235711** [comment]
> Also trial, is there a way to try your builds early? I really need the new features and am eager to get started.

Yes, navigate to checks (either by the "successful checks" dropdown above the comment section, or by selecting the green checkmark before each commit number), choose one of "Build" check, in its page select Summary from the left pane, and scroll all the way to the bottom you can see a list of generated builds from this PR.

**Comment by aurora-1-2-3** [comment]
thank you so much, ima test all of their builds

File: launcher/minecraft/mod/ModFolderModel.cpp [hunk 1]
```diff
@@ -240,3 +262,145 @@ void ModFolderModel::onParseSucceeded(int ticket, QString mod_id)
...
+    if (action == EnableAction::TOGGLE) {
+        if (indexedMods.length() != 1) {
+            return {};  // not sure how to handle a bunch of rows that are toggled(not even sure it is posible)
+        }
+        action = indexedMods.first()->enabled() ? EnableAction::DISABLE : EnableAction::ENABLE;
+    }
+    auto findById = [](QList<Mod*> mods, QString id) -> Mod* {
+        auto found = std::find_if(mods.begin(), mods.end(), [id](Mod* m) { return m->mod_id() == id; });
+        return found != mods.end() ? *found : nullptr;
+    };
```
Comment (getchoo) [inline launcher/minecraft/mod/ModFolderModel.cpp]: This should probably just be made into a function, as it's copy-pasted from above

File: launcher/ui/pages/instance/ModFolderPage.cpp [hunk 2]
```diff
@@ -133,7 +134,22 @@ void ModFolderPage::removeItems(const QItemSelection& selection)
         if (response != QMessageBox::Yes)
             return;
     }
-    m_model->deleteResources(selection.indexes());
+
+    auto indexes = selection.indexes();
+    auto affected = m_model->getAffectedMods(indexes, EnableAction::DISABLE);
+    if (!affected.isEmpty()) {
+        auto response = CustomMessageBox::selectable(this, tr("Confirm Disable"),
+                                                     tr("The mods you are tring to remove are required by %1 mods.\n"
```
Comment (getchoo) [inline launcher/ui/pages/instance/ModFolderPage.cpp]:
```suggestion
                                                     tr("The mods you are tring to disable are required by %1 mods.\n"
```

File: launcher/ui/widgets/InfoFrame.cpp
Comment (getchoo) [inline launcher/ui/widgets/InfoFrame.cpp:1]: Really wanted to get both of these boxes to show at the same time, but I actually couldn't find a mod that had its own (correctly defined) dependencies that was depended on by others lol

**Review by getchoo — COMMENTED** [review]
LGTM otheriwse

I think it'd be cool to flesh the current requirements/required by boxes into a full properties-esc dialog, but that'd definitely need some features (like idk, file size, more author info, blah blah) and can be done later

Thanks!

File: launcher/ui/widgets/InfoFrame.cpp
Comment (Trial97) [reply launcher/ui/widgets/InfoFrame.cpp:1]: image
occultims

File: launcher/minecraft/mod/ModFolderModel.cpp [hunk 3]
```diff
@@ -48,25 +48,34 @@
...
-                                   "Minecraft Versions", "Release Type" });
-    m_column_names_translated = QStringList({ tr("Enable"), tr("Image"), tr("Name"), tr("Version"), tr("Last Modified"), tr("Provider"),
-                                              tr("Size"), tr("Side"), tr("Loaders"), tr("Minecraft Versions"), tr("Release Type") });
-    m_column_sort_keys = { SortType::ENABLED, SortType::NAME,        SortType::NAME,        SortType::VERSION,
-                           SortType::DATE,    SortType::PROVIDER,    SortType::SIZE,        SortType::SIDE,
-                           SortType::LOADERS, SortType::MC_VERSIONS, SortType::RELEASE_TYPE };
+                                   "Minecraft Versions", "Release Type", "Requires", "Required by" });
+    m_column_names_translated =
+        QStringList({ tr("Enable"), tr("Image"), tr("Name"), tr("Version"), tr("Last Modified"), tr("Provider"), tr("Size"), tr("Side"),
+                      tr("Loaders"), tr("Minecraft Versions"), tr("Release Type"), tr("Requires "), tr("Required by") });
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/ModFolderModel.cpp]:
```suggestion
                      tr("Loaders"), tr("Minecraft Versions"), tr("Release Type"), tr("Requires"), tr("Required By") });
```

File: launcher/minecraft/mod/ModFolderModel.cpp [hunk 4]
```diff
@@ -195,6 +213,10 @@ QVariant ModFolderModel::headerData(int section, [[maybe_unused]] Qt::Orientatio
                     return tr("The release type.");
                 case SizeColumn:
                     return tr("The size of the mod.");
+                case RequiredByColumn:
+                    return tr("Number of mods for what this is needed.");
+                case RequiresColumn:
+                    return tr("Number of mods that this requires.");
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/ModFolderModel.cpp]: I would prefer this:
```suggestion
                case RequiredByColumn:
                    return tr("For each mod, the number of other mods which depend on it.");
                case RequiresColumn:
                    return tr("For each mod, the number of other mods it depends on.");
```

Might be inconsistent but I want it to be easier to understand than time travel

File: launcher/minecraft/mod/ModFolderModel.h [hunk 5]
```diff
@@ -85,8 +90,20 @@ class ModFolderModel : public ResourceFolderModel {
...
+    QStringList requiresList(QString id);
+    QStringList requiredByList(QString id);
+
    private slots:
     void onParseSucceeded(int ticket, QString resource_id) override;
+    void onParseFinished();
+
+   private:
+    QHash<QString, QList<Mod*>> m_requiredBy;
+    QHash<QString, QList<Mod*>> m_requires;
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/ModFolderModel.h]: Can you not get away with doing this to eliminate duplicates?
```suggestion
    QHash<QString, QSet<Mod*>> m_requiredBy;
    QHash<QString, QSet<Mod*>> m_requires;
```

**Comment by TheKodeToad** [comment]
FYI it is possible to toggle many mods at once by pressing enter

**Comment by Trial97** [comment]
> FYI it is possible to toggle many mods at once by pressing enter

Can you please elaborate? What if it is possible to toggle many mods at once by pressing enter? Does the dependency stuff not work? Or what?

**Comment by TheKodeToad** [comment]
> // not sure how to handle a bunch of rows that are toggled(not even sure it is posible)

**Comment by Trial97** [comment]
This should have fixed it: if you try to do the toggle thing, this will prioritize the enabled mod(aka will ensure that when a mod is enabled, the deps are also enabled, regardless if the user wanted to disable the dep by toggle). When enabling/disabling individual mods, it will behave normally

File: launcher/minecraft/mod/tasks/LocalModParseTask.cpp [hunk 6]
```diff
@@ -62,6 +62,36 @@ ModDetails ReadMCModInfo(QByteArray contents)
...
+
+        if (firstObj.contains("requiredMods")) {
+            for (auto dep : firstObj.value("dependencies").toArray().toVariantList()) {
+                addDep(dep.toString());
+            }
+        } else if (firstObj.contains("dependencies")) {
+            for (auto dep : firstObj.value("dependencies").toArray().toVariantList()) {
+                addDep(dep.toString());
+            }
+        }
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/tasks/LocalModParseTask.cpp:92]: nitpick: just use json api directly
but you did also accidentally write dependencies in the first case :P
```suggestion
        if (firstObj.contains("requiredMods")) {
            for (auto dep : firstObj.value("requiredMods").toArray()) {
                addDep(dep.toString());
            }
        } else if (firstObj.contains("dependencies")) {
            for (auto dep : firstObj.value("dependencies").toArray()) {
                addDep(dep.toString());
            }
        }
```

File: launcher/minecraft/mod/tasks/LocalModParseTask.cpp [hunk 7]
```diff
@@ -199,6 +229,42 @@ ModDetails ReadMCModTOML(QByteArray contents)
...
+                    if (modId != "forge" && modId != "neoforge" && modId != "minecraft") {
+                        if (dep_table->contains("type") && (dep_table->get("type"))->value_or<std::string>("") == "required") {
+                            details.dependencies.append(QString::fromStdString(modId));
+                        } else if (dep_table->contains("mandatory") && (dep_table->get("mandatory"))->value_or(false)) {
+                            details.dependencies.append(QString::fromStdString(modId));
+                        }
+                    }
+                }
+            }
+        }
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: Oops I guess I reworked a whole function again...
Better null safety and less nesting
```suggestion
        if (!dependencies) {
            return;
        }
        for (auto& dep : *dependencies) {
            auto dep_table = dep.as_table();
            if (!dep_table) {
               continue;
            }

            auto modId = (*dep_table)["modId"].as_string();
            if (!modId) {
                continue;
            }
            if (modId->get() == "forge" || modId->get() == "neoforge" || modId->get() == "minecraft") {
                continue;
            }

            if (auto type = (*dep_table)["type"].as_string()) { // NeoForge format
                if (type->get() != "required") {
                    continue;
                }
            } else if (auto mandatory = (*dep_table)["mandatory"]) {
                if (!mandatory->get()) {
                    continue;
                }
            } else {
                continue;
            }

            details.dependencies.append(QString::fromStdString(modId->get()));
        }
```

Comment (Trial97) [reply launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: As much as I love the go approach here, I think it would just be better to keep a relatively smaller number of continue: use it in moderation
I applied this suggestion partially, as you would see: I consider the 3 continue at the end being a bit too much

Comment (TheKodeToad) [reply launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: No null safety though for modID - it will segfault

Comment (TheKodeToad) [reply launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: I also prefer the [key].as_whatever() approach as it is null safe without needing to check .contains 
(it's also used elsewhere in the same function)

Comment (TheKodeToad) [reply launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: Also given the length of 
`details.dependencies.append(QString::fromStdString(modId->get()));`
it seems bad to duplicate it for every case

Comment (Trial97) [reply launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: Ok now it should address all the comments but without the extra continue

File: launcher/minecraft/mod/ModFolderModel.cpp (hunk 3 above)
Comment (TheKodeToad) [reply launcher/minecraft/mod/ModFolderModel.cpp]: Not resolved

File: launcher/minecraft/mod/ModFolderModel.cpp (hunk 4 above)
Comment (TheKodeToad) [reply launcher/minecraft/mod/ModFolderModel.cpp]: Also unresolved.

**Review by TayouVR — APPROVED** [review]
didn't fully analyze code, but tested it out. Generally I think its pretty decent.

Some small feedback points. (not blocking)
- the dependency panels replacing the name and description bugs me a little, especially since I usually have the window fullscreen and there is more than enough space. I think the layouting could use some tweaking
- when enabling a mod its dependencies get enabled too. I sometimes enable a mod, try to update it or start the game, it doesn't work (outdated mod, incompatible with another, etc.). Now when I disable it its dependencies stay enabled. Not sure if theres a good way to handle that tbh, so I wouldn't count this as a blocker. But I'm sure other people will complain about it later on as well.

**Comment by Trial97** [comment]
- for the first one: yes, sure, there may be a better way to display them, but increasing the size of the panel at the bottom of the list seems like it takes a bit too much space. Yes, on a bigger screen, it may look decent, but we should consider that smaller resolutions exist(let's not make the experience worse for some users who may not have bigger resolutions). I'm open to suggestions and discussions on how best to display them. 
- on second: there is no way the game would start if the dependencies are disabled. So if you update the mod and have deps, you would want the deps to be enabled; otherwise, the game will not start. And the launcher should try to ensure that all the deps are enabled. A possible fix would be just to make the dependency toggle configurable in some way

Thanks for considering my PR.

**Review by TheKodeToad — CHANGES_REQUESTED** [review]
- Disabling is no longer an easily reversible action. It should have confirmation if another mod is being disabled. (edit: same with enabling)
- What's up with the ux here lol
https://github.com/user-attachments/assets/a80d38ef-5bb5-4dbf-aeb6-0f20cc77523b
*When the arrow points east, the description is shown. When it points west, the dependencies are shown. Click on the arrow to rotate it by 180°.*
I don't think we should try to cram so much info into this pane, or at least use tabs (but the horizontal layout doesn't work well for this)
Like getchoo says:
> I think it'd be cool to flesh the current requirements/required by boxes into a full properties-esc dialog

Probably best to leave this out until this is added

**Comment by Trial97** [comment]
- yes it is not reversible, but  without enabling/disabling the  mods, the instance would not start
- I did not use tabs for the pane, so I do not take 20px of screen with just the tab name(I tried to make it so it doesn't use more space than it already does). I still do not like the idea of separating it into a different window, as I want users to go through the mods and see the deps without needing to click each mod, then a button. I can change the button name to represent the action better. Can we discuss alternatives other than opening a new modal to see the deps/required by?

**Comment by TheKodeToad** [comment]
> yes it is not reversible, but without enabling/disabling the mods, the instance would not start

Yeah but there should still be a confirmation for toggling a mod if there's a chain reaction. If the user says no disable no mods, if yes disable all mods

**Comment by TheKodeToad** [comment]
> I did not use tabs for the pane, so I do not take 20px of screen with just the tab name(I tried to make it so it doesn't use more space than it already does). I still do not like the idea of separating it into a different window, as I want users to go through the mods and see the deps without needing to click each mod, then a button. I can change the button name to represent the action better. Can we discuss alternatives other than opening a new modal to see the deps/required by?

How about showing a list on hover?
Edit: this implementation also does appear to make the box a lot larger

**Comment by TheKodeToad** [comment]
Also the counting breaks really easily lol

[Screencast_20251015_121214.webm](https://github.com/user-attachments/assets/6b85202c-668e-41ce-b688-fd3530631eb3)

**Comment by Trial97** [comment]
> Yeah but there should still be a confirmation for toggling a mod if there's a chain reaction. If the user says no disable no mods, if yes disable all mods

Added the mentioned dialog, has yes(will automatically do the stuff), No( it will only disable the selected), Cancel(will do nothing). Language can be improved, and I need to make Cancel as default instead of No.






> Also the counting breaks really easily lol

Should have addressed that(hopefully) 





> How about showing a list on hover?

I need a bit more time on this.  And as I did not try it, I have my doubts about whether it is better or not.

> Edit: this implementation also does appear to make the box a lot larger

Yes, it has a few additional pixels because I added that button there.

File: launcher/minecraft/mod/ModFolderModel.cpp [hunk 8]
```diff
@@ -238,3 +263,253 @@ void ModFolderModel::onParseSucceeded(int ticket, QString mod_id)
...
+    };
+
+    if (requiredToEnable.size() > 0 || requiredToDisable.size() > 0) {
+        QString title;
+        QString message;
+        QString noButton;
+        QString yesButton;
+        if (requiredToEnable.size() > 0 && requiredToDisable.size() > 0) {
+            title = tr("Confirm toggle");
+            message = tr("Toggling this mod(s) will cause changes to other mods.\n") +
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/ModFolderModel.cpp]:
```suggestion
            message = tr("Toggling these mod(s) will cause changes to other mods.\n") +
```

File: launcher/minecraft/mod/ModFolderModel.cpp [hunk 9]
```diff
@@ -238,3 +263,253 @@ void ModFolderModel::onParseSucceeded(int ticket, QString mod_id)
...
+    };
+    auto rsp = ResourceFolderModel::deleteResources(indexes);
+    for (auto mod : allMods()) {
+        auto id = mod->mod_id();
+        deleteInvalid(m_requiredBy[id]);
+        deleteInvalid(m_requires[id]);
+        mod->setRequiredByCount(m_requiredBy[id].count());
+        mod->setRequiresCount(m_requires[id].count());
+        int row = m_resources_index[mod->internal_id()];
+        emit dataChanged(index(row), index(row, columnCount(QModelIndex()) - 1));
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/ModFolderModel.cpp]: You shouldn't need to cause an update for every column and row
in the whole treeview

File: launcher/ui/pages/instance/ModFolderPage.cpp [hunk 10]
```diff
@@ -135,7 +136,22 @@ void ModFolderPage::removeItems(const QItemSelection& selection)
         if (response != QMessageBox::Yes)
             return;
     }
-    m_model->deleteResources(selection.indexes());
+
+    auto indexes = selection.indexes();
+    auto affected = m_model->getAffectedMods(indexes, EnableAction::DISABLE);
+    if (!affected.isEmpty()) {
+        auto response = CustomMessageBox::selectable(this, tr("Confirm Disable"),
+                                                     tr("The mods you are tring to disable are required by %1 mods.\n"
```
Comment (TheKodeToad) [inline launcher/ui/pages/instance/ModFolderPage.cpp]:
```suggestion
        auto response = CustomMessageBox::selectable(this, tr("Confirm Disable"),
                                                     tr("The mods you are trying to delete are required by %1 mods.\n"
```

File: launcher/minecraft/mod/ModFolderModel.cpp [hunk 11]
```diff
@@ -238,3 +263,253 @@ void ModFolderModel::onParseSucceeded(int ticket, QString mod_id)
...
+
+    if (requiredToEnable.size() > 0 || requiredToDisable.size() > 0) {
+        QString title;
+        QString message;
+        QString noButton;
+        QString yesButton;
+        if (requiredToEnable.size() > 0 && requiredToDisable.size() > 0) {
+            title = tr("Confirm toggle");
+            message = tr("Toggling this mod(s) will cause changes to other mods.\n") +
+                      tr("%n mod(s) will be enabled\n", "", requiredToEnable.size()) +
```
Comment (TheKodeToad) [inline launcher/minecraft/mod/ModFolderModel.cpp:435]: %n might not be a good idea right now as we don't have translation files for en_US so it will probably always appear with the awkward (s)

Comment (Trial97) [reply launcher/minecraft/mod/ModFolderModel.cpp:435]: Yeah, but the alternative also does this. So the text would be the same even if I use %n or %1 and the QString::arg function.

File: launcher/minecraft/mod/ModFolderModel.cpp (hunk 9 above)
Comment (TheKodeToad) [reply launcher/minecraft/mod/ModFolderModel.cpp]: @Trial97 It still looks like it updates it for all rows

Comment (Trial97) [reply launcher/minecraft/mod/ModFolderModel.cpp]: ok now I'm sure that the update only happens when the number changes

File: launcher/ui/pages/instance/ModFolderPage.cpp [hunk 12]
```diff
@@ -135,7 +136,22 @@ void ModFolderPage::removeItems(const QItemSelection& selection)
...
-    m_model->deleteResources(selection.indexes());
+
+    auto indexes = selection.indexes();
+    auto affected = m_model->getAffectedMods(indexes, EnableAction::DISABLE);
+    if (!affected.isEmpty()) {
+        auto response = CustomMessageBox::selectable(this, tr("Confirm Disable"),
+                                                     tr("The mods you are trying to delete are required by %1 mods.\n"
+                                                        "Do you want to disable them?")
+                                                         .arg(affected.length()),
+                                                     QMessageBox::Warning, QMessageBox::Yes | QMessageBox::No, QMessageBox::No)
```
Comment (TheKodeToad) [inline launcher/ui/pages/instance/ModFolderPage.cpp]: Just a nitpick: this should probably have cancel too

File: launcher/ui/widgets/InfoFrame.cpp [hunk 13]
```diff
@@ -227,8 +227,7 @@ void InfoFrame::updateWithResourcePack(ResourcePack& resource_pack)
     setImage(resource_pack.image({ 64, 64 }));
 }
 
-void InfoFrame::updateWithDataPack(DataPack& data_pack)
-{
+void InfoFrame::updateWithDataPack(DataPack& data_pack) {
```
Comment (TheKodeToad) [inline launcher/ui/widgets/InfoFrame.cpp]: Wrong brace style

**Review by TheKodeToad — APPROVED** [review]

**Comment by DioEgizio** [comment]
with this pr prism spams "   169.934 Warning: "Failed to read str property 'version' in mod metadata." (Packwiz::stringEntry:74)" in logs while installing a cf pack. it's especially bad in big packs like atm10, where 
image

**Comment by Trial97** [comment]
@DioEgizio that is not related to this PR.
Here is the PR that removes that exact warning https://github.com/PrismLauncher/PrismLauncher/pull/4388

**Comment by DioEgizio** [comment]
> @DioEgizio that is not related to this PR.
> Here is the PR that removes that exact warning https://github.com/PrismLauncher/PrismLauncher/pull/4388

interesting, because I couldn't reproduce that on develop
