### PR TITLE
fix jpg icons

### LINKED ISSUE #4666: Thick and small modpack icons
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 10.0.0

### Version of Qt

This program uses Qt version 6.10.1.

### Description of bug

When opening the launcher, some of the icons were smaller or streched.

Image

Image

### Steps to reproduce

Update from 9.2.0
Close launcher after update
Open launcher

### Suspected cause

Icon inconssitencies between Prism and CurseForge

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### LINKED ISSUE #4686: icon with jpeg format displayed incorrectly
### Operating System

Windows

### Version of Prism Launcher

10.0.1

### Version of Qt

Qt 6.10.1

### Description of bug

All the modpack icons with jpeg format is displayed much smaller than normal icons if the instance is not chosen when prism launcher is opened, and if the instance is chosen when opening the launcher, the icon becomes wider.

Image

Image

### Steps to reproduce

download any pack with jpeg formatted icon, or change the icon of any existing instances to a jpeg file

### Suspected cause

_No response_

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #4686 and fixes #4666
Forces jpg and jpeg to go through QPixmap first then to Icon. The original behaivior used the QIcon internal engine to build the QPixmap causing some inconsitencies.

### CODE REVIEW

**Review by DioEgizio — APPROVED** [review]

**Comment by TheKodeToad** [comment]
Curious why this suddenly started happening? Also any reason to check for `jpg` or `jpeg` instead of `.jpg` or `.jpeg`.. or maybe better to just do this with all icons (personally unsure)?

**Comment by Trial97** [comment]
Not sure why it started not working.
I'm also against using the same format for all icons as `.ico`, as other extensions work as intended(do not want to break the code in any way).

**Comment by TheKodeToad** [comment]
Isn't a QPixmap always used anyway? Just QIcon might use the same file to generate multiple pixmaps for different situations

**Comment by TheKodeToad** [comment]
FWIW this also affects some of our internal icons which don't use JPEG

**Comment by Trial97** [comment]
The logic differs a bit from reading from [file](https://github.com/qt/qtbase/blob/dev/src/gui/image/qicon.cpp#L465-L479) from [pixmap](https://github.com/qt/qtbase/blob/dev/src/gui/image/qicon.cpp#L426-L435)

>FWIW this also affects some of our internal icons which don't use JPEG

Can you please name one to see if I can reproduce it?

**Comment by TheKodeToad** [comment]
E.g. the legacy ender pearl icon which is super small now

File: launcher/icons/IconList.cpp [hunk 1]
```diff
@@ -36,6 +36,7 @@
 
 #include "IconList.h"
 #include <FileSystem.h>
+#include <qpixmap.h>
```
Comment (Octol1ttle) [inline launcher/icons/IconList.cpp]: fix include

**Comment by Trial97** [comment]
> E.g. the legacy ender pearl icon which is super small now

I do not think I can change that one as that is loaded via `QIcon::fromTheme` 
So Tldr: QT broke something with QIcons, and I can't fully fix it. This fix only applies to external icons.

**Comment by TheKodeToad** [comment]
Looks like we use QIcon::fromTheme for built in icons... so idk how that could've changed
Edit: oops didn't see your post

**Review by TheKodeToad — APPROVED** [review]
Perhaps our legacy icons actually have the size wrong but jpgs are extra janky right now for whatever reason and this seems to fix
