### PR TITLE
Fix crash with mod icon caching

### LINKED ISSUE #1774: Int Overflow Issues Caused by Failure To Release Image
### Operating System

_No response_

### Version of Prism Launcher

prismlauncher_ZN4tN0B7nj

### Version of Qt

QT 6.6.0

### Description of bug

Crashing every 10th (Give or take 1-5) relaunches. 

Looks like an icon caching issue.

[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/13234357/PrismLauncher-0.log)

``Red flag  44811.949 D | 15 pixmap cache misses by eviction happened too fast, doubling cache size to 0
 44811.987 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.026 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.064 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.103 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.141 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.180 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.219 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.257 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.295 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.334 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.373 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.411 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.450 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.488 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
 44812.527 D | Mod "Thermal Series" Had it's icon evicted form the cache. reloading...
``

I was told to report it by ``Trial`` of Prism Discord

### Steps to reproduce

Use launcher? Add thermal to mods ... dunno. It happened 3 times for sure not sure what causes it.

### Suspected cause

Icon Image Cache and Release

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
How to reproduce:
- download multiple large instances( more mods better they can be the same)
- view the mods page for each one of them
- after closing all edit instances windows
- repeat the second and third steps until the UI doesn't respond

Small note I was able to reproduce this with three instances with 800+ mods
Here is the link to the discord message that started this: https://discord.com/channels/1031648380885147709/1118165588200657006/1169052911200903288 if they ever do an issue on GitHub link it to this ticket

### CODE REVIEW

**Review by TayouVR — APPROVED** [review]
I guess I understand kodes concerns, but besides that; as long as the cast back to int works right this code looks good to me.

File: launcher/MTPixmapCache.h [hunk 1]
```diff
@@ -100,22 +101,32 @@ class PixmapCache final : public QObject {
...
         m_last_cache_miss_by_eviciton = now;
         if (m_consecutive_fast_evicitons >= m_consecutive_fast_evicitons_threshold) {
-            // double the cache size
-            auto newSize = _cacheLimit() * 2;
-            qDebug() << m_consecutive_fast_evicitons << "pixmap cache misses by eviction happened too fast, doubling cache size to"
-                     << newSize;
-            _setCacheLimit(newSize);
+            // increase the cache size
+            uint newSize = _cacheLimit() + step;
+            if (newSize >= maxInt) {  // increase it until you overflow :D
```
Comment (Scrumplex) [inline launcher/MTPixmapCache.h:121]: I feel like this could raise warnings with some compilers, as you are comparing signed and unsigned integers. But I might be wrong

File: launcher/MTPixmapCache.h [hunk 2]
```diff
@@ -100,22 +101,32 @@ class PixmapCache final : public QObject {
...
+                newSize = maxInt;
+                qDebug() << m_consecutive_fast_evicitons
+                         << tr("pixmap cache misses by eviction happened too fast, doing nothing as the cache size reached it's limit");
+            } else {
+                qDebug() << m_consecutive_fast_evicitons << tr("pixmap cache misses by eviction happened too fast, doubling cache size to")
```
Comment (Scrumplex) [inline launcher/MTPixmapCache.h]: These seem to be the wrong way around? Also this message still says `doubling`

Comment (Trial97) [reply launcher/MTPixmapCache.h]: Fixed the message.
But can you please be more explicit about what is wrong(I usually do not get the small details)?

**Review by Scrumplex — APPROVED** [review]
