### PR TITLE
make MainWindow cat update instantly

### LINKED ISSUE #763: Background cat doesn't update until toggled on/off
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

Changing the "cat" option in the launcher settings while the cat is visible won't change which cat is shown until it's toggled off and back on, or the launcher is restarted

### Steps to reproduce

1. Press the cat button
2. Go into `settings > launcher > user interface` and change the "cat" setting
3. Close the settings window
4. The cat doesn't change

### Suspected cause

The cat setting is probably only being checked when the cat toggle is enabled, it should switch to the new image after the settings window is closed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by TayouVR**
closes https://github.com/PrismLauncher/PrismLauncher/issues/763

this introduces a signal/slot chain from ThemeCustomizationWidget via LauncherPage and Application to MainWindow. 
Maybe there is a better way to go from that widget to the MainWindow, I'm always up for any suggestions!

### CODE REVIEW

File: launcher/ui/pages/global/LauncherPage.h [hunk 1]
```diff
@@ -58,7 +58,9 @@ class LauncherPage : public QWidget, public BasePage
 
 public:
     explicit LauncherPage(QWidget *parent = 0);
-    ~LauncherPage();
+ ~LauncherPage();
```
Comment (Scrumplex) [inline launcher/ui/pages/global/LauncherPage.h]: oops?

File: launcher/ui/pages/global/LauncherPage.cpp [hunk 2]
```diff
@@ -106,6 +106,8 @@ LauncherPage::LauncherPage(QWidget *parent) : QWidget(parent), ui(new Ui::Launch
     }
     connect(ui->fontSizeBox, SIGNAL(valueChanged(int)), SLOT(refreshFontPreview()));
     connect(ui->consoleFont, SIGNAL(currentFontChanged(QFont)), SLOT(refreshFontPreview()));
+
+    connect(ui->themeCustomizationWidget, &ThemeCustomizationWidget::currentCatChanged, this, &LauncherPage::emitCatUpdate);
```
Comment (Scrumplex) [inline launcher/ui/pages/global/LauncherPage.cpp]: You should be able to connect `APPLICATION->currentCatChanged` directly

Maybe this:

```suggestion
    connect(ui->themeCustomizationWidget, &ThemeCustomizationWidget::currentCatChanged, APPLICATION, &Application::currentCatChanged);
```

File: launcher/ui/pages/global/LauncherPage.h (hunk 1 above)
Comment (TayouVR) [reply launcher/ui/pages/global/LauncherPage.h]: yep, oops

File: launcher/ui/pages/global/LauncherPage.cpp (hunk 2 above)
Comment (TayouVR) [reply launcher/ui/pages/global/LauncherPage.cpp]: that seems to work, thank you!

**Review by Scrumplex — APPROVED** [review]

**Review by flowln — APPROVED** [review]
lgtm, thanks!
