### PR TITLE
Ask before deleting saves as part of a Modpack update

### LINKED ISSUE #2904: Deletes all worlds when updating a modpack
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.7.3

### Description of bug

When updating a modpack instance from the Modrinth tab 1-2 times in a row _(I had to update it a 2nd time because the first time over it removed half of the mods)_ it deletes every world in the saves folder and resets every setting back to what the modpack originally shipped with.

I have spent over 10 hours in a singleplayer world, I am very pissed right now :)

### Steps to reproduce

1. Install a modpack
2. Create a world
3. Update the modpack via the Modrinth tab

### Suspected cause

The launcher should only replace any existing files when updating and shouldn't wipe everything before updating the modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes https://github.com/PrismLauncher/PrismLauncher/issues/2904#issuecomment-3707474864
~~(need to test it though, so I mark it as draft)~~ tested and it works

### CODE REVIEW

File: launcher/InstanceCreationTask.cpp [hunk 1]
```diff
@@ -64,3 +65,28 @@ void InstanceCreationTask::executeTask()
     if (!m_abort)
         emitSucceeded();
 }
+
+void InstanceCreationTask::scheduleToDelete(QWidget* parent, QDir dir, QString path, bool checkDisabled)
+{
+    static const auto savesPath = QString("saves") + QDir::separator();
```
Comment (TheKodeToad) [inline launcher/InstanceCreationTask.cpp]: I made this mistake with mrpack export: QDir::separator actually breaks crossplatform support *because* of being `\` on windows since qt converts all `\` to `/` even there

**Review by Ryex — APPROVED** [review]

File: launcher/InstanceCreationTask.cpp [hunk 2]
```diff
@@ -64,3 +65,27 @@ void InstanceCreationTask::executeTask()
...
+    }
+    qDebug() << "Scheduling" << path << "for removal";
+    m_filesToRemove.append(dir.absoluteFilePath(path));
+    if (checkDisabled) {
+        if (path.endsWith(".disabled")) {  // remove it if it was enabled/disabled by user
+            m_filesToRemove.append(dir.absoluteFilePath(path.chopped(9)));
+        } else {
+            m_filesToRemove.append(dir.absoluteFilePath(path + ".disabled"));
+        }
+    }
```
Comment (getchoo) [inline launcher/InstanceCreationTask.cpp:134]: I think I might be missing something here, but this code seems odd. Why are we adding disabled files *without* the `.disabled` suffix and enabled files *with* it to `m_filesToRemove`? Wouldn't that result in invalid paths?

Couldn't this be better written as something like this?

```cpp
if (!path.endsWith(".disabled") || checkDisabled) {
    m_filesToRemove.append(dir.absoluteFilePath(path))
}
```

Edit: Ok this was actually used in some places before...but I still don't know the hell it works

Comment (Trial97) [reply launcher/InstanceCreationTask.cpp:134]: Here are the reasons why:
- It was used in a lot of places, so I just copied the code
- already check if the file exists at line 49, so it's ok to pass invalid paths
- when creating the index for the pack the file name is used, but the user can enable/disable that file and this change is not reflected in the index(because it would be hard) so as a patch it was pushed that we also check for the disabled mod if the mod was present as enabled at the installation and for the enabled mod if the mod was disabled at installation. This prevents the presence of unwanted mods when you update the instance(like a user enabling an optional mod that is now not optional, but because it is an updated version, the file is not overwritten, and the game crashes because there is 2 mods with the same ID)

**Review by Ryex — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]
