### PR TITLE
fix(InstanceImportTask): stream archive reads

### LINKED ISSUE #4435: Longer extraction speed after quazip replacement / viewport glitchy
### Operating System

Other

### Version of Prism Launcher

10.0

### Version of Qt

6.9.3

### Description of bug

Linux: https://cdn.discordapp.com/attachments/1031823065937629267/1445480470383956222/20251202_202216.mp4?ex=69347497&is=69332317&hm=bb7ded3b593d51ef4008b281bb302cba9e816a9dd9a7e5db395837e79f74a53c&

Windows:
https://cdn.discordapp.com/attachments/1031823065937629267/1444491190786592829/20251130_025148.mp4?ex=6934cfc1&is=69337e41&hm=cf4a589e76c3b5ab193ef60c1dc006779bd6d272d0cc8f349cb6dc76b15c85b9&

On Windows the ui goes bye bye, also takes longer time to extract after quazip replacement. 
On Linux its glitchy and viewport is larger then expected but also slow extract/import speed.

### Steps to reproduce

As for test I've did gregtech new horizons modpack import

### Suspected cause

Who knows.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
Parent PR: #3959 
fixes #4435

Well looks like the detection code for libarchive was a bit more than bad.
It loaded once all the filenames into the memory when it could have just stream the process and exit early.

Also the second commit(other than the renames) fixes a regression regarding qtConcurrent accessing this member variables after the task was ended: 
- removed isCanceled check: if the task is not deleted the flag is handled in the signal otherwise the result is not used anymore anyway.
- created a stack variable for the file name so I do not need to access any member of the task. Only used for the final result in case something actually fails.

### CODE REVIEW

File: launcher/InstanceImportTask.cpp [hunk 1]
```diff
@@ -108,76 +108,77 @@ void InstanceImportTask::downloadFromUrl()
...
-    } else if (packZip.exists("/bin/modpack.jar") || packZip.exists("/bin/version.json")) {
-        // process as Technic pack
-        qDebug() << "Technic:" << true;
-        extractDir.mkpath("minecraft");
-        extractDir.cd("minecraft");
-        m_modpackType = ModpackType::Technic;
-    } else {
-        root = getRootFromZip(packZip.getFiles());
-        setDetails("");
+    if (!packZip.parse([this, &extractDir, &root, cleanPath](MMCZip::ArchiveReader::File* f, bool& stop) {
```
Comment (TheKodeToad) [inline launcher/InstanceImportTask.cpp]: nitpick: maybe don't inline a whole lambda here and stuff it in an auto var instead or keep it as a separate func

Comment (Trial97) [reply launcher/InstanceImportTask.cpp]: done

**Review by Ryex — APPROVED** [review]

File: launcher/InstanceImportTask.cpp (hunk 1 above)
Comment (TheKodeToad) [reply launcher/InstanceImportTask.cpp]: the lambda is still here

**Review by edgars-cirulis — APPROVED** [review]

**Review by DioEgizio — APPROVED** [review]

File: launcher/InstanceImportTask.cpp (hunk 1 above)
Comment (Trial97) [reply launcher/InstanceImportTask.cpp]: Ok now it is done. My bad I did not properly understood what you wanted.
I did not separate it as a function as it touches some variables that are in the current function(root and extractDir)

File: launcher/InstanceImportTask.cpp [hunk 2]
```diff
@@ -108,76 +108,79 @@ void InstanceImportTask::downloadFromUrl()
...
+                return true;
+            }
+        }
+        QCoreApplication::processEvents();
+        return true;
+    };
     // NOTE: Prioritize modpack platforms that aren't searched for recursively.
     // Especially Flame has a very common filename for its manifest, which may appear inside overrides for example
     // https://docs.modrinth.com/docs/modpacks/format_definition/#storage
-    if (packZip.exists("/modrinth.index.json")) {
```
Comment (getchoo) [inline launcher/InstanceImportTask.cpp:162]: The comment above should be moved as well

File: launcher/InstanceImportTask.cpp [hunk 3]
```diff
@@ -108,76 +108,79 @@ void InstanceImportTask::downloadFromUrl()
...
+    if (!packZip.parse(detectInstance)) {
+        emitFailed(tr("Unable to open supplied modpack zip file."));
+        return;
     }
     if (m_modpackType == ModpackType::Unknown) {
         emitFailed(tr("Archive does not contain a recognized modpack type."));
         return;
     }
     setStatus(tr("Extracting modpack"));
+    setDetails("");
```
Comment (getchoo) [inline launcher/InstanceImportTask.cpp]: Is this actually required? I don't think I've seen it before in the codebase...and it's kinda pointless

File: launcher/archive/ExtractZipTask.cpp [hunk 4]
```diff
@@ -104,17 +105,16 @@ auto ExtractZipTask::extractZip() -> ZipResult
             return true;
         })) {
         FS::removeFiles(extracted);
-        return result.has_value() || m_zip_future.isCanceled() ? result
-                                                               : ZipResult(tr("Failed to parse file %1").arg(m_input.getZipName()));
+        return result.has_value() ? result : ZipResult(tr("Failed to parse file %1").arg(fileName));
```
Comment (getchoo) [inline launcher/archive/ExtractZipTask.cpp:108]: ~~Can `m_zip_future` still be cancelled at this point?~~

Edit: I can't read

**Review by getchoo — COMMENTED** [review]
In the future, *please* split unrelated refactors into separate commits. It honestly took me a second to actually tell what the practical changes were in the use after free one, when it was basically just a one line change

**Comment by getchoo** [comment]
This isn't a bug that reached a stable release, so it can be omitted from the changelog

**Comment by Trial97** [comment]
> This isn't a bug that reached a stable release, so it can be omitted from the changelog

image
So, withthe  merged label, this PR will not appear inthe  changelog
This tag is better than omitting in this case

File: launcher/InstanceImportTask.cpp [hunk 5]
```diff
@@ -108,70 +108,72 @@ void InstanceImportTask::downloadFromUrl()
...
+    QString result = path;
+    if (result.startsWith("./"))
+        result = result.mid(2);
+    return result;
 }
 
 void InstanceImportTask::processZipPack()
 {
     setStatus(tr("Attempting to determine instance type"));
+    setDetails("");
```
Comment (getchoo) [inline launcher/InstanceImportTask.cpp]: Not sure why this was added either

Comment (Trial97) [reply launcher/InstanceImportTask.cpp]: done

**Review by getchoo — APPROVED** [review]
