### PR TITLE
fix(flame install): don't assume .zip is a resource pack. default to mod

### LINKED ISSUE #1322: Prism Launcher incorrectly handles .zip mods when downloading a modpack
### Operating System

Windows

### Version of Prism Launcher

Prism 7.1 

### Version of Qt

Qt 6.5.1

### Description of bug

When downloading a mod that has a .zip extension inside a modpack, the mod is not put into the instance's mod folder (aka effectively it goes MIA). This does not occur when directly downloading the mod with the built in mod downloader.

### Steps to reproduce

1. Find a pack that includes said .zip mod (e.g: https://legacy.curseforge.com/minecraft/modpacks/setgamedifficulty-reika)
2. Try to download the pack with the in-launcher modpack downloader
3. Launch Game
4. Get error a dependent mod is missing

### Suspected cause

[Related Support Thread](https://discord.com/channels/1031648380885147709/1126694961430147164)

Possible related issues that might have indirectly caused the bug: #336 #349

The launcher seems to get confused when it sees a zip in the mods section while downloading a pack and leaves it inside the temp directory as follows:
``` 
72875.641 D | Validating whether resources stored as .zip are in the right place
 72875.641 D | Checking "Pam's Mob Drop Crops 1.7.10a.zip" ...
 72875.642 W | Resource pack at "E:/Games/MMC/Instances/.LAUNCHER_TEMP/e65f3f7e-0bf4-41e3-b78d-c3d5b2120745/minecraft/resourcepacks/Pam's Mob Drop Crops 1.7.10a.zip" does not have a valid pack.mcmeta
 72875.644 W | Data pack at "E:/Games/MMC/Instances/.LAUNCHER_TEMP/e65f3f7e-0bf4-41e3-b78d-c3d5b2120745/minecraft/resourcepacks/Pam's Mob Drop Crops 1.7.10a.zip" does not have a valid pack.mcmeta
 72875.650 D | Can't Identify "Pam's Mob Drop Crops 1.7.10a.zip"
 72875.650 D | Can't Identify "Pam's Mob Drop Crops 1.7.10a.zip" at "E:/Games/MMC/Instances/.LAUNCHER_TEMP/e65f3f7e-0bf4-41e3-b78d-c3d5b2120745/minecraft/resourcepacks/Pam's Mob Drop Crops 1.7.10a.zip" , leaving it where it is.
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Ryex**
let identifier move it if needed
fix: #1322

### CODE REVIEW

**Comment by TheKodeToad** [comment]
:thinking: Why isn't this breaking most mods - they usually contain `assets`?

Also, `Pam's Mob Drop Crops 1.7.10a.zip` doesn't look like it'd pass any of this

https://github.com/PrismLauncher/PrismLauncher/blob/67d473aab773e7f94c394ebdde05581dc8f805de/launcher/minecraft/mod/tasks/LocalModParseTask.cpp#L464-L592

The top level files are only `assets/`, `com/` and `Mob Drop Crops 1.7.2 Changelog.txt`

**Comment by Ryex** [comment]
> thinking Why isn't this breaking most mods - they usually contain `assets`?
> 
> Also, `Pam's Mob Drop Crops 1.7.10a.zip` doesn't look like it'd pass any of this
> 
> https://github.com/PrismLauncher/PrismLauncher/blob/67d473aab773e7f94c394ebdde05581dc8f805de/launcher/minecraft/mod/tasks/LocalModParseTask.cpp#L464-L592
> 
> The top level files are only `assets/`, `com/` and `Mob Drop Crops 1.7.2 Changelog.txt`

it's not breaking most mods because most mods are *not* distributed as .zip or are proerly identifyable by the presence of meatadata. 

This mod _HAS NO METADATA GRRRRRRR_  and there is no valid was to distinguish it from some other resource.
fortunately there should be no case of something _other_ than a mod having no metadata.

Because we can't identify it defaulting to placing everything in the mods folder (the resource folder things was a special hack to begin with that was superseded by the identification logic) and then leaving it there is the only valid move.

**Review by Scrumplex — APPROVED** [review]

File: launcher/minecraft/mod/tasks/LocalResourceParse.cpp [hunk 1]
```diff
@@ -44,7 +44,11 @@ static const QMap<PackedResourceType, QString> s_packed_type_names = {
 namespace ResourceUtils {
 PackedResourceType identify(QFileInfo file){
     if (file.exists() && file.isFile()) {
-        if (ResourcePackUtils::validate(file)) {
+        if (ModUtils::validate(file)) {
+            // mods can contain resource and data packs so they much be tested first
```
Comment (getchoo) [inline launcher/minecraft/mod/tasks/LocalResourceParse.cpp]:
```suggestion
            // mods can contain resource and data packs so they must be tested first
```

**Review by getchoo — APPROVED** [review]
