### PR TITLE
fix legacy skin model

### LINKED ISSUE #4503: 3D Skin Renderer not rendering outer layer of some skins as transparent.
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 10.0.0-pre-1

### Version of Qt

6.9.3

### Description of bug

On some specific skins, for some reason the skin renderer shows the any of the fully transparent pixels as black. When zooming it it shows the inner layer as normal. Additionally applying the skin results still works as normal. This happens on multiple skins, and I can't find a pattern to them so far. They're all made by me in Blockbench somewhat recently, I've only had a problem with some of them but not others. I have one of the skin files to try linked in the steps to reproduce but if you need more or to try to find patterns feel free to ask. When I copy the texture of the skin that isn't working into a file that is working, it works.

Image

### Steps to reproduce

- I downloaded the installer from PrismLauncher-Windows-MSVC-Setup-10.0.0-pre1
- Add the skin file linked to the skins folder: https://namemc.com/skin/624df86309251f60, 
- Observe the skin having any of the fully transparent pixels being black.

Image

### Suspected cause

_No response_

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes the black skins issues 
also not the code is ~~copied~~adapted from the actual Minecraft deobfuscated sources
https://mcsrc.dev/#1/1.21.11_unobfuscated/net/minecraft/client/renderer/texture/SkinTextureDownloader#L125

 do I need to add extra license stuff or something?

fixes #4503

fixes https://discord.com/channels/1031648380885147709/1450161125172707390/1450167712738185408, https://discord.com/channels/1031648380885147709/1450161125172707390/1450164360570998784 https://discord.com/channels/1031648380885147709/1450161125172707390/1450163097011749044 https://discord.com/channels/1031648380885147709/1450161125172707390/1450163191450566689 https://discord.com/channels/1031648380885147709/1450161125172707390/1450404673885311047

### CODE REVIEW

**Comment by TheKodeToad** [comment]
Minecraft's source code is proprietary. Best to avoid copying code from it.

**Comment by TheKodeToad** [comment]
Best to do this clean room (https://en.wikipedia.org/wiki/Clean-room_design) if we really wanna be safe - describe the algorithm and have somebody else create it without looking (well maybe we can't afford the lawyer bit :P)

**Comment by Trial97** [comment]
Do not get me wrong but if I say `if (x>5){doStuff();} ` is proprietary does that mean that everybody else can't use it?

Also is a different programing language and is not an algorithm that is complicated. like I'm basically coping pixels.

I will try to not be similar to Minecraft source but there is not so many ways to check every pixel in a region than to for over each

**Review by Ryex — APPROVED** [review]
nah. so long as it was reverse engineered by you were good

**Review by timoreo22 — APPROVED** [review]

**Review by getchoo — COMMENTED** [review]
I'd still be concerned over the licensing of this. Reverse engineering is a fair bit different from decompiling/deobfuscating code in order to basically have the same source as Mojang. The website also enforces the EULA agreement, and makes no clear statement of what exactly the code it generates is licensed under

Some of these lines also appear to be directly copied (like Trial originally said), as well as some general control flow

To be on the safe side, it might be better to copy from a fully FOSS implementation - doesn't the Modrinth App support this for example?

**Comment by Trial97** [comment]
I will do the modrinth approach as it looks much cleaner, but be aware it still is the same as the one from the Minecraft sources:
https://github.com/modrinth/code/blob/fd08dff1e79fdb3ebb2943ca31ac9947a882b1c7/packages/app-lib/src/api/minecraft_skins/png_util.rs#L244-L305
https://github.com/modrinth/code/blob/fd08dff1e79fdb3ebb2943ca31ac9947a882b1c7/packages/app-lib/src/api/minecraft_skins/png_util.rs#L311-L322

**Comment by Trial97** [comment]
@getchoo now the code is copied from modrith(and I mean the copy faces part and set opaque parts)
the notch hack was the same on modrith so no need to change it.

**Comment by TheKodeToad** [comment]
> nah. so long as it was reverse engineered by you were good

FWIW the original implementation had a `& 16777215` obviously copied directly from the decompiled source :P
Let's avoid.. that

**Comment by Trial97** [comment]
Yes that(that is why I mentioned it) now the new one it looks more like the modrinth one and no I can't set/check the alpha other than iterating over the image

File: launcher/minecraft/skins/SkinModel.cpp [hunk 1]
```diff
@@ -1,7 +1,8 @@
 // SPDX-License-Identifier: GPL-3.0-only
 /*
  *  Prism Launcher - Minecraft Launcher
- *  Copyright (c) 2023 Trial97 <alexandru.tripon97@gmail.com>
+ *  Copyright (c) 2023-2025 Trial97 <alexandru.tripon97@gmail.com>
+ *  Copyright (c) 2023 Rinth, Inc
```
Comment (DioEgizio) [inline launcher/minecraft/skins/SkinModel.cpp]:
```suggestion
 *  Copyright (c) 2025 Rinth, Inc.
```
