### PR TITLE
Avoid deadlock when there's a lot of RPs in an instance 

### LINKED ISSUE #624: Crash when clicking on Resource Packs tab if too many RPs are added
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.4.0

### Description of bug

Having too many resource packs added to an instance causes Prism Launcher to crash when switching to the Resource Packs tab. Interestingly, this doesn't happen if RPs are added after loading the Resource Packs tab, even if the tab is closed and re-opened. For me, 6 or more RPs is enough to crash Prism Launcher.

### Steps to reproduce

* Open Prism Launcher and create a new instance
* Edit the instance and open the Resource Packs tab
* Click "View Folder" on the bottom right to open the `resourcepacks` folder
* **Fully close** Prism Launcher
* Add a resource pack, such as [Faithful](https://modrinth.com/resourcepack/faithful-32x), to the `resourcepacks` folder
* Select the file from within `resourcepacks` and press `Ctrl-C` to copy the file
* Press `Ctrl-V` about 10 times to create about 10 copies of the resource pack
* Re-open Prism Launcher
* Edit the instance and open the Resource Packs tab

### Suspected cause

funni memory allocation

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Fixes #624

This adds all parsing tasks to a single ConcurrentTask, so that only a single thread is at use, and so there's available ones for the UI thread to use internally.

NOTE: This does not 100% eliminate the possibility of this problem occurring, since it's possible that the one thread we take is also the last one available, and other threads running in the code base also block on the main thread. However, I think that's pretty unlikely to happen, since most other threads are not blocking on the main thread, and we don't use that many threads to begin with. I also don't know what's the best approach to solve completely this problem, so that's why I've left it at this (though we could perhaps use something like https://doc.qt.io/qt-6/qthreadpool.html#maxThreadCount-prop, idk)

### CODE REVIEW

File: launcher/tasks/ConcurrentTask.cpp [hunk 1]
```diff
@@ -27,10 +27,8 @@ auto ConcurrentTask::getStepTotalProgress() const -> qint64
 
 void ConcurrentTask::addTask(Task::Ptr task)
 {
-    if (!isRunning())
-        m_queue.append(task);
-    else
-        qWarning() << "Tried to add a task to a running concurrent task!";
+    m_queue.append(task);
+    m_total_size += 1;
```
Comment (Scrumplex) [inline launcher/tasks/ConcurrentTask.cpp]: I think we might be able to get rid of this and rely solely on `m_queue.size()`.

Or perhaps make it a short method that just returns `m_queue.size()`.

QQueue is just a QList with extras, so there shouldn't be any performance penalty.

**Review by Scrumplex — APPROVED** [review]

**Comment by DioEgizio** [comment]
https://github.com/PrismLauncher/PrismLauncher/pull/628/commits/83c8a53849569984c2641e232f4e56b14b663fe1 broke build btw

**Comment by flowln** [comment]
oops

**Review by timoreo22 — APPROVED** [review]
