### PR TITLE
Reset status label when deleting instance

### LINKED ISSUE #207: The minecraft version label is inconsistant and weird.
### Operating System

Linux

### Version of Prism Launcher

5.0 via nixpkgs

### Version of Qt

5.15.6

### Description of bug

The bottom-left label is usually used for showing version information about the highlighted instance, but it does not work very well. See steps to reproduce for weird observed behavior:

### Steps to reproduce

1. get yourself a fresh new prism (no instances)
2. install a vanilla 1.19.2 instance
3. "Minecraft"
4. restart
5. "Minecraft 1.19.2"
6. delete instance
7. "Minecraft 1.19.2"

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #207

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]

File: launcher/ui/MainWindow.cpp [hunk 1]
```diff
@@ -1351,10 +1352,11 @@ void MainWindow::on_actionDeleteInstance_triggered()
...
     if (APPLICATION->instances()->trashInstance(id)) {
         ui->actionUndoTrashInstance->setEnabled(APPLICATION->instances()->trashedSomething());
-        return;
+    } else {
+        APPLICATION->instances()->deleteInstance(id);
     }
-
-    APPLICATION->instances()->deleteInstance(id);
+    APPLICATION->settings()->set("SelectedInstance", QString());
+    selectionBad();
```
Comment (TheKodeToad) [inline launcher/ui/MainWindow.cpp:1359]: This will change the behaviour - previously the instance before the deleted instance would be selected.

Comment (Trial97) [reply launcher/ui/MainWindow.cpp:1359]: No, it doesn't change the current behavior. 
In that setting, we already have an invalid id(the id of the deleted instance).
So it doesn't matter if I rewrite it with an empty string.
Also, selectionBad will put all the other stuff to more generic values and then tries again to select a new instance.
I did try side by side to delete an instance on both the current develop and this version and once deleted it selects a new instance.

Comment (TheKodeToad) [reply launcher/ui/MainWindow.cpp:1359]: :o I see

**Review by TheKodeToad — APPROVED** [review]
