### PR TITLE
Identify zip file contents

### LINKED ISSUE #349: CurseForge mods distributed as .zip get downloaded to the resourcepacks folder
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 5.0

### Version of Qt

Qt 6.4.0

### Description of bug

When importing CF modpacks, some mods which are distributed as .zip files (e.g. Mo' Creatures, Custom Mob Spawner for 1.7.10) get downloaded to the resourcepacks folder instead of the mods folder.

### Steps to reproduce

1. Create a CurseForge modpack with e.g. Mo' Creatures 1.7.10
2. Import it to Prism
3. Click the "Folder" button and go to "resourcepacks"

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Ryex**
## Purpose

This PR will add support to identify zip archives (and in some cases bare folders) as containing:

  - [x] Minecraft Data Packs (Presence of a valid `pack.mcmeta` and `data` folder at the archive root.)
    - [x] add `class DataPack : public Resource`
    - [x] add `LocalDataPackParseTask`
    - [x] add tests
  - [x] Minecraft Resource Packs (Presence of a valid `pack.mcmeta` and `assets` folder at the archive root.)
    - [x] add additional checks to `LocalResourcePackParseTask`
    - [x] update tests
  - [x] Minecraft Texture Packs (for older minecraft versions prior to 1.6.1) (Presence of a `pack.txt` at the archive root while not parsing as a resource pack.)
    - [x] add additional checks to `LocalTexturePackParseTask`
    - [x] update tests
  - [x] Optifine / Iris Shaderpacks (Presence of a `shaders` directory at the archive root)
    - [x] add `class ShaderPack : public Resource`
    - [x] add `LocalShaderPackParseTask`
    - [x] add tests
  - [x] A Minecraft Mod (presence of  `mcmod.info` \ `META-INF/mods.toml` or mod loader equivalent  file at the archive root)
    - [X] add a `bool validate(QFileInfo file)` function to `LocalModParseTask`
    - [x] add good tests ? 
  - [x] A Minecraft World (some worlds are distributed by CF, would also be good to import a world into an instance by dropping it on the window.) (detected by a named directory containing a `level.dat`)
  
With this support it will also add check during instance creation to ensure zip files are placed appropriately.
  
Added as a draft for tracking and review purposes.

### Related Issues

When complete this should fix #349.

### Additional Info

will enable the creation of support for managing datapacks.

### CODE REVIEW

**Comment by Ryex** [comment]
Ok, just added a simple validator for Shaderpacks. Only world saves left and then I can write a function to take a file name and tell you what it is if it is any of these things.

I'm a little hung up on how to validate world saves

There are two real questions:

  1. Should this have it's own `Resource` class and parse task like the others? if so where should these classes live? `launcher/minecraft/mod` feels inappropriate but it's where everything else is.  
  2.  Should the validator identify and mark the save format? I know what your thinking "save format"? but there are two major ways a save could present.

  1. an archive containing
```
saves/
├─ <word_name>/
│  ├─ level.dat
```
  3. an archive containing
```
<word_name>/
├─ level.dat
```

The first is done to make extracting the save as easy as unpacking the archive to the minecraft folder while the second requires knowing to unpack to the `saves` folder but both are commonly used and distributed.

I think this change is significant enough that code handling the world save would like to know beforehand without needing to check itself. Should it use a `m_format` enum?

**Comment by flowln** [comment]
> 1. Should this have it's own `Resource` class and parse task like the others? if so where should these classes live? `launcher/minecraft/mod` feels inappropriate but it's where everything else is.

I agree that the name isn't the best, but that folder should really be called `resources` instead of `mod`, considering all that is there now. I just didn't do it because it'll be a big big diff :p
Anyway, i think the world stuff can go there regardless of the current name of that folder

> 2. Should the validator identify and mark the save format?

I think you can make it a separate enum if you really think it would change a lot of the code. It would possibly be similar to [ResourceType](https://github.com/PrismLauncher/PrismLauncher/blob/dd3848d7b161e415c34c3c1c393985b644a88f1c/launcher/minecraft/mod/Resource.h#L10), but only for Worlds. However, I don't see how that'd be such a big thing in the code for parsing it. Wouldn't it just be a simple check like this?
```
if ("saves" folder exists)
    goToSubfolder("saves");
// Continue parsing ...
```

**Comment by Ryex** [comment]
Ok, all the new validators and tests are in place. taking off WIP for preliminary review.

In order to truly close #349 I just have to add the check to the instance creation task after the files are downloaded

**Comment by Ryex** [comment]
And... DONE!
Added a check on FlameInstaceCreationTask to validate zip resources are in the right place.

checked with these modpacks

  * https://www.curseforge.com/minecraft/modpacks/foh-survival-legacy/  1.7.10 modpack that uses Mo's Creatures per #349 (mod in .zip)
  * https://www.curseforge.com/minecraft/modpacks/better-mc-fabric  Has datapacks
  * https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric has datapacks

**Comment by Ryex** [comment]
validated that world saves are handled correctly via https://www.curseforge.com/minecraft/modpacks/mythcraft-revilo2

**Comment by Ryex** [comment]
.. the build fails.... oh that is *weird*. in my machine somehow it knows how to convert QString to QFileInfo...

OH! it's a qt 5 vs 6 thing

**Comment by Ryex** [comment]
ok, fixed

File: launcher/minecraft/mod/DataPack.h [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+    DataPack(QObject* parent = nullptr) : Resource(parent) {}
+    DataPack(QFileInfo file_info) : Resource(file_info) {}
+
+    /** Gets the numerical ID of the pack format. */
+    [[nodiscard]] int packFormat() const { return m_pack_format; }
+    /** Gets, respectively, the lower and upper versions supported by the set pack format. */
+    [[nodiscard]] std::pair<Version, Version> compatibleVersions() const;
+
+    /** Gets the description of the resource pack. */
```
Comment (flowln) [inline launcher/minecraft/mod/DataPack.h]:
```suggestion
    /** Gets the description of the data pack. */
```

File: launcher/minecraft/mod/DataPack.h [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+    bool valid() const override;
+
+    [[nodiscard]] auto compare(Resource const& other, SortType type) const -> std::pair<int, bool> override;
+    [[nodiscard]] bool applyFilter(QRegularExpression filter) const override;
+
+   protected:
+    mutable QMutex m_data_lock;
+
+    /* The 'version' of a resource pack, as defined in the pack.mcmeta file.
+     * See https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack#Formatting_pack.mcmeta
```
Comment (flowln) [inline launcher/minecraft/mod/DataPack.h]:
```suggestion
    /* The 'version' of a data pack, as defined in the pack.mcmeta file.
     * See https://minecraft.fandom.com/wiki/Data_pack#pack.mcmeta
```

File: launcher/minecraft/mod/DataPack.h [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+     */
+    int m_pack_format = 0;
+
+    /** The resource pack's description, as defined in the pack.mcmeta file.
```
Comment (flowln) [inline launcher/minecraft/mod/DataPack.h]:
```suggestion
    /** The data pack's description, as defined in the pack.mcmeta file.
```

File: launcher/minecraft/mod/Mod.cpp [hunk 4]
```diff
@@ -190,3 +195,8 @@ void Mod::finishResolvingWithDetails(ModDetails&& details)
     if (metadata)
         setMetadata(std::move(metadata));
 }
+
+bool Mod::valid() const
+{
+    return !m_local_details.mod_id.isEmpty();
+}
```
Comment (flowln) [inline launcher/minecraft/mod/Mod.cpp]: newline!

File: launcher/minecraft/mod/ResourcePack.cpp [hunk 5]
```diff
@@ -17,15 +17,17 @@ static const QMap<int, std::pair<Version, Version>> s_pack_format_versions = {
     { 3, { Version("1.11"), Version("1.12.2") } }, { 4, { Version("1.13"), Version("1.14.4") } },
     { 5, { Version("1.15"), Version("1.16.1") } }, { 6, { Version("1.16.2"), Version("1.16.5") } },
     { 7, { Version("1.17"), Version("1.17.1") } }, { 8, { Version("1.18"), Version("1.18.2") } },
-    { 9, { Version("1.19"), Version("1.19.2") } }, { 11, { Version("1.19.3"), Version("1.19.3") } },
+    { 9, { Version("1.19"), Version("1.19.2") } },
+    // { 11, { Version("22w42a"), Version("22w44a") } }
```
Comment (flowln) [inline launcher/minecraft/mod/ResourcePack.cpp]: i guess this should be uncommented?

File: launcher/minecraft/mod/ShaderPack.h [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+ *
+ * This class and enum are mostly here as placeholders for validating 
+ * that a shaderpack exsists and is in the right format,
+ * namely that they contain a folder named 'shaders'.
+ *
+ * In the technical sense it would be possible to parse files like `shaders/shaders.properties` 
+ * to get information like the availble profiles but this is not all that usefull without more knoledge of the 
+ * shader mod used to be able to change settings
+ *
+ */
```
Comment (flowln) [inline launcher/minecraft/mod/ShaderPack.h]:
```suggestion
/* Info:
 * Currently For Optifine / Iris shader packs, 
 * could be expanded to support others should they exist?
 *
 * This class and enum are mostly here as placeholders for validating 
 * that a shaderpack exists and is in the right format,
 * namely that they contain a folder named 'shaders'.
 *
 * In the technical sense it would be possible to parse files like `shaders/shaders.properties` 
 * to get information like the available profiles but this is not all that useful without more knowledge of the 
 * shader mod used to be able to change settings.
 */
```

File: launcher/minecraft/mod/ShaderPack.h [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+
+#include <QMutex>
+
+enum class ShaderPackFormat {
+	VALID,
+	INVALID
```
Comment (flowln) [inline launcher/minecraft/mod/ShaderPack.h]:
```suggestion
    VALID,
    INVALID
```

File: launcher/minecraft/mod/ShaderPack.h [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+
+    /** Thread-safe. */
+    void setPackFormat(ShaderPackFormat new_format);
+
+    bool valid() const override;
+
+   protected:
+    mutable QMutex m_data_lock;
+
+		ShaderPackFormat m_pack_format = ShaderPackFormat::INVALID;
```
Comment (flowln) [inline launcher/minecraft/mod/ShaderPack.h]:
```suggestion
    ShaderPackFormat m_pack_format = ShaderPackFormat::INVALID;
```

File: launcher/minecraft/mod/WorldSave.cpp [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+{
+    QMutexLocker locker(&m_data_lock);
+
+    
+    m_save_dir_name = dir_name;
+}
+
+bool WorldSave::valid() const
+{
+	return m_save_format != WorldSaveFormat::INVALID;
```
Comment (flowln) [inline launcher/minecraft/mod/WorldSave.cpp]:
```suggestion
    return m_save_format != WorldSaveFormat::INVALID;
```

File: launcher/minecraft/mod/WorldSave.cpp [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+}
```
Comment (flowln) [inline launcher/minecraft/mod/WorldSave.cpp]: newline!

File: launcher/minecraft/mod/WorldSave.h [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+#include "Resource.h"
+
+#include <QMutex>
+
+class Version;
+
+enum class WorldSaveFormat {
+	SINGLE,
+	MULTI,
+	INVALID
```
Comment (flowln) [inline launcher/minecraft/mod/WorldSave.h]:
```suggestion
    SINGLE,
    MULTI,
    INVALID
```

File: launcher/minecraft/mod/WorldSave.h [hunk 12]
```diff
@@ -0,0 +1,67 @@
...
+
+    bool valid() const override;
+
+
+   protected:
+    mutable QMutex m_data_lock;
+
+    /* The 'version' of a resource pack, as defined in the pack.mcmeta file.
+     * See https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack#Formatting_pack.mcmeta
+     */
```
Comment (flowln) [inline launcher/minecraft/mod/WorldSave.h]:
```suggestion
    /** The format in which the save file is in.
     *  Since saves can be distributed in various slightly different ways, this allows us to treat them separately.
     */
```

File: launcher/minecraft/mod/WorldSave.h [hunk 13]
```diff
@@ -0,0 +1,67 @@
...
+    WorldSaveFormat m_save_format = WorldSaveFormat::INVALID;
+
+		QString m_save_dir_name;
```
Comment (flowln) [inline launcher/minecraft/mod/WorldSave.h]:
```suggestion
    QString m_save_dir_name;
```

File: launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp [hunk 14]
```diff
@@ -0,0 +1,169 @@
...
+
+bool process(DataPack& pack, ProcessingLevel level)
+{
+    switch (pack.type()) {
+        case ResourceType::FOLDER:
+            return DataPackUtils::processFolder(pack, level);
+        case ResourceType::ZIPFILE:
+            return DataPackUtils::processZIP(pack, level);
+        default:
+            qWarning() << "Invalid type for resource pack parse task!";
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp]:
```suggestion
            qWarning() << "Invalid type for data pack parse task!";
```

File: launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp [hunk 15]
```diff
@@ -0,0 +1,169 @@
...
+        zip.close();
+        return true; // only need basic info already checked
+    }
+
+    zip.close();
+
+    return true;
+}
+
+// https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack#Formatting_pack.mcmeta
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalDataPackParseTask.cpp]:
```suggestion
// https://minecraft.fandom.com/wiki/Data_pack#pack.mcmeta
```

File: launcher/minecraft/mod/tasks/LocalDataPackParseTask.h [hunk 16]
```diff
@@ -0,0 +1,65 @@
...
+    bool abort() override;
+
+    void executeTask() override;
+
+    [[nodiscard]] int token() const { return m_token; }
+
+   private:
+    int m_token;
+
+    DataPack& m_resource_pack;
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalDataPackParseTask.h]:
```suggestion
    DataPack& m_data_pack;
```

will need to change code in the .cpp too!

File: launcher/minecraft/mod/tasks/LocalModParseTask.cpp [hunk 17]
```diff
@@ -283,35 +284,45 @@ ModDetails ReadLiteModInfo(QByteArray contents)
...
+bool process(Mod& mod, ProcessingLevel level) {
+    switch (mod.type()) {
+        case ResourceType::FOLDER:
+            return processFolder(mod, level);
+        case ResourceType::ZIPFILE:
+            return processZIP(mod, level);
+        case ResourceType::LITEMOD:
+            return processLitemod(mod);
+        default:
+            qWarning() << "Invalid type for resource pack parse task!";
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalModParseTask.cpp]:
```suggestion
            qWarning() << "Invalid type for mod parse task!";
```

File: launcher/minecraft/mod/tasks/LocalModParseTask.cpp [hunk 18]
```diff
@@ -283,35 +284,45 @@ ModDetails ReadLiteModInfo(QByteArray contents)
...
             zip.close();
-            return;
+            return false;
         }
 
-        m_result->details = ReadMCModTOML(file.readAll());
+        details = ReadMCModTOML(file.readAll());
         file.close();
-
+
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalModParseTask.cpp]:
```suggestion

```

File: launcher/minecraft/mod/tasks/LocalShaderPackParseTask.h [hunk 19]
```diff
@@ -0,0 +1,63 @@
...
+namespace ShaderPackUtils {
+
+enum class ProcessingLevel { Full, BasicInfoOnly };
+
+bool process(ShaderPack& pack, ProcessingLevel level = ProcessingLevel::Full);
+
+bool processZIP(ShaderPack& pack, ProcessingLevel level = ProcessingLevel::Full);
+bool processFolder(ShaderPack& pack, ProcessingLevel level = ProcessingLevel::Full);
+
+/** Checks whether a file is valid as a resource pack or not. */
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalShaderPackParseTask.h]:
```suggestion
/** Checks whether a file is valid as a shader pack or not. */
```

File: launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp [hunk 20]
```diff
@@ -0,0 +1,180 @@
...
+ *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
+ */
+
+#include "LocalWorldSaveParseTask.h"
+
+#include "FileSystem.h"
+
+#include <qdir.h>
+#include <qfileinfo.h>
+#include <quazip/quazip.h>
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp]:
```suggestion
#include <QDir>
#include <QFileInfo>

#include <quazip/quazip.h>
```

File: launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp [hunk 21]
```diff
@@ -0,0 +1,180 @@
...
+
+bool process(WorldSave& pack, ProcessingLevel level)
+{
+    switch (pack.type()) {
+        case ResourceType::FOLDER:
+            return WorldSaveUtils::processFolder(pack, level);
+        case ResourceType::ZIPFILE:
+            return WorldSaveUtils::processZIP(pack, level);
+        default:
+            qWarning() << "Invalid type for shader pack parse task!";
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp]:
```suggestion
            qWarning() << "Invalid type for world save parse task!";
```

File: launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp [hunk 22]
```diff
@@ -0,0 +1,180 @@
...
+        save.setSaveFormat(WorldSaveFormat::MULTI);
+    } else {
+        save.setSaveFormat(WorldSaveFormat::SINGLE);
+    }
+
+    if (level == ProcessingLevel::BasicInfoOnly) {
+        return true; // only need basic info already checked
+    }
+
+    // resurved for more intensive processing
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp]:
```suggestion
    // reserved for more intensive processing
```

File: launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp [hunk 23]
```diff
@@ -0,0 +1,180 @@
...
+    } else {
+        save.setSaveFormat(WorldSaveFormat::SINGLE);
+    }
+
+    if (level == ProcessingLevel::BasicInfoOnly) {
+        zip.close();
+        return true; // only need basic info already checked
+    }
+
+    // resurved for more intensive processing
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp]:
```suggestion
    // reserved for more intensive processing
```

File: launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.h [hunk 24]
```diff
@@ -0,0 +1,62 @@
...
+
+    [[nodiscard]] int token() const { return m_token; }
+
+   private:
+    int m_token;
+
+    WorldSave& m_save;
+
+    bool m_aborted = false;
+};
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.h]: newline!

File: launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp [hunk 25]
```diff
@@ -0,0 +1,180 @@
...
+    if (level == ProcessingLevel::BasicInfoOnly) {
+        return true; // only need basic info already checked
+    }
+
+    // resurved for more intensive processing
+      
+    return true; // all tests passed
+}
+
+static std::tuple<bool, QString, bool> contains_level_dat(QuaZip& zip)
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalWorldSaveParseTask.cpp:108]: since you're not using a struct here, i think it would be nice if you make a comment explaining what exactly is being returned :)

File: launcher/modplatform/flame/FlameInstanceCreationTask.cpp [hunk 26]
```diff
@@ -53,6 +53,16 @@
...
 
+#include <minecraft/mod/tasks/LocalResourcePackParseTask.h>
+#include <minecraft/mod/tasks/LocalTexturePackParseTask.h>
+#include <minecraft/mod/tasks/LocalDataPackParseTask.h>
+#include <minecraft/mod/tasks/LocalModParseTask.h>
+#include <minecraft/mod/tasks/LocalWorldSaveParseTask.h>
+#include <minecraft/mod/tasks/LocalShaderPackParseTask.h>
+#include <minecraft/World.h>
+#include <qdebug.h>
+#include <qfileinfo.h>
```
Comment (flowln) [inline launcher/modplatform/flame/FlameInstanceCreationTask.cpp]:
```suggestion
#include <QDebug>
#include <QFileInfo>

#include "minecraft/mod/tasks/LocalResourcePackParseTask.h"
#include "minecraft/mod/tasks/LocalTexturePackParseTask.h"
#include "minecraft/mod/tasks/LocalDataPackParseTask.h"
#include "minecraft/mod/tasks/LocalModParseTask.h"
#include "minecraft/mod/tasks/LocalWorldSaveParseTask.h"
#include "minecraft/mod/tasks/LocalShaderPackParseTask.h"
#include "minecraft/World.h"
```

File: launcher/modplatform/flame/FlameInstanceCreationTask.cpp [hunk 27]
```diff
@@ -520,3 +507,110 @@ void FlameCreationTask::setupDownloadJob(QEventLoop& loop)
...
+        setProgress(i, total);
+    }
+
+    setAbortable(true);
+}
+
+bool moveFile(QString src, QString dst)
+{
+    if (!FS::copy(src, dst)()) {  // copy
+        qDebug() << "Copy of" << src << "to" << dst << "Failed!";
```
Comment (flowln) [inline launcher/modplatform/flame/FlameInstanceCreationTask.cpp]:
```suggestion
        qDebug() << "Copy of" << src << "to" << dst << "failed!";
```

File: launcher/modplatform/flame/FlameInstanceCreationTask.cpp [hunk 28]
```diff
@@ -520,3 +507,110 @@ void FlameCreationTask::setupDownloadJob(QEventLoop& loop)
...
+        return false;
+    } else {
+        if (!FS::deletePath(src)) {  // remove original
+            qDebug() << "Deleation of" << src << "Failed!";
```
Comment (flowln) [inline launcher/modplatform/flame/FlameInstanceCreationTask.cpp]:
```suggestion
            qDebug() << "Deletion of" << src << "Failed!";
```

File: launcher/modplatform/flame/FlameInstanceCreationTask.cpp [hunk 29]
```diff
@@ -520,3 +507,110 @@ void FlameCreationTask::setupDownloadJob(QEventLoop& loop)
...
+            return false;
+        };
+    }
+    return true;
+}
+
+
+void FlameCreationTask::validateZIPResouces()
+{
+    qDebug() << "Validating resoucres stored as .zip are in the right place";
```
Comment (flowln) [inline launcher/modplatform/flame/FlameInstanceCreationTask.cpp]:
```suggestion
    qDebug() << "Validating whether resources stored as .zip are in the right place";
```

File: launcher/modplatform/flame/FlameInstanceCreationTask.cpp [hunk 30]
```diff
@@ -520,3 +507,110 @@ void FlameCreationTask::setupDownloadJob(QEventLoop& loop)
...
+            } else if (ShaderPackUtils::validate(localFileInfo)) {
+                // in theroy flame API can't do this but who knows, that *may* change ?
+                // better to handle it if it *does* occure in the future
+                qDebug() << fileName << "is a shader pack";
+                validatePath(fileName, targetFolder, "shaderpacks");
+            } else {
+                qDebug() << "Can't Identify" << fileName << "at" << localPath << ", leaving it where it is.";
+            }
+        } else {
+            qDebug() << "Can't find" << localPath << "to validate it, ignoreing";
```
Comment (flowln) [inline launcher/modplatform/flame/FlameInstanceCreationTask.cpp]:
```suggestion
            qDebug() << "Can't find" << localPath << "to validate it, ignoring";
```

**Review by flowln — COMMENTED** [review]
sorry for the big amount of comment changes :sweat_smile:

When you changed the process functions to return a `bool` instead of `void`, you also added checks to see if they returned the expected values. In principle, that's good, however maybe that's a bit too strict. For instance, suppose a resource pack doesn't have a `pack.png` file. It is a valid state, since it will just use the default image on the game, but when you check its result, and returns `false` from the entire processing of the resource pack, you make it so that the lack of an image is considered as a failure. Shouldn't that be changed, so that optional fields don't trigger this kind of failure?

otherwise the logic looks mostly fine, thanks :relaxed:

File: launcher/minecraft/mod/ResourcePack.cpp (hunk 5 above)
Comment (Ryex) [reply launcher/minecraft/mod/ResourcePack.cpp]: will it cause problems with the non numeric version?

Comment (flowln) [reply launcher/minecraft/mod/ResourcePack.cpp]: i _think_ not, iirc this is only used for display, and in the filtering, where it _should_ be fine since it only converts directly to a string :thinking:

**Comment by Ryex** [comment]
ok, all cleaned up now. sorry for the mess.

File: launcher/modplatform/flame/FlameInstanceCreationTask.cpp [hunk 31]
```diff
@@ -520,3 +506,110 @@ void FlameCreationTask::setupDownloadJob(QEventLoop& loop)
...
+    if (!FS::copy(src, dst)()) {  // copy
+        qDebug() << "Copy of" << src << "to" << dst << "failed!";
+        return false;
+    } else {
+        if (!FS::deletePath(src)) {  // remove original
+            qDebug() << "Deletion of" << src << "failed!";
+            return false;
+        };
+    }
+    return true;
```
Comment (flowln) [inline launcher/modplatform/flame/FlameInstanceCreationTask.cpp]: shouldn't this just be a function in `FileSystem.h` using [`std::filesystem::rename`](https://en.cppreference.com/w/cpp/filesystem/rename)? Since it follows the [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/renameat.html), in a failure it will not change the src file, so it retains the behavior you seem to be aiming here.

**Review by flowln — COMMENTED** [review]
> ok, all cleaned up now. sorry for the mess.

don't worry about it, it's a lot of code to keep track off, some stuff inevitably slips by :slightly_smiling_face:

i only have a single note here, otherwise this looks fine for me i think!

File: launcher/modplatform/flame/FlameInstanceCreationTask.cpp (hunk 31 above)
Comment (Ryex) [reply launcher/modplatform/flame/FlameInstanceCreationTask.cpp]: ... WOW, this is peak not written here syndrome. why do I do this to myself?

File: launcher/minecraft/mod/tasks/LocalResourceParse.h [hunk 32]
```diff
@@ -0,0 +1,31 @@
...
+#pragma once
+
+#include <QDebug>
+#include <QFileInfo>
+#include <QObject>
+
+enum class PackedResourceType { DataPack, ResourcePack, TexturePack, ShaderPack, WorldSave, Mod, UNKNOWN };
+namespace ResourceUtils {
+PackedResourceType identify(QFileInfo file);
+}  // namespace ResourceUtils
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalResourceParse.h]:
```suggestion
}  // namespace ResourceUtils

```

File: launcher/minecraft/mod/tasks/LocalResourceParse.cpp [hunk 33]
```diff
@@ -0,0 +1,60 @@
...
+            return PackedResourceType::ShaderPack;
+        } else {
+            qDebug() << "Can't Identify" << file.fileName() ;
+        }
+    } else {
+        qDebug() << "Can't find" << file.absolutePath();
+    }
+    return PackedResourceType::UNKNOWN;
+}
+}
```
Comment (flowln) [inline launcher/minecraft/mod/tasks/LocalResourceParse.cpp]:
```suggestion
}

```

**Review by flowln — APPROVED** [review]
(only noting the newlines :p)

this looks good to me, thank you!

**Comment by Scrumplex** [comment]
> When you changed the process functions to return a `bool` instead of `void`, you also added checks to see if they returned the expected values. In principle, that's good, however maybe that's a bit too strict. For instance, suppose a resource pack doesn't have a `pack.png` file. It is a valid state, since it will just use the default image on the game, but when you check its result, and returns `false` from the entire processing of the resource pack, you make it so that the lack of an image is considered as a failure. Shouldn't that be changed, so that optional fields don't trigger this kind of failure?

any comment about this?

As long as other metadata checks out, it probably shouldn't fail if `pack.png` doesn't exist/is bad.

**Review by Scrumplex — COMMENTED** [review]
LGTM

**Comment by flowln** [comment]
> any comment about this?
> 
> As long as other metadata checks out, it probably shouldn't fail if `pack.png` doesn't exist/is bad.

they changed it already iirc, see [here](https://github.com/Ryex/PrismLauncher/blob/0ebf04a021c633cd6a3cdd76514aa728dc253714/launcher/minecraft/mod/tasks/LocalResourcePackParseTask.cpp#L153)

**Comment by Scrumplex** [comment]
Oh I see, I misread that code :eyes:

**Review by Scrumplex — APPROVED** [review]
