### PR TITLE
[Windows] Autodetect Java from the Microsoft Store version of the official launcher

### LINKED ISSUE #1835: Official launcher Java doesn't get autodetected
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0 (portable)

### Version of Qt

Qt 6.6.0

### Description of bug

I have Java installed from the official launcher in "...\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\javaw.exe" and in "...\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime\jre-legacy\windows-x64\jre-legacy\bin\javaw.exe". I expected it to get autodetected by Prism (#1685).
It didn't get autodetected by Prism.
I tried rebooting my PC & pressing `Refresh` after installing Prism 8.0.

### Steps to reproduce

what I did:
- install the official launcher
- launch the game to make it install Java
- install Prism Launcher 8.0

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #1835
issue reported: Minecraft java detection not working on windows: https://discord.com/channels/1031648380885147709/1167762562155303014/1171227351774937150
Microsoft uses two paths for this:
- on UNIX inside the .minecraft data dir
- on Windows is where Minecraft is installed.

### CODE REVIEW

File: launcher/java/JavaUtils.cpp [hunk 1]
```diff
@@ -440,18 +441,26 @@ QStringList getMinecraftJavaBundle()
...
 #elif defined(Q_OS_WIN32)
     partialPath = QProcessEnvironment::systemEnvironment().value("LOCALAPPDATA", "");
     executable += "w.exe";
+
+    // add the following to the search
+    // C:\Users\USERNAME\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime
+    auto minecraftInstaltionPath =
+        FS::PathCombine(QFileInfo(partialPath).absolutePath(), "Local", "Packages", "Microsoft.4297127D64EC6_8wekyb3d8bbwe");
+    minecraftInstaltionPath = FS::PathCombine(minecraftInstaltionPath, "LocalCache", "Local", "runtime");
+    processpaths << minecraftInstaltionPath;
```
Comment (getchoo) [inline launcher/java/JavaUtils.cpp]:
```suggestion

    // add the microsoft store version of the launcher to the search. the current path is:
    // C:\Users\USERNAME\AppData\Local\Packages\Microsoft.4297127D64EC6_8wekyb3d8bbwe\LocalCache\Local\runtime
    auto minecraftMSStorePath =
        FS::PathCombine(QFileInfo(partialPath).absolutePath(), "Local", "Packages", "Microsoft.4297127D64EC6_8wekyb3d8bbwe");
    minecraftMSStorePath = FS::PathCombine(minecraftMSStorePath, "LocalCache", "Local", "runtime");
    processpaths << minecraftMSStorePath;
```

this isn't exactly the perfect solution since these packages can change in the future, but as long as we keep it up to date this should be fine

**Review by getchoo — CHANGES_REQUESTED** [review]

**Review by getchoo — APPROVED** [review]

**Comment by getchoo** [comment]
image
works as expected

**Review by TayouVR — APPROVED** [review]
I couldn't test it due to MS Store fuckery, but it seems to work, so LGTM.
