### PR TITLE
Fix crash with invalid quilt mod info

### LINKED ISSUE #3495: Invalid json from quilt.mod.json causes Prism to crash upon entering mods tab
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 9.2

### Version of Qt

Qt 6.7.3

### Description of bug

Trying to view the mods tab while having a mod with an invalid quilt.mod.json crashes Prism launcher. As I am playing Fabric I expect it to not parse this file or warn me about this. If I was on Quilt I would expect this to inform me but not crash.

From testing did not encounter the same issue with a purposefully invalid FMJ.

### Steps to reproduce

1. Install Dark Graph 1.2.0 (1.2.1 fixes the invalid json) https://modrinth.com/mod/dark-graph/version/1.2.0.

2. Try to open the mods tab and see Prism launcher crashes

### Suspected cause

Looking at prism logs I see
> 4.311 C | Exception: "quilt.mod.json is not an object"

as the last thing in the log

I'm unsure if any information is private in logs, can share upon request and validation.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Trial97**
fixes #3495

### CODE REVIEW

File: launcher/minecraft/mod/tasks/LocalModParseTask.cpp [hunk 1]
```diff
@@ -293,86 +293,90 @@ ModDetails ReadFabricModInfo(QByteArray contents)
...
+                } else if (icon.isString()) {
+                    details.icon_file = icon.toString();
                 }
-            } else if (icon.isString()) {
-                details.icon_file = icon.toString();
             }
         }
+
+    } catch (const Exception& e) {
+        qWarning() << "Unable to parse mof info:" << e.cause();
```
Comment (dynpatch) [inline launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: `mod`?
nit: a space might be nice to have after `:`

**Review by dynpatch — CHANGES_REQUESTED** [review]

File: launcher/minecraft/mod/tasks/LocalModParseTask.cpp (hunk 1 above)
Comment (Trial97) [reply launcher/minecraft/mod/tasks/LocalModParseTask.cpp]:
```suggestion
        qWarning() << "Unable to parse mod info:" << e.cause();
```

Comment (Trial97) [reply launcher/minecraft/mod/tasks/LocalModParseTask.cpp]: The space is added by the << operator

**Review by TayouVR — APPROVED** [review]

**Review by Ryex — APPROVED** [review]

**Review by ImAwsumm — APPROVED** [review]

**Review by ImAwsumm — APPROVED** [review]
